bin/generateSqlLite, lib/perl/centreon/script/centreontrapd.pm, lib/perl/centreon/trapd/lib.pm
+ centreontrapd: add livestatus check for downtimes
+ centreontrapd: add @DAYS@ macro
=> centreontrapd update

www/include/views/graphs/generateGraphs/generateImage.php
=> RRD Graph Generation - user disconnected

www/include/Administration/brokerPerformance/brokerPerformance.ihtml, www/include/Administration/brokerPerformance/brokerPerformance.php
Allow to display on each line Centreon Broker category filters as connected peers
=> Correct Centreon Broker stats display

www/include/reporting/dashboard/template/viewHostGroupLog.ihtml, www/include/reporting/dashboard/template/viewHostLog.ihtml, www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml, www/include/reporting/dashboard/template/viewServicesLog.ihtml
Allow to freeze actual day and futur days
=> unable to select futur days in reporting datepicker

bin/generateSqlLite, lib/perl/centreon/trapd/lib.pm, www/class/centreonTraps.class.php, www/include/configuration/configObject/traps-groups/DB-Func.php, www/include/configuration/configObject/traps-groups/formGroups.ihtml, www/include/configuration/configObject/traps-groups/formGroups.php, www/include/configuration/configObject/traps-groups/groups.php, www/include/configuration/configObject/traps-groups/help.php, www/include/configuration/configObject/traps-groups/listGroups.ihtml, www/include/configuration/configObject/traps-groups/listGroups.php, www/install/sql/centreon/Update-DB-2.6.5_to_2.7.0.sql
=> Add group system for trap

www/class/centreonGraphTemplate.class.php
=> Avoid PHP Warning when open service whithout graph template

www/class/centreon-clapi/centreon.Config.Poller.class.php
Change group to apache for centreon
=> Change right on clapi generation for centcore

www/class/centreon-clapi/centreon.Config.Poller.class.php
fix the following error while doing a cfgMove
Please check that files in the followings directory are writable by apache user : /etc/centreon-engine/
Please check that files in the followings directory are writable by apache user : /etc/centreon-broker/
=> Fix file owner

www/api/class/centreon_metric.class.php, www/class/centreonMetrics.class.php, www/class/centreonWidget.class.php, www/class/centreonWidget/Params.class.php, www/class/centreonWidget/Params/Connector/HostCategoriesMulti.class.php, www/class/centreonWidget/Params/Connector/HostGroupMulti.class.php, www/class/centreonWidget/Params/Connector/HostMulti.class.php, www/class/centreonWidget/Params/Connector/MetricMulti.class.php, www/class/centreonWidget/Params/Connector/ServiceMulti.class.php, www/class/centreonWidget/Params/Select2.class.php
For a better navigation, select2 is implemented in several widgets.
To be more precise they are for : Hostcategories, Hostgroup, Host, Metric and Service.
=> Add select2 for multiple widgets

libinstall/CentWeb.sh
Fix
https://github.com/centreon/centreon/issues/4077
=> Prepare generateSqlLite before trying to install it

www/class/centreonWidget/Params.class.php
The select2 work with the version 2.8 of Centreon now.
=> Select2 for metrics and services

www/Themes/Centreon-2/style.css
Amélioration de l'espacement entre les objets, sur la barre des statuts.
=> Espacement des objets

www/include/home/customViews/index.php
Trie des valeurs dans les select, pour le choix des vues
=> Trie des valeurs dans les select

www/include/configuration/configGenerate/xml/generateFiles.php
=> Line not useful

www/include/configuration/configGenerate/formGenerateFiles.ihtml, www/include/configuration/configGenerate/formGenerateFiles.php, www/include/configuration/configGenerate/xml/generateFiles.php, www/include/configuration/configGenerate/xml/moveFiles.php, www/include/configuration/configGenerate/xml/restartPollers.php
cleaning generation page :  
- remove
- option "include comments", 
- remove warning with session during the generation, 
- remove use of session_id in post, 
- improve coding style
=> Clean Generation page

config/partition.d/partitioning-data_bin.xml, config/partition.d/partitioning-log_archive_host.xml, config/partition.d/partitioning-log_archive_service.xml, config/partition.d/partitioning-logs.xml
#4877
Updating the partitioning in the config. Change the old myisam to go in InnoDB.
=> #4877 myisam to InnoDB

www/include/configuration/configObject/servicegroup/formServiceGroup.ihtml, www/include/configuration/configObject/servicegroup/formServiceGroup.php
remove old source code dedicated to QuickForm, remove old filters not used and improve HTML
=> Improbe SG Config page

www/class/centreonACL.class.php
Fix problem in reporting. 
--> When a simple user goes to Dashboad > Host, services of the host are never displayed. 
An ACL problem has been detected : the query was not working.
=> Fix problem in reporting

www/include/home/customViews/index.ihtml
The problem exists when at least one created view.
=> Disable the edit mode when connecting to the WEB interface.

doc/en/release_notes/centreon-2.4/index.rst, doc/en/release_notes/centreon-2.5/index.rst, doc/en/release_notes/centreon-2.6/index.rst
Fixes a typo in english text in release notes so they do not repeat on next release.
=> Fix repeating typo.

doc/en/installation/from_packages.rst, doc/fr/installation/from_packages.rst
Change place for the installation of Centreon in the documentation and add description for GPG key and mariadb.
=> Doc installation

www/include/configuration/configGenerateTraps/formGenerateTraps.php
fix #4972  
--> issue regarding the trap generation system : synctrap was never send
=> Trap Generation Problem

www/install/steps/process/installConfigurationDb.php
* Change the information of open files limit, during installation
Ref: #5017
=> Add systemd information MariaDB open files limit

www/api/index.php, www/class/centreonAuth.class.php
=> Add possibility for a user to have access to API and not to Frontend

doc/en/api/clapi/objects/contacts.rst
=> Wrong Language

www/class/centreonService.class.php, www/include/views/graphs/graphs.php
=> Wrong Hosttitle in GraphTitle on Graphpage #4964

www/class/centreonConfigCentreonBroker.php
The fix problem of help tooltip doesn't display when save a Centreon Broker configuration or create a new Centreon Broker configuration.
Ref: #4944
=> The help information work on Centreon Broker configuration

www/class/centreon-clapi/centreonAPI.class.php
* Fix namespace problem when CLAPI object is from a module
Ref: #4921
=> Can export when a module with CLAPI is installed

www/class/centreonAuth.class.php
Log every action for logging and logout not only on debug
Ref: #4924
=> Log every action for logging and logout

www/include/reporting/dashboard/template/viewServicesLog.ihtml
* Fix the style of the page service dashboard reporting
Ref: #4934
=> Service dashboard reporting page has the good style

www/include/monitoring/status/Hosts/hostJS.php
Thank @hocinetwork
* Fix clean up before reopen the popin
Ref: #4862
=> Send correct acknownlege command on host monitoring page

cron/centreon-backup.pl
* Load new configuration and convert to old format
Ref: #4965
=> Backup load correctly the configuration

cron/centreon-backup.pl
* Better test for configuration parameters
* Add messages when bad configuration
Ref: #4726
=> Human error message when bad SCP export configuration

www/class/centreonPerformanceService.class.php
From Monitoring > hosts, clic on graph icone, an error appear in the log file.
=> Fix problem on graph when user ask to display graphs of a hosts

www/class/config-generate/correlation.class.php, www/class/config-generate/host.class.php
* Fix problem with virtual host from BAM
* The dependancy and parentship is generated only if hosts and services are activated
=> Correlation with bam

www/include/home/customViews/widgetParam.php
USe Centreon Web 2.7.x style for button
=> Apply new Centreon style on button

www/install/sql/centreon/Update-DB-2.6.6_to_2.7.0-RC1.sql
=> #5064 sql update script syntax problem

www/class/centreon-clapi/centreonHostGroup.class.php
* Fix the export of hostgroup. Add HG;ADD command
Ref: #4878
=> Centreon CLAPI export add hostgroup

www/include/configuration/configObject/host_categories/formHostCategories.ihtml, www/include/configuration/configObject/hostgroup/formHostGroup.ihtml, www/lib/HTML/QuickForm/select2.php
* The scroll is enabled on host category and host group configuration
Refs: #4282
=> Activate scroll on host category and host group configuration

www/include/configuration/configObject/service/formService.php
Improve loading performance for service configuration page when a LDAP server timeout
=> Improve loading performance for service configuration page

www/include/monitoring/downtime/listDowntime.php, www/include/monitoring/downtime/template/listDowntime.ihtml
Update hostname, service description and links when object is a BA
=> fix #5014 - Display real BA name instead of _Module_BAM_

www/include/monitoring/status/TopCounter/xml/statusCounter.php
#5126
The poller state logo change when we disabled the poller
=> Poller status

www/class/centreonConfigCentreonBroker.php
* Can save multiple column in InfluxDB output config
Ref: #5058
=> Save metrics column on InfluxDB output config

doc/en/installation/prerequisites.rst
=> Fixed typo in english doc

www/include/views/graphs/javascript/centreon-graph.js
This fix removes curves artifacts by changing lines type
fixes #4644
fixes #5143
=> remove curves artifacts

www/include/views/graphs/generateGraphs/generateMetricImage.php, www/include/views/graphs/graph-split.html
=> Export the chart image when the chart view is split

www/class/centreonHost.class.php
=> fix  error during generation #5214

www/include/monitoring/objectDetails/serviceDetails.php
=> #5118 Convert string in UTF-8

www/class/centreon-clapi/centreonAPI.class.php
* Add default filter for export with select
Ref: #4868
=> CLAPI export can filter for a selected host

www/class/centreon-knowledge/procedures.class.php, www/class/centreon-knowledge/procedures_DB_Connector.class.php
=> Add PDO for KB

www/class/centreon-clapi/centreonAPI.class.php, www/class/centreonAuth.LDAP.class.php
Uses 'CentreonAuthLDAP' class to check user/password against configured LDAP servers in Centreon.
=> CLAPI with LDAP Authentication

tests/rest_api/rest_api.postman_collection.json
ACL Menus modifié ainsi qu'ACL Resources.
=> Modifications tests Postman

behat.yml, features/ContactGroupCreationDuplication.feature, features/bootstrap/ContactGroupCreationDuplicationContext.php
It tests simple operations (Add, Duplicate and Delete)
=> ContactGroupCreationDuplication added

tests/rest_api/rest_api.postman_collection.json
=> Name of Engine Cfg in Postman tests changed

www/class/centreonACL.class.php, www/include/configuration/configObject/meta_service/metric.php
#5358
Now we can modify a meta-service with an user.
=> Fix display of hosts and services in metaservices with non admin user

www/api/class/centreon_configuration_servicetemplate.class.php
https://github.com/centreon/centreon/pull/5389
=> Second Fix: Select All don't work on service categories

www/class/centreon-clapi/centreonContactGroup.class.php, www/class/centreon-clapi/centreonHostGroup.class.php
Fix contact group filtered member export
=> #5297 [CLAPI] Several bugs on HG / CG when export is filtered

www/class/centreonLog.class.php
Error in the name of the variable
=> Variable problem

bin/centreon-partitioning.php, cron/centreon-partitioning.php, www/class/centreon-partition/config.class.php
Enhance configuration handling by reading partitioning configuration in centreon database
=> enhance configuration handling

www/class/centreon-partition/partEngine.class.php
Fix https://github.com/centreon/centreon/issues/5429
=> + Enhance partitioning table status check

www/class/centreon-clapi/centreonHost.class.php
Save changes in logs (Set/Add/Del)...
=> CLAPI - Host - Save changes in logs

www/class/centreon-clapi/centreonCommand.class.php
Ref https://github.com/centreon/centreon/issues/5455
=> + Fix double command export with CLAPI

cron/centreon-backup-mysql.sh
ps --ef | grep mysql => no datadir information
Using mysql command help
=> [FIX]  ERROR: Can't find MySQL datadir

www/include/configuration/configServers/DB-Func.php
When you deleted a host or a service, all poller had "conf changed"
=> All pollers had "config changed"

www/include/monitoring/status/Services/service.php
Move include to get correct values for $sort_type and $order
=> #5410 #5287 - Fix sort and order in real time services monitoring

www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
=> #5402 - order by status then by service description

www/class/centreon-clapi/centreonServiceTemplate.class.php
This class works like centreonService.class.php, and we pass the alias (i.e. the login) when setting contacts to a service template.
=> Replacing contact_name by contact_alias

Jenkinsfile, www/class/centreonMeta.class.php, www/include/configuration/configObject/meta_service/formMetaService.php
- Fix metric select
- Fix contactgroups init values
=> Fix metaservice form

www/class/centreonAuth.LDAP.class.php, www/class/centreonLDAP.class.php
Need to delete the contact and re-autoimport it. 
Be careful if you use the contact for notification: it won't work because of the coma (separator in configuration)
=> LDAP import with comma #4867

www/class/centreon-clapi/centreonCentbrokerCfg.class.php
fix(clapi): Fix importation of an existing broker configuration option on master
#5640
=> fix(clapi): Fix importation of an existing broker configuration option

www/class/centreon-clapi/centreonCentbrokerCfg.class.php
=> fix(clapi): remove bad check for import field on master

www/include/reporting/dashboard/DB-Func.php
The problem comes if the service is in X acl groups for a same user.
=> fix(area/reporting): dashboard-with-acl

www/include/home/customViews/widgetParam.html
=> fix(C.V.): Fix missing parameter in redirect action on master

doc/en/release_notes/centreon-2.8/centreon-2.8.13.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.13.rst
fix(doc): Add release note Centreon web 2.8.13
=> Complete release note for Centreon web 2.8.13

doc/en/release_notes/centreon-2.8/centreon-2.8.13.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.13.rst, www/install/sql/centreon/Update-DB-2.8.12_to_2.8.13.sql, www/install/sql/centreon/Update-DB-2.8.13_to_2.9.0.sql
release note and install script
=> Update 2.8.13 to master

features/bootstrap/MassiveChangeHostsContext.php, www/include/configuration/configObject/host/formHost.ihtml
Remove useless massive change option in the host configuration page and fix tests accordingly.
=> Master fix massive change

www/include/common/javascript/centreon/popin.js, www/include/home/customViews/index.ihtml
Add possiblitiy to change centreon popin
to a modal
Refs: #5607
=> feat(popin) : improve popin to modal

features/bootstrap/InfluxdbContext.php
It seems like test is sometimes failing because of this missing condition.
The service status containing performance data seems to be processed
before the InfluxDB endpoint is connected, so no perfdata gets stored.
=> fix(test): wait for Centreon Broker to be connected in InfluxDB test.

www/class/centreon-clapi/centreonAPI.class.php, www/class/centreon-clapi/centreonContact.class.php, www/class/centreon-clapi/centreonUtils.class.php, www/class/centreonAuth.class.php, www/class/centreonUtils.class.php, www/include/common/common-Func.php, www/include/configuration/configObject/contact/DB-Func.php
contact : fix language for clapi import / check password pattern for insert
centreonAuth : check password pattern for auth / update myCrypt function
commonFunc -> create two function for check and encode password
DBfunc -> check password pattern for add and update form
=> fix(auth): Fix encoding password #5654

bootstrap.php, src/CentreonLegacy/Core/Utils/Utils.php, www/api/index.php, www/class/centreon-clapi/centreonAPI.class.php, www/class/centreon-clapi/centreonContact.class.php, www/class/centreon-clapi/centreonObject.class.php, www/class/centreonAuth.SSO.class.php, www/class/centreonAuth.class.php, www/include/configuration/configObject/contact/DB-Func.php, www/include/core/login/processLogin.php
contact : fix language for clapi import / check password pattern for insert/update
centreonAuth : check password pattern for auth / update myCrypt function
DBfunc -> check password pattern for add and update form
use dependencyInjector
=> fix(auth): Fix encoding password on master #5653

www/include/monitoring/common-Func.php, www/include/monitoring/objectDetails/template/hostDetails.ihtml, www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Add also links for the configuration :)
=> Contacts display on monitoring view #4981

www/include/home/customViews/index.ihtml
There is still some stuffs not clean. Like when we don't want to select all from the popup. But the problem comes directly from select2 js. Need to have a more independant library from the DOM context.
=> Fix user multiselect in custom views #5029

www/class/centreon-clapi/centreonEngineCfg.class.php
=> Fix - variable initialization

features/bootstrap/WidgetContext.php
Do not refresh widget listing page manually when installing and
removing widget as this could prevent installation or removal
from working.
=> fix(test): fix widget installation and removal tests.

Jenkinsfile, features/Acknowledgement.feature, features/CommandConfiguration.feature, features/ContactConfiguration.feature, features/DowntimeStartAndStop.feature, features/GeneratePoller.feature, features/HostConfiguration.feature, features/HostGroupConfiguration.feature, features/HostTemplateBasicsOperations.feature, features/Module.feature, features/RestApi.feature, features/RestartCentreonEngine.feature, features/ServiceConfiguration.feature, features/ServiceGroupConfiguration.feature, features/ServiceTemplateConfiguration.feature, features/Widget.feature
Add a new stage to the Jenkinsfile to run only critical tests before running the entire test suite.
=> Critical tests

features/bootstrap/DowntimeStartAndStopContext.php
Increase duration of downtime end detection in tests.
=> Fix downtime stop tests

www/include/monitoring/status/TopCounter/xml/statusCounter.php
Add SELECT DISTINCT service_id from centreon_acl table
ref: #5616
=> fix(top counter): display too much resources

cron/centreon-backup.pl
Not so proud but necessary... :p
=> temporary backup dir not always backup

tests/rest_api/realtime_rest_api.postman_collection.json
Add 2s timeout after poller generation to wait objects in realtime
=> fix realtime api acceptance tests

www/include/monitoring/status/Hosts/xml/hostXML.php, www/include/monitoring/status/Services/service.php, www/include/monitoring/status/Services/xml/serviceXML.php, www/include/monitoring/status/ServicesServiceGroups/serviceGridBySG.php, www/include/monitoring/status/ServicesServiceGroups/serviceGridBySGJS.php, www/include/monitoring/status/ServicesServiceGroups/templates/serviceGrid.ihtml, www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
=> fix(monitoring) use default params to sort services

www/class/centreonGMT.class.php
Hi,
If there was an error during an SQL query, do not make a "fetch".
Regards
=> Fix condition - Error query BDD

www/class/centreon-clapi/centreonServiceTemplate.class.php
=> fix(clapi) fix duplicate htpl in stpl

behat.yml, features/DowntimeDST.feature, features/bootstrap/DowntimeDSTContext.php, www/class/centreonDowntime.Broker.class.php, www/class/centreonExternalCommand.class.php, www/class/centreonGMT.class.php, www/include/monitoring/downtime/AddDowntime.php
to cherry-pick on master
An other pull request is coming for 2.7.x
=> Manage downtimes with dst (recurrent and realtime)

www/include/views/graphs/exportData/ExportCSVServiceData.php
=> fix(graph) fix export with empty metric

www/class/centreonContactgroup.class.php
=> fix(acl): Check timeout

www/api/class/centreon_configuration_trap.class.php
Sql query updated for getting the Vendor name and Traps name in a configured Trap Group
Ref:PR-5542 to master
=> fix(MON)TrapsSNMPGroupĈonfiguration_MASTER

www/class/centreon-clapi/centreonCentbrokerCfg.class.php
=> fix(clapi) authorize id 0

tests/clapi_export/clapi-configuration.txt
=> fix(test) remove duplicate configuration

www/include/configuration/configKnowledge/display-serviceTemplates.php
Remove space between '%' symbole and search variable
Fix: #5762
=> fix(configuration): Fix SQL request to search servicetemplate by name

www/class/centreonGraph.class.php
It's gonna be LEGEN... wait for it... DARY!
=> feat(chart): add legend name when defined

tests/clapi_export/clapi-configuration.txt
=> fix(test) Clean clapi configuration test

www/include/configuration/configObject/service/DB-Func.php
=> checkIllegalChar one time only

doc/en/api/clapi/objects/realtime_downtimes.rst, doc/fr/api/clapi/objects/realtime_downtimes.rst, features/RestApi.feature, lib/Centreon/Object/Downtime/RtDowntime.php, tests/rest_api/realtime_rest_api.postman_collection.json, www/class/centreon-clapi/centreonRtDowntime.class.php, www/class/centreon-clapi/centreonService.class.php, www/class/centreonInstance.class.php, www/class/centreonServicegroups.class.php
#5796
-add check on rt downtime
-check invalid date
-change host/service separator of | to ,
-add to add/show multi object downtime with | separator
-update doc and acceptance
-change order/declaration of service inheritance on add method
=> Api rt exception 2.8

doc/en/installation/from_centreon.rst
Slight changes of expressions, missing words and typos
Ref: #5825
=> fix (doc): Improve installation documentation

doc/en/configuration_guide/timeperiod.rst
Typo fixes, expression changes, missing words
Ref: #5828
=> fix (doc): Improve Time Period documentation

www/class/centreonGMT.class.php
getMyGTMFromUser method did not return the user GMT, return added
Refs: none
=> fix(MON)downtimeStartandStop_test issue

www/include/configuration/configObject/contact/DB-Func.php
Local users password appear in admin logs.
=> fix(conf): some field was not encoded

doc/en/api/clapi/objects/time_periods.rst, doc/fr/api/clapi/objects/time_periods.rst
Fix name of timeperiod object
ref: #5637
=> fix(doc): clapi replace TIMEPERIOD by TP

www/install/insertBaseConf.sql, www/install/sql/centreon/Update-DB-2.8.15_to_2.8.16.sql
Remove occurence of NDO protocol
Fix: #5830
=> fix(install): Remove non existing broker protocol

doc/en/api/clapi/objects/realtime_downtimes.rst, doc/fr/api/clapi/objects/realtime_downtimes.rst, features/RestApi.feature, lib/Centreon/Object/Downtime/RtDowntime.php, tests/clapi_export/clapi-configuration.txt, tests/rest_api/realtime_rest_api.postman_collection.json, www/class/centreon-clapi/centreonRtDowntime.class.php, www/class/centreon-clapi/centreonService.class.php, www/class/centreonInstance.class.php, www/class/centreonServicegroups.class.php
#5735
-add check on rt downtime
-check invalid date
-change host/service separator of | to ,
-add to add/show multi object downtime with | separator
-update doc and acceptance
-change order/declaration of service inheritance on add method
=> Api rt exception master

doc/en/api/clapi/objects/realtime_downtimes.rst, doc/fr/api/clapi/objects/realtime_downtimes.rst, www/class/centreon-clapi/centreonRtDowntime.class.php
=> fix(clapi) host/service relation

features/RestApi.feature, tests/rest_api/rest_api.postman_environment.json
=> fix(test) ndo protocol

doc/fr/upgrade/index.rst
=> fix(doc): translate missing paragraph

lib/Centreon/Object/Relation/Host/Parent/Host.php, lib/Centreon/Object/Relation/Relation.php, www/class/centreon-clapi/centreonHost.class.php
Add host parents in the export.
Related to issue #5605
=> Hosts parentship master

lib/Centreon/Object/Object.php, lib/Centreon/Object/Relation/Host/Parent/Host.php, lib/Centreon/Object/Relation/Relation.php, www/class/centreon-clapi/centreonHost.class.php
Add host parents in the export.
Related to issue #5605
=> feat(export): Add parentship for hosts

www/include/configuration/configObject/host/formHost.ihtml, www/include/configuration/configObject/service/formService.ihtml
=> fix(macro) host/service macro visibility

features/MassiveChangeHosts.feature, www/include/configuration/configObject/host/formHost.ihtml
=> fix(host configuration) add massive change contact/cg update mode

www/api/class/centreon_administration_aclgroup.class.php
#5624
Now the filter of "ACL Resource Groups" works when it's a simple user.
=> fix(ACL): Filter ACL resource group for simple users

www/include/monitoring/objectDetails/common-func.php
=> fix(macro) hide password macro in Executed Check Command Line

doc/en/installation/from_centreon.rst, doc/fr/installation/from_centreon.rst
=> fix(doc): improve documentation install using ISO

doc/en/api/clapi/objects/realtime_downtimes.rst, doc/fr/api/clapi/objects/realtime_downtimes.rst, lib/Centreon/Object/Downtime/RtDowntime.php, tests/rest_api/realtime_rest_api.postman_collection.json, www/class/centreon-clapi/centreonRtDowntime.class.php
* feat(clapi) add cancel downtime
* update doc
* fix test
=> Api cancel downtime (#5894)

www/include/Administration/brokerPerformance/brokerPerformance.php
As the title said, prepare et execute the query to prevent SQL injection.
=> fix(security): prepare query and execute it

www/class/centreonUser.class.php
Update SQL query to prevent SQL injection in setRotate form
Refs: MON-2129
=> fix(mon)SQL-Vulnerability_In_CustomViews

libinstall/functions
- Add missing parameters to create user
- Create function to create file with question
- Create missing /etc/sudoers.d/centreon
ref: #5785
=>  fix(install): create centreon sudoer file if not exist

www/class/centreonUser.class.php
Update SQL query to prevent SQL injection in setRotate form
Refs: MON-2129
=> fix(mon)vunerability in customViews_MASTER

www/include/configuration/configObject/host/listHost.php
Add _GET to get host search filter
Change URL for enable/disable host
fix: #5711
=> Fix(configuration): Host search not saved when activate/desactivate a host

www/include/Administration/brokerPerformance/brokerPerformance.php
As the title said, prepare et execute the query to prevent SQL injection.
=> fix(security): prepare and execute query

doc/en/api/clapi/objects/hosts.rst, doc/fr/api/clapi/objects/hosts.rst, lib/Centreon/Object/Media/Media.php, www/class/centreon-clapi/centreonHost.class.php, www/class/centreon-clapi/centreonObject.class.php
=> feat(api) add host getparam master

lib/Centreon/Object/Media/Media.php, www/class/centreon-clapi/centreonHost.class.php, www/class/centreon-clapi/centreonObject.class.php
=> API: Add HOST getparam

www/class/centreonLogAction.class.php, www/include/Administration/configChangelog/viewLogs.php, www/include/options/accessLists/actionsACL/DB-Func.php, www/include/options/accessLists/actionsACL/actionsConfig.php, www/include/options/accessLists/actionsACL/listsActionsAccess.ihtml, www/include/options/accessLists/actionsACL/listsActionsAccess.php, www/include/options/accessLists/groupsACL/DB-Func.php, www/include/options/accessLists/groupsACL/groupsConfig.php, www/include/options/accessLists/groupsACL/listGroupConfig.ihtml, www/include/options/accessLists/groupsACL/listGroupConfig.php, www/include/options/accessLists/menusACL/DB-Func.php, www/include/options/accessLists/menusACL/listsMenusAccess.ihtml, www/include/options/accessLists/menusACL/listsMenusAccess.php, www/include/options/accessLists/menusACL/menusAccess.php, www/include/options/accessLists/resourcesACL/DB-Func.php, www/include/options/accessLists/resourcesACL/listsResourcesAccess.ihtml, www/include/options/accessLists/resourcesACL/listsResourcesAccess.php, www/include/options/accessLists/resourcesACL/resourcesAccess.php
+ Add 'Enable' and 'Disable' actions in 'More actions...' drop down menu,
+ Add line coloration when disabled,
+ Add logging for every actions on every acl object types.
=> feat(admin): add more actions and logging for ACL management

doc/en/api/clapi/objects/hosts.rst, doc/fr/api/clapi/objects/hosts.rst, www/class/centreon-clapi/centreonHost.class.php
add multi param
add missing param
=> Feat update host get param

www/class/centreonNotification.class.php, www/include/configuration/configObject/contact/displayNotification.php, www/include/configuration/configObject/contactgroup/displayNotification.php
=> Contact notification

www/api/class/centreon_performance_service.class.php
=> fix graph filter

www/include/monitoring/common-Func.php
Hi,
'asort' with SORT_NATURAL was added only in PHP version 5.4.
=> Compatibility with PHP version 5.3

www/class/centreonLogAction.class.php, www/include/Administration/configChangelog/viewLogs.php, www/include/options/accessLists/actionsACL/DB-Func.php, www/include/options/accessLists/actionsACL/actionsConfig.php, www/include/options/accessLists/actionsACL/listsActionsAccess.ihtml, www/include/options/accessLists/actionsACL/listsActionsAccess.php, www/include/options/accessLists/groupsACL/DB-Func.php, www/include/options/accessLists/groupsACL/groupsConfig.php, www/include/options/accessLists/groupsACL/listGroupConfig.ihtml, www/include/options/accessLists/groupsACL/listGroupConfig.php, www/include/options/accessLists/menusACL/DB-Func.php, www/include/options/accessLists/menusACL/listsMenusAccess.ihtml, www/include/options/accessLists/menusACL/listsMenusAccess.php, www/include/options/accessLists/menusACL/menusAccess.php, www/include/options/accessLists/resourcesACL/DB-Func.php, www/include/options/accessLists/resourcesACL/listsResourcesAccess.ihtml, www/include/options/accessLists/resourcesACL/listsResourcesAccess.php, www/include/options/accessLists/resourcesACL/resourcesAccess.php
=> #5841 more actions and logging for acl

www/include/monitoring/status/TopCounter/xml/statusCounter.php, www/install/createTablesCentstorage.sql, www/install/php/Update-2.8.17_to_2.8.18.php
=> fix(sql): add index in centreon_acl for topcounter

www/class/centreonConfigCentreonBroker.php
Old value was 100 000. Proposal to set lower limit to 10 000
ref: #6011
=> fix(conf): Propose low limit of EventMaxQueueSize to 10000

www/include/Administration/parameters/DB-Func.php
Set "broker" value for "broker" key in order to offers possibility to use old version of Centreon DSM for example
Ref: #6029
=> fix(admin): add default value for broker option

www/class/centreon-knowledge/wikiApi.class.php, www/include/Administration/parameters/DB-Func.php, www/include/Administration/parameters/knowledgeBase/formKnowledgeBase.html, www/include/Administration/parameters/knowledgeBase/formKnowledgeBase.php, www/include/Administration/parameters/knowledgeBase/help.php
=> Add CURLOPT_SSL_ to bypass certificate

doc/en/administration_guide/02l.rst
Fixes  documentation for Lua Outputs section (Broker configuration in administration guide)
=> Typo and format fixes of Lua Outputs section

doc/fr/administration_guide/02l.rst
Administration guide (Broker configuration section) for french version.
=> Fix Lua outputs section

www/class/centreon-clapi/centreonHost.class.php
fix clapi export with hosts parent relations when hosts have big id
=> fix clapi export with hosts parent relations

www/Themes/Centreon-2/centreon-loading.css, www/include/core/header/htmlHeader.php
=> feat(css) add loading css

www/class/centreon-clapi/centreonAPI.class.php
=> feat(centreonApi) add clapi set option

www/install/insertBaseConf.sql, www/install/php/Update-2.8.18_to_2.8.19.php, www/install/sql/centreon/Update-DB-2.8.18_to_2.8.19.sql
=> fix(perf): fix centreon_acl index creation on update

www/include/configuration/configGenerateTraps/formGenerateTraps.php
* Add ACL control to display list of available pollers
Ref: #6043
=> fix(acl): SNMP trap poller generation

lib/Centreon/Object/Instance/Instance.php, www/class/centreon-clapi/centreonHost.class.php
when I import a host with unknown poller by clapi
=> fix(clapi) link host with default poller if unknown poller

www/class/centreon-clapi/centreonService.class.php
When using CLAPI export with filter and select option, add line for service was first of add host itself
=> fix(clapi) export specific service, add host before service

doc/en/installation/prerequisites.rst, doc/fr/installation/prerequisites.rst
Add notice to support 64bit operating systems only
=> Add notice for 64bits support only

www/class/centreonLDAP.class.php, www/include/configuration/configObject/contact/DB-Func.php
=> fix(ldap): allow nested groups filter in ldap configuration

doc/en/configuration_guide/poller/02configuration.rst
added a screenshot present in fr doc but lacking in en doc
Ref: #6086, #6132 and #6129
=> Missing screenshot

doc/en/configuration_guide/poller/02configuration.rst
=> correct screenshot path

www/class/centreon-clapi/centreonHost.class.php, www/class/centreonHost.class.php
* Insert information in log action when user use APPLYTPL with API
* Insert information in log action when user use "Deploy Services" in "Configuration > Hosts > Hosts" more action menu
=> Allow to see "conf changed" = YES in Poller menu
ref: #6160
=> fix(conf): Insert info in log_action when user use deploy services

tests/clapi_export/clapi-configuration.txt, www/api/class/centreon_administration_widget.class.php, www/api/class/centreon_clapi.class.php, www/api/class/centreon_configuration_objects.class.php, www/api/class/centreon_home_customview.class.php, www/api/class/centreon_keepalive.class.php, www/api/class/centreon_metric.class.php, www/api/class/centreon_proxy.class.php, www/api/class/centreon_realtime_base.class.php, www/api/class/centreon_results_acceptor.class.php, www/api/class/centreon_wiki.class.php, www/api/class/webService.class.php, www/api/index.php, www/api/internal.php, www/class/centreon-clapi/centreonContact.class.php, www/class/centreonUser.class.php, www/include/configuration/configObject/contact/DB-Func.php, www/include/configuration/configObject/contact/formContact.ihtml, www/include/configuration/configObject/contact/formContact.php, www/include/configuration/configObject/contact/help.php, www/install/createTables.sql, www/install/sql/centreon/Update-DB-2.8.20_to_2.8.21.sql
Separate Rest Api configuration and Rest Api realtime access. 
Add the choise to access on each API on the user configuration page.
=> Rest api rt temporary acl fix

doc/en/api/api_rest/index.rst, doc/fr/api/api_rest/index.rst
REFS: MON-2421
Adding documentation related to the API rest permission split.
=> fix(doc): Add documentation on API Rest permissions

src/CentreonLegacy/Core/Module/License.php, www/include/options/oreon/modules/listModules.ihtml
file_get_contents() method can't get the path of the license file and send NULL.
So the date displayed in Administration->Extensions->Module is 01/01/1970
=> Fix(license) : Filename cannot be empty

www/include/reporting/dashboard/template/viewHostGroupLog.ihtml, www/include/reporting/dashboard/template/viewHostLog.ihtml, www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml
correct the broken input in jQuery
=> fix(jQuery): fix broken input in reporting_dashboard

cron/centAcl.php
To check that nothing changed, it is possible to:
* edit an acl group and change service group, host or host group linked to it.
Verify that users with rights to see those ones keep their rights.
* Remove a user from an acl group and verify he lost his rights.
=> fix(centAcl.php): Dead code removed

www/class/config-generate/generate.class.php
Fix incorrectly pushed variable name
=> git bCp7 m22 quickfix config generate

composer.json, www/lib/HTML/QuickForm/HTML_QuickFormCustom.php, www/lib/HTML/QuickForm/HTML_QuickForm_radio_Custom.php
Load a custom radio buttons quick form class, which uses a custom match to load default values.
=> fix(global): load radio buttons default value

www/include/common/javascript/tool.js
=> fix(js): fix select all action on listing

www/lib/HTML/QuickForm/HTML_QuickFormCustom.php
Change fatal error to notice to comply with previous version error type all over the code.
=> refactor(quickformCustom): Change error type of addRule

www/lib/HTML/QuickForm/HTML_QuickFormCustom.php
Change fatal error to notice to comply with previous version error type all over the code.
=> refactor(quickFormCustom): change error type of applyfilter

lib/Centreon/Cache/Manager/Manager.php, lib/Zend/Cache/Backend.php, lib/Zend/Cache/Core.php, lib/Zend/Cache/Frontend/Class.php, lib/Zend/Cache/Frontend/File.php, lib/Zend/Cache/Frontend/Function.php, lib/Zend/Cache/Frontend/Page.php, www/class/centreon-clapi/centreonAPI.class.php, www/class/centreon-clapi/centreonExported.class.php, www/class/centreon-clapi/centreonHost.class.php, www/class/centreon-clapi/centreonServiceTemplate.class.php
replace using of deprecated each() function with foreach(),
fix several PHP notices related with undefined index
Resolves CP7M-51
=> fix(global): deprecated function, PHP notices

composer.json, www/lib/HTML/QuickForm/customcheckbox.php, www/lib/HTML/QuickForm/tags.php
Add custom tags and checkbox elements to quickform, which are used in modules.
=> fix(quickform): add previously deleted elements

www/include/common/pagination.php, www/include/configuration/configObject/service/DB-Func.php, www/include/configuration/configObject/service/listServiceByHost.php, www/include/options/oreon/modules/upgradeForm.php
fix missing variable in pagination view, upgradeForm and service host list
fix requirement of password when auth with token
Resolves CP7M-54
=> fix(global): clean up several PHP warnings

www/lib/HTML/QuickForm/HTML_QuickFormCustom.php
=> Change quickform custom addrule returns

Jenkinsfile
=> chore(build): trigger AWIE job on successful build

Jenkinsfile
=> chore(build): trigger Export (PPE) job on successful build

Jenkinsfile
=> chore(build): trigger AutoDiscovery job on successful build

www/include/common/common-Func.php, www/main.php
Add additional conditions to the function which resets the pagination. Only when the request does not have a number of the current page we should set the page to 0.
=> Cp7 m58 fix service templates pagination

www/include/configuration/configObject/host/listHost.php
reset pagination page on new filter posted
Resolves: CP7M-59
=> fix(host): update pagination

www/api/class/centreon_wiki.class.php, www/class/centreon-knowledge/wikiApi.class.php
Apply new API rules and add compatibility downwards to 1.27
Resolves: CP7M-63
=> fix(knowledgebase): fix compatibility with MW1.30

www/class/centreonPurgeEngine.class.php, www/include/configuration/configObject/contact/ldapImportContact.php, www/include/home/customViews/rename.php
- remove unused variable 
- remove getting a reference from the function
- Illegal string offset
=> Cp7 m53 ongoing fixes

www/api/class/centreon_configuration_timeperiod.class.php, www/api/class/webService.class.php
=> fix(api): timeperiod API response without HTML encoding

libinstall/CentWeb.sh, libinstall/check_pear.php, libinstall/functions, varinstall/pear.lst, varinstall/php_modules.lst, varinstall/vars
* Add check module
* Add validate fpm-php service
* Add validate php version
=> fix(chore): Change install from sources to work with PHP 7

www/include/common/autoNumLimit.php
Save to the session what is the selected number of results for each $url.
=> feat(pagination): persist selected results limit

www/include/reporting/dashboard/xmlInformations/GetXmlHost.php, www/include/reporting/dashboard/xmlInformations/GetXmlHostGroup.php, www/include/reporting/dashboard/xmlInformations/GetXmlService.php, www/include/reporting/dashboard/xmlInformations/GetXmlServiceGroup.php
=> fix(sec): Fix SQL injection in dashboard

www/class/centreonCommand.class.php, www/include/configuration/configObject/command/formArguments.php, www/include/configuration/configObject/command/javascript/commandJs.php
* Fix SQL injection when export metrics to CSV from graphs
=> fix(sec): Fix SQL injection on graphs

www/class/centreonGraph.class.php
* Fix execution command by rrdtool command line in Virtual Metrics
* Fix execution command by rrdtool command line in graph images
=> fix(sec): Fix execution command by rrdtool command line

www/class/centreonCommand.class.php, www/include/configuration/configObject/command/formArguments.php, www/include/configuration/configObject/command/javascript/commandJs.php
* Fix XSS for describe arguments and macros
=> fix(sec): Fix XSS on command form

www/include/Administration/configChangelog/viewLogs.ihtml, www/include/Administration/configChangelog/viewLogs.php
* Fix SQL Injection in Administration logs in search fields
=> fix(sec): Fix SQL Injection in administration logs

doc/en/release_notes/centreon-2.8/centreon-2.8.24.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.24.rst
Add release note for FR & EN documentation
=> Add Centreon web 2.8.24 release note

tests/clapi_export/clapi-configuration.txt
=> Change the export configuration for the comparison to work

doc/en/release_notes/centreon-2.8/index.rst, doc/fr/release_notes/centreon-2.8/index.rst
Add missing chapter to index.rst for the 2.8.24 release note
=> fix(doc): Add missing chapter to release note

src/CentreonLegacy/Core/Widget/Information.php, www/include/options/oreon/widgets/action.php, www/include/options/oreon/widgets/list.ihtml, www/include/options/oreon/widgets/list.php
Add button to upgrade all widgets and to install all widgets.
=> feat(widgets): add buttons to install and upgrade all

www/class/centreon.class.php, www/include/configuration/configObject/host/listHost.php, www/include/configuration/configObject/hostgroup/listHostGroup.php
Add persistence for search terms in hosts and host groups. Replace double quotes. Replace database methods.
=> feat(searching): persist search term for host and host group

src/CentreonLegacy/Core/Module/Information.php, www/include/options/oreon/modules/installForm.php, www/include/options/oreon/modules/listModules.ihtml, www/include/options/oreon/modules/listModules.php, www/include/options/oreon/modules/modules.php, www/include/options/oreon/modules/modulesAction.tpl, www/include/options/oreon/modules/upgradeForm.php
Add buttons to install and upgrade all modules.
=> feat(modules): add buttons to install and upgrade all

www/include/eventLogs/viewLog.php, www/include/eventLogs/xml/data.php, www/include/eventLogs/xsl/logEngine.xsl
JS bugs
issue related with selector for limit of rows
improve code readability
Resolve CP7M-104
Ref #6367
=> fix(mon): bugs in event/system logs

www/include/views/graphs/generateGraphs/generateImage.php
Get rows count from pdo query statement.
=> fix(monitoring): get rows count from query statement

www/include/options/oreon/modules/installForm.php, www/include/options/oreon/modules/listModules.ihtml, www/include/options/oreon/modules/listModules.php, www/include/options/oreon/modules/upgradeForm.php
Make a single button to install and upgrade all modules.
=> refactor(modules): make a single button to install and upgrade modules

www/include/configuration/configObject/meta_service/metric.php
Fix Quickform create input
Resolves: CP7M-125
=> fix(metaservice): Quickform element loading

www/include/options/accessLists/resourcesACL/formResourcesAccess.php
Add array name keys for default values of include all checkboxes.
=> fix(resources): add default value to form checkboxes

www/include/configuration/configObject/service/listServiceByHost.php
Add new query to get the count of all services without limit clause.
=> fix(pagination): add count of all services results

www/class/centreon-clapi/centreonAPI.class.php
=> fix(widget): add option to skip using of PHP exit function

www/include/configuration/configObject/command/formArguments.php, www/include/configuration/configObject/command/formMacros.php
fix problem with editing and describing check commands
Resolves: CP7M-127
=> fix(config-command): update smarty/quickform loading

www/include/core/header/header.php
=> fix(ux): show a proper bg color of the submenu

www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php, www/include/monitoring/external_cmd/popup/popup.php, www/include/monitoring/status/Common/commonJS.php, www/include/monitoring/status/Notifications/notifications.php
Remove manual loading of smarty. Fix jquery attribute get. Fix pdo prepared statement.
=> fix(monitoring): proper smarty loading and js attribute fix

www/include/common/javascript/jquery/plugins/centreon/jquery.centreonValidate.js, www/include/configuration/configObject/timeperiod/formTimeperiod.php, www/include/configuration/configObject/timeperiod/timeperiod_JS.php
=> feat(conf): add JS validation of Time Range Exceptions

www/include/common/javascript/tool.js
=> fix(ux): the mass selection doesn't work the second time

www/class/centreonWidget.class.php
=>  fix(cv): issue with moving of widgets

README.md
This PR needs to be taken into account with the following one #6253  (might need to handle a conflict on the README file)
=> fix(README): Adding Stéphane Chapron to dev team

doc/fr/faq/administration.rst
correctement utilisé 2 fois à la suite.
=> Erreur ligne 54

www/class/centreon-clapi/centreonHost.class.php
=> fix(clapi): avoid to order parentship several times

www/api/class/centreon_realtime_services.class.php
small patch to probable cut/paste bug
=> fixe (api) #6080

www/include/views/virtualMetrics/listVirtualMetrics.php
JS scripts inserted in the metric / RPM field, are launched in the listing page.
=> fix(sec): Fix SQL injection from metrics RPN's field

www/class/centreon-clapi/centreonACLAction.class.php, www/class/centreon-clapi/centreonACLGroup.class.php, www/class/centreon-clapi/centreonACLMenu.class.php, www/class/centreon-clapi/centreonACLResource.class.php, www/class/centreon-clapi/centreonAPI.class.php, www/class/centreon-clapi/centreonCentbrokerCfg.class.php, www/class/centreon-clapi/centreonCommand.class.php, www/class/centreon-clapi/centreonContact.class.php, www/class/centreon-clapi/centreonContactGroup.class.php, www/class/centreon-clapi/centreonContactTemplate.class.php, www/class/centreon-clapi/centreonDependency.class.php, www/class/centreon-clapi/centreonDowntime.class.php, www/class/centreon-clapi/centreonEngineCfg.class.php, www/class/centreon-clapi/centreonExported.class.php, www/class/centreon-clapi/centreonHost.class.php, www/class/centreon-clapi/centreonHostCategory.class.php, www/class/centreon-clapi/centreonHostGroup.class.php, www/class/centreon-clapi/centreonHostGroupService.class.php, www/class/centreon-clapi/centreonLDAP.class.php, www/class/centreon-clapi/centreonObject.class.php, www/class/centreon-clapi/centreonResourceCfg.class.php, www/class/centreon-clapi/centreonService.class.php, www/class/centreon-clapi/centreonServiceCategory.class.php, www/class/centreon-clapi/centreonServiceGroup.class.php, www/class/centreon-clapi/centreonServiceTemplate.class.php, www/class/centreon-clapi/centreonTimezone.class.php, www/class/centreon-clapi/centreonTrap.class.php
ST export ==> does not export HT, only HT relations 
SVC export ==>does not export host, only host relations
HG ==> does not export linked hosts, only relations
SG ==> does not export linked services, only relations
Refs: #5294
=> refacto(clapi): refacto clapi export

www/class/centreonLDAP.class.php
=> fix(ldap): remove contact password if ldap password storage is disabled

doc/en/api/api_rest/index.rst, doc/fr/api/api_rest/index.rst, www/api/class/centreon_submit_results.class.php, www/api/class/webService.class.php, www/api/exceptions.php
Please find here a very simple API to push results for hosts and services through the rest API.
You can send simple result or multiple results. 
`{
"results": [{ 	
"updatetime": "1523872945",
"host": "server-1",
"service": "service-passif",
"status": "0",
"output": "Output 1",
"perfdata": "perf=1"
},
{ 	
"updatetime": "1523872945",
"host": "server-2",
"service": "service-passif",
"status": "1",
"output": "Output 2",
"perfdata": "perf=2"
},
{ 	
"updatetime": "1523872945",
"host": "server-3",
"service": "service-passif",
"status": "2",
"output": "Output 3",
"perfdata": "perf=1"
}]
}`
=> add api for passif check acceptance

www/include/core/autologout/autologout.php
this is reflected in the menu clock
Resolve CP7M-144
=> fix(ux): make an immediately check_session request

www/include/options/oreon/modules/listModules.ihtml
changing popup message : "Are you sire..." with "Are you sure..."
=> fix(popup): minor spelling correction

www/include/monitoring/common-Func.php
=> fix(Status Details) display true inheritance relation

package.json
* Better package version for remove conflict between @babel/runtime
=> fix(ui): Fix unit test

www/class/centreonAuth.class.php
* Get from topology table the topology_url_opt field to add in default url page the options
Ref: #6528
=> fix(topology): Add topology url option when loading default page

www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
=> fix(monitoring): Sort hosts by name ASC in serviceGridByHGXML

Jenkinsfile
As XUnit reporter is not understanding Behat results anymore.
=> JUnit reporter in Jenkinsfile

cron/centAcl-Func.php, cron/centAcl.php
=> enh(perf): Optimize acl filter calculation

doc/en/api/api_rest/index.rst, doc/en/exploitation_guide/04realtime.rst, doc/en/release_notes/centreon-2.8/centreon-2.8.25.rst, doc/en/upgrade/from_packages.rst, doc/fr/api/api_rest/index.rst, doc/fr/api/clapi/overview.rst, doc/fr/configuration_guide/poller/01installation.rst, doc/fr/exploitation_guide/04realtime.rst, doc/fr/migration/nagiostocentreon.rst, doc/fr/release_notes/centreon-2.7/centreon-2.7.11.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.25.rst, doc/fr/upgrade/from_packages.rst
Numerous corrections to correct errors when generating documentation.
=> Doc correct build errors

www/class/centreonUtils.class.php, www/include/configuration/configResources/DB-Func.php, www/include/configuration/configResources/formResources.php, www/include/configuration/configResources/listResources.php, www/include/configuration/configResources/resources.php
Added controls on some parameters and added filters during the creation of macros. 
Fixed the display of the poller macros when HTML tags were included in the resource name or macro expression.
=> fix(poller macros): Fix XSS security issue on adding poller macros 

www/class/centreonTraps.class.php, www/class/centreonUtils.class.php, www/include/configuration/configObject/traps/formTraps.php, www/include/configuration/configObject/traps/listTraps.php, www/include/configuration/configObject/traps/traps.php
Added controls on some parameters. 
Fixed the display of the SNMP trap list that crash when attempting to duplicate the same trap twice.
=>  fix(SNNP trap) : Fix SQL injection on editing trap SNMP

www/class/centreonUtils.class.php, www/include/views/virtualMetrics/DB-Func.php, www/include/views/virtualMetrics/formVirtualMetrics.php, www/include/views/virtualMetrics/listVirtualMetrics.php, www/include/views/virtualMetrics/virtualMetrics.php
Fixed SQL injection on the virtual metric list page.
Fixed control on the virtual metric name when attempting to add or modify a virtual metric.
=> fix(virtual metric): Fix SQL injection

www/class/centreonUtils.class.php, www/include/monitoring/status/Common/commonJS.php, www/include/monitoring/status/Services/service.php
Added filter on search requests to correct the XSS issue. 
Correction on the output search field that does not persist during refresh.
=>  fix(monitoring service): Fix XSS security issue 

www/class/centreonUtils.class.php, www/include/Administration/configChangelog/viewLogs.php
Fix XSS issues on the administration logs page.
Protection of all database queries against SQL injection.
=> fix(administration log page): Fix XSS issue

www/include/configuration/configNagios/DB-Func.php
=> fix(conf): SQL syntax error in engine conf form

src/CentreonLegacy/Core/Menu/Menu.php, tests/php/CentreonLegacy/Core/Menu/MenuTest.php, www/front_src/src/components/navigation/index.js
=>  fix(menu): Fix the menu order

www/install/steps/process/insertBaseConf.php
When installation process runs add more default data in the database related to remotes.
=> fix(install): add more default data on install process

www/include/options/oreon/modules/modulesAction.tpl, www/include/options/oreon/widgets/list.php
=> fix(admin): after install/upgrade all reload parent page

www/front_src/src/components/hostMenu/index.js
=> fix(ux): wording issue in header menu host's drop-down

package-lock.json, package.json, www/front_src/src/App.js, www/front_src/src/styles/partials/_header.scss, www/front_src/src/styles/partials/form/_form.scss
=> fix(ui): Fullscreen functionality fixes. IE compatibility fix.

www/include/options/oreon/modules/installForm.php, www/include/options/oreon/modules/listModules.php, www/include/options/oreon/modules/reload.ihtml
=> fix(admin): reload parent window when the module is updated or installed

www/include/home/customViews/widgetParam.html
=> fix(widget): Errors when saving preferences of widget

www/include/configuration/configServers/listServers.ihtml
=> poller wizard include acl

www/Themes/Centreon-2/style.css, www/main.get.php
=> fix(ux): the centreon message box hide part of a filter form

www/front_src/src/components/hostMenu/index.js, www/front_src/src/components/pollerMenu/index.js, www/front_src/src/components/serviceStatusMenu/index.js, www/front_src/src/components/userMenu/index.js, www/front_src/src/config/index.js
=> fix(ux): add base path of links in header

src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php, src/CentreonRemote/Domain/Service/ConfigurationWizard/LinkedPollerConfigurationService.php, www/include/configuration/configGenerate/xml/moveFiles.php, www/include/core/pathway/pathway.php, www/install/createTables.sql, www/install/sql/centreon/Update-DB-2.8.26_to_18.10.0.sql
Add additional params when creating export task.
=> Add extra export params

src/CentreonRemote/Application/Clapi/CentreonWorker.php
Update namespace of export commitment.
=> Fix pocess queue namespace

www/main.get.php
=> fix(ux): remove warning icon v2

www/class/centreonACL.class.php
Avoid the first menu level having more privileges than the first child
=> fix(menu): Fix the ACLs of menu

www/include/monitoring/objectDetails/hostDetails.php, www/include/monitoring/objectDetails/serviceDetails.php
=> fix(mon): syntax error in monitoring status pages

www/include/common/javascript/datepicker/localizedDatepicker.js
=> fix(report): the datepicker drop selected date after form submission

www/front_src/src/components/forms/remoteServer/RemoteServerFormStepOne.js
Use arrow function into callback, because value change with redux-form,
see https://github.com/erikras/redux-form/issues/124
Refs: MON-2918
=> fix(remote): Fix the change remote server type on wizard

www/include/Administration/myAccount/formMyAccount.php
Correction of the user profile form to take into account the default page after login.
=> fix(user profile): Fix the default page on login

www/include/configuration/configCentreonBroker/blockConfig.ihtml
Modify 'href' by 'onclick' on link
=> fix(broker): Fix blank page redirection on delete output

www/include/monitoring/status/Notifications/notifications.php
=> fix(ux): exclude services started by BA from BAM UI notification style

www/include/Administration/about/about.php
Macro will be replaced by the source tarball creation script.
=> Print original source commit in the about page

www/include/views/graphs/graph-periods.html, www/include/views/graphs/graph-split.html, www/include/views/graphs/graphs.html
=> fix(service graph): Fix blank page after click on double column icon

www/include/monitoring/acknowlegement/serviceAcknowledge.php
=> fix(style): Add missing style for button in svc ack form

lang/pt_BR/LC_MESSAGES/help.po, lang/pt_BR/LC_MESSAGES/messages.po, www/include/common/javascript/datepicker/datepicker-pt-BR.js, www/include/common/javascript/datepicker/datepicker-pt.js
=> add localization to pt-BR (Portuguese Brazil)

www/install/php/Update-2.8.26_to_18.10.0.php
insert parents of checked topology
=> fix(acl): fix acl topology relations in database 

www/include/Administration/parameters/ldap/form.ihtml
Replace main.php by main.get.php
=> fix(ldap): Fix inception when importing manually users

lang/pt_BR/LC_MESSAGES/messages.po
=> update translation from #6747

lang/es/LC_MESSAGES/help.po, lang/es/LC_MESSAGES/messages.po, www/include/common/javascript/datepicker/datepicker-es.js
Spanish language, needs revision by a native speaker (community?)
=> Add translation to spanish

www/class/centreonService.class.php
This fix in necessary to init the select2 configuration KPI / Services
Refs: BAM-352
=> fix configuration boolean kpi (#BAM-352)

lang/pt_PT/LC_MESSAGES/help.po, lang/pt_PT/LC_MESSAGES/messages.po
Now portuguese from Portugal ! (pt_PT)
=> add translation portuguese variant Portugal (pt_PT)

bin/centreon-translations.php, bootstrap.php, www/api/class/centreon_i18n.class.php
Modifies the creation of translation files.
The translations files will be created during the update or during installation.
=> fix(translation): Fix blank page about 'failed to open dir' error

cron/centreon-backup.pl
MON-2917
- Fix PHP CLI executable path
- Fix php.ini path
=> fix(path) : fix PHP paths in backup script

doc/en/administration_guide/poller/wizard_add_poller.rst, doc/en/migration/index.rst, doc/en/migration/pollerdisplaytoremoteserver.rst, doc/en/migration/upgradetoCentreon18.10.rst, doc/en/upgrade/from_packages.rst, doc/en/upgrade/index.rst, doc/fr/administration_guide/poller/wizard_add_poller.rst, doc/fr/migration/index.rst, doc/fr/migration/pollerdisplaytoremoteserver.rst, doc/fr/migration/upgradetoCentreon18.10.rst, doc/fr/upgrade/from_packages.rst, doc/fr/upgrade/index.rst
* Add FR documentation to migrate Poller Display to Remote Server
* Add En documentation to migrate Poller Display to Remote Server
=> enh(doc): Add chapter to migrate Poller Display to Remote Server

www/include/monitoring/comments/template/comments.ihtml
If user can't add a comments he can't cancel too.
=> fix(comments): Display cancel button using ACL rights

www/include/monitoring/downtime/template/listDowntime.ihtml
If user can't add a downtimes he can't cancel too.
=> fix(downtimes): Display cancel button using ACL rights

www/include/reporting/dashboard/ajaxReporting_js.php
=> fix(dashboard): Fix color for timeline

src/Centreon/Domain/Repository/HostTemplateRelationRepository.php, src/CentreonRemote/Domain/Exporter/HostExporter.php
=> fix(remote): export BA hosts

www/include/configuration/configObject/host/host.php, www/include/configuration/configObject/hostgroup/hostGroup.php
Force reload of acl before listing of data on page
=> fix(configuration): duplication of host and hostgroup

www/Themes/Centreon-2/style.css, www/include/common/javascript/resize_td.js
Issue was that jQuery fired before content was loaded, so we check if it's loaded and then fire it one more time to let JS do it's magic
=> fix(js): wait content load before fire jquery event

src/CentreonRemote/Domain/Service/ConfigurationWizard/RemoteConnectionConfigurationService.php, src/CentreonRemote/Domain/Service/ConfigurationWizard/ServerConnectionConfigurationService.php
=> fix(remote): BAM output configuration will be not add to remote server

www/include/monitoring/external_cmd/popup/massive_downtime.php
=> fix(DT): default date is in 2024

doc/en/configuration_guide/advanced_configuration/recurrent_downtimes.rst
The path to create a recurrent downtime has changed to Configuration > Host > Downtime to Monitoring > Downtimes
=> fix(doc) Path to Recurrent Downtime EN

doc/fr/configuration_guide/advanced_configuration/recurrent_downtimes.rst
The path to create a recurrent downtime has changed to Configuration > Host > Downtime to Monitoring > Downtime
=> fix(doc) Path to Recurrent Downtime FR

src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
change exception variable name in output of fail clapi import process
=> fix(remote-server): fix incorrect variable name

doc/en/administration_guide/poller/install_poller.rst, doc/en/administration_guide/poller/wizard_add_poller.rst, doc/en/migration/pollerdisplaytoremoteserver.rst, doc/fr/administration_guide/poller/install_poller.rst, doc/fr/administration_guide/poller/install_remote_server.rst, doc/fr/administration_guide/poller/ssh_key.rst, doc/fr/administration_guide/poller/wizard_add_poller.rst, doc/fr/migration/pollerdisplaytoremoteserver.rst
Correct many typo in FR & EN documentation
=> fix(doc): correct typo

doc/en/installation/from_iso.rst, doc/fr/installation/from_iso.rst
=> fix(doc): update installation documentation to full EL7

doc/fr/upgrade/from_packages.rst
In Poller it's not necessary to restart cbd
=> Remove restart cbd

www/class/config-generate/broker.class.php
=> fix(broker): fix export of cbd watchdog logs path

www/front_src/src/App.js, www/front_src/src/route-components/module/index.js
=> fix(ui): manage fullscreen even with iframe navigation

www/include/monitoring/status/Common/commonJS.php, www/include/monitoring/status/Services/service.php, www/include/monitoring/status/Services/serviceJS.php
Fix columns on service list page (about 'hard state duration' column).
Fix the play button to use the selected status when we click on it.
Fix the refresh feature to avoid to restart play if the pause is actived.
=> fix(monitoring service): Fix columns on the list page

www/include/configuration/configServers/DB-Func.php, www/include/configuration/configServers/formServers.php, www/include/configuration/configServers/listServers.ihtml, www/include/configuration/configServers/listServers.php, www/include/configuration/configServers/servers.php
Add the PID column in the poller list page.
Fix the behavior of the duplicate feature.
Add security controls.
=> enh(poller): Add the PID column in the poller list page

www/include/configuration/configObject/host/DB-Func.php, www/include/configuration/configObject/host/formHost.php, www/include/configuration/configObject/host/host.php, www/include/configuration/configObject/host/listHost.ihtml, www/include/configuration/configObject/host/listHost.php
Added filter to avoid SQL injection.
Fixed the 'duplicate' action on the suffix calculation.
=> Fix SQL injection and duplicate action

src/Centreon/Domain/Repository/TimePeriodRepository.php, www/api/class/centreon_configuration_timeperiod.class.php, www/include/configuration/configObject/timeperiod/DB-Func.php, www/include/configuration/configObject/timeperiod/formTimeperiod.php
=> fix(conf): prevent timeperiod to call itself via templates

doc/en/administration_guide/poller/enable_remote.rst, doc/fr/administration_guide/poller/enable_remote.rst, src/Centreon/Domain/Repository/InformationsRepository.php, src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php, src/CentreonRemote/Application/Webservice/CentreonTaskService.php
* Allow to define multiple IP address of authorized master using coma as separator
Based on pull request: #6959
=> Remote server add multiple authorized master

behat.yml, features/PollerResourceConfiguration.feature, features/bootstrap/PollerResourceConfigurationContext.php, www/include/configuration/configResources/DB-Func.php, www/include/configuration/configResources/formResources.php, www/include/configuration/configResources/listResources.php, www/include/configuration/configResources/resources.php
Fix the XSS vulnerability for the poller resource list page.
=> enh(poller): Fix the XSS vulnerability on poller resource

features/AclAccessGroups.feature, features/bootstrap/AclAccessGroupsContext.php, www/include/options/accessLists/groupsACL/groupsConfig.php, www/include/options/accessLists/groupsACL/listGroupConfig.php
Fix XSS vulnerability in the 'ACL group' search field.
Fix XSS vulnerability in the access group list page.
Add two acceptance tests to test these cases.
=> fix(acl_access_group): Fix XSS vulnerabilities

lang/fr/LC_MESSAGES/messages.po
resolve : https://github.com/centreon/centreon/issues/7074
=> fix(UI): french translation misspelling

www/class/centreonTraps.class.php, www/class/centreonUtils.class.php, www/include/configuration/configObject/traps/formTraps.php, www/include/configuration/configObject/traps/listTraps.ihtml, www/include/configuration/configObject/traps/listTraps.php, www/include/configuration/configObject/traps/traps.php
SQL queries updated to prevent SQL injection.
The duplication feature has been fixed.
=> fix(trap_snmp): Fix SQL injection and duplicate feature

www/class/centreonFileManager.php, www/class/centreonImageManager.php, www/include/options/media/images/DB-Func.php, www/include/options/media/images/formDirectory.php, www/include/options/media/images/formImg.php, www/include/options/media/images/images.php, www/include/options/media/images/listImg.php, www/include/options/media/images/syncDir.php
Fix move and update features also.
=> fix(media): Fix XSS vulnerability.

www/include/configuration/configObject/host/listHost.ihtml, www/include/configuration/configObject/host/resolveHostName.php, www/include/monitoring/objectDetails/template/hostDetails.ihtml, www/include/monitoring/objectDetails/template/serviceDetails.ihtml
=> fix(conf): protect hostname resolver from XSS

src/CentreonRemote/Domain/Resources/RemoteConfig/CfgNagiosBrokerModule.php
- Change character from _ to -
=> fix(remote server): fix poller space replacement

www/include/monitoring/status/Common/commonJS.php
=> enh(UI): tooltip popins relative position

www/include/home/customViews/index.ihtml, www/include/home/customViews/layouts/column_1.ihtml, www/include/home/customViews/layouts/column_2.ihtml, www/include/home/customViews/layouts/column_3.ihtml, www/include/home/customViews/views.php
=> fix(ui): backport memory leak

www/include/options/oreon/modules/licenseUpload.php
- check for session
- change new file permissions to 444 (read only)
- file extension is always .license
=> fix(security): fix unauthorized file upload

www/include/monitoring/objectDetails/hostDetails.php, www/include/monitoring/objectDetails/serviceDetails.php, www/include/monitoring/objectDetails/template/hostDetails.ihtml, www/include/monitoring/objectDetails/template/serviceDetails.ihtml
Localize dates in the host and service detail pages
=> fix(UI): correct comments date in host and svc detail pages

www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php, www/include/reporting/dashboard/csvExport/csv_HostLogs.php, www/include/reporting/dashboard/csvExport/csv_ServiceGroupLogs.php, www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php
Add downtimes information in CSV export of dashboard for:
- Host
- HostGroup
- Service
- ServiceGroup
ref: #5968
=> fix(reporting): add downtimes information in CSV export of dashboard

www/include/views/componentTemplates/formComponentTemplate.php, www/include/views/graphTemplates/listGraphTemplates.php, www/include/views/virtualMetrics/formVirtualMetrics.php
Minor fixes on three pages.
Removing errors in the console and in the log.
Pages :
* add metric
* add curve
* template
=> Mon 3291 minor fixes on page load

www/include/configuration/configKnowledge/functions.php
=> fix(kb): correct documentation link

Jenkinsfile
These changes will allow us to handle _testing_ builds as pipelines.
=> Rework Jenkinsfile to handle release builds

doc/en/administration_guide/poller/add_manually_a_poller.rst, doc/en/administration_guide/poller/advanced_configuration_broker.rst, doc/en/administration_guide/poller/enable_remote.rst, doc/en/administration_guide/poller/index.rst, doc/en/administration_guide/poller/install_poller.rst, doc/en/administration_guide/poller/install_poller_iso.rst, doc/en/administration_guide/poller/install_poller_packages.rst, doc/en/administration_guide/poller/install_remote_server.rst, doc/en/administration_guide/poller/pollersstats.rst, doc/en/administration_guide/poller/ssh_key.rst, doc/en/administration_guide/poller/wizard_add_poller.rst, doc/en/administration_guide/poller/wizard_add_remote.rst, doc/en/installation/common/install_iso.rst, doc/en/installation/common/install_packages.rst, doc/en/installation/common/post_install.rst, doc/en/installation/common/web_install.rst, doc/en/installation/from_VM.rst, doc/en/installation/prerequisites.rst, doc/en/life_cycle.rst, doc/en/migration/index.rst, doc/en/migration/pollerdisplaytoremoteserver.rst, doc/en/migration/upgradetoCentreon18.10.rst, doc/en/upgrade/from_packages.rst, doc/en/upgrade/from_sources.rst, doc/en/upgrade/index.rst
Improved the English Centreon documentation, thanks to @jefestyler
Replace previous PR #7051 (issue with rebase on master)
=> enh(doc): improved English documentation, thanks to jefestyler

doc/en/installation/common/post_install.rst, doc/fr/installation/common/post_install.rst, doc/fr/quick_start/index.rst
Add at the end of installation a link to configure the proxy to allow the Centreon server to access to Internet.
=> Doc improve install chapters

www/include/configuration/configObject/command/minPlayCommand.php
Original author : @gquere
Authenticated RCE
An RCE was exploitable in minPlayCommand.php
QA Team (Quality Assurance) with tests.
reviewers to understand what are the stakes of the pull request.
Check :
#7099
Fixes # (issue) : none
Type of change
Patch fixing an issue (non-breaking change)
Target serie
2.8.x
How this pull request can be tested ?
Ask me in private please.
Checklist
Community contributors & Centreon team
I followed the coding style guidelines provided by Centreon.
I have rebased my development branch on the base branch (master, maintenance).
I have updated the release note in dedicated temporary section. *
Centreon team only
I have made sure that the unit tests related to the story are successful.
I have made sure that unit tests covers 80% of the code written for the story. …
=> Mon 3310 authenticated rce minplay command

www/class/centreonDowntime.class.php, www/include/monitoring/recurrentDowntime/listDowntime.php
Resolve MON-3518 on 2.8.x
As I couldn't push a coding style commit, on jben94's branch. 
I opened a new branch to add the required commit.
From jben94 PR -> 
Link issue : #6501
Link to the first PR : #6504 closed / rebased on the master
Link to the second PR PR : #6506
=> MON-3518-filter-correction-recurrent-downtime-form

doc/en/release_notes/centreon-2.8/centreon-2.8.27.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.27.rst
Simple update of the 2.8.27 release note before starting validation phase.
Fixes # (issue) **None**
Just display it on GitHub
=> fix(release notes): complete 2.8.27 release note

doc/en/release_notes/centreon-2.8/centreon-2.8.26.rst, doc/en/release_notes/centreon-2.8/centreon-2.8.27.rst, doc/en/release_notes/centreon-2.8/index.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.26.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.27.rst, doc/fr/release_notes/centreon-2.8/index.rst
Adding missing release notes from the 2.8.x branche
Fixes # (issue) None
Display it on GitHub
=> Add missing release notes (2.8.26 & 2.8.27)

doc/en/administration_guide/partitioning/user/configuration.rst, doc/fr/administration_guide/partitioning/user/configuration.rst
Replace #7077 because include EN documentation
=> enh(doc): describe directory of XML files for partitioning

www/Themes/Centreon-2/style.css, www/class/centreonDowntime.class.php, www/include/monitoring/recurrentDowntime/listDowntime.php
Correct the number of rows to display when a filter is applied
=> enh(DT): fix search filter for recurrent downtimes

doc/en/release_notes/centreon-18.10/centreon-18.10.4.rst, doc/fr/release_notes/centreon-18.10/centreon-18.10.4.rst
Release note in order to start validation of the 18.10.4
Fixes # (issue) **None**
Display it on GitHub and during the upgrade process.
=> doc(release note): complete 18.10.4 release note

doc/en/exploitation_guide/04realtime.rst, lang/es_ES.UTF-8/LC_MESSAGES/messages.po, lang/fr_FR.UTF-8/LC_MESSAGES/messages.po, lang/pt_BR.UTF-8/LC_MESSAGES/messages.po, lang/pt_PT.UTF-8/LC_MESSAGES/messages.po, www/include/monitoring/downtime/listDowntime.php
Two very small changes to the downtime-related messages.
=> Fix wording related to downtimes

www/front_src/src/styles/partials/_side-nav.scss, www/front_src/src/styles/partials/_variables.scss
You should see a grey border on the right side of the left menu.
You should see a grey border on the right side of the left menu.
**\*** updating the release note results in adding the **pull request id** and **description** at the end of the file. **Product …
=> enh(ui) better menu delimitation

www/api/class/centreon_topcounter.class.php
* refacto webservice to check access properly
=>  refacto(webservice): refacto top counter webservice

www/class/centreon-clapi/centreonHost.class.php
=> fix(clapi) fix init parameters

doc/en/faq/index.rst, doc/en/faq/remote_server.rst, doc/fr/faq/index.rst, doc/fr/faq/remote_server.rst
Add a FAQ about known issues of Remote Server usage
Replace #6970
**\*** updating the release note results in adding the **pull request id** and **description** at the end of the file. **Product Managers** will rework it for the release. Release notes can be found …
=> enh(doc): Add FAQ for known issues about Remote Server

src/Centreon/Application/DataRepresenter/Entity.php
Update generic Entity Data Representor
=> Bam 393 new cc config tab

phpunit.xml, src/Centreon/Infrastructure/CentreonLegacyDB/StatementCollector.php, src/Centreon/Infrastructure/Service/CentreonPaginationService.php, src/Centreon/Tests/Resource/Mock/CentreonPaginationServiceMock.php, src/CentreonNotification/Application/DataRepresenter/EscalationEntity.php, src/CentreonNotification/Application/Webservice/CentreonEscalationWebservice.php, src/CentreonNotification/Domain/Entity/Escalation.php, src/CentreonNotification/Domain/Repository/EscalationRepository.php, src/CentreonNotification/ServiceProvider.php, src/CentreonNotification/Tests/Application/DataRepresenter/EscalationEntityTest.php, src/CentreonNotification/Tests/Application/Webservice/CentreonEscalationWebserviceTest.php, src/CentreonNotification/Tests/Domain/Repository/EscalationRepositoryTest.php, src/CentreonNotification/Tests/Resource/Fixture/response-list-1.json, src/CentreonNotification/Tests/Resource/Fixture/response-list-2.json, src/CentreonNotification/Tests/ServiceProviderTest.php
=> feat(API): escalation API resource and unit tests for it

doc/en/installation/common/install_packages.rst, doc/en/installation/common/post_install.rst, doc/fr/installation/common/install_packages.rst, doc/fr/installation/common/post_install.rst
Add in documentation how to enable systemctl for centreon systemd process
Fixes #7273 #7246
=> fix(doc): add enable systemctl for centreon

src/Centreon/Application/DataRepresenter/Entity.php, src/Centreon/Infrastructure/Service/CentreonPaginationService.php, src/CentreonCommand/Application/DataRepresenter/CommandEntity.php, src/CentreonCommand/Application/Webservice/CentreonCommandWebservice.php, src/CentreonCommand/Domain/Entity/Command.php, src/CentreonCommand/Domain/Repository/CommandRepository.php, src/CentreonCommand/ServiceProvider.php, src/CentreonCommand/Tests/Application/DataRepresenter/CommandEntityTest.php, src/CentreonCommand/Tests/Application/Webservice/CentreonEscalationWebserviceTest.php, src/CentreonCommand/Tests/Domain/Repository/CommandRepositoryTest.php, src/CentreonCommand/Tests/Resource/Fixture/response-list-1.json, src/CentreonCommand/Tests/Resource/Fixture/response-list-2.json, src/CentreonCommand/Tests/ServiceProviderTest.php, src/CentreonNotification/Application/Webservice/CentreonEscalationWebservice.php, src/CentreonNotification/Domain/Repository/EscalationRepository.php, src/CentreonNotification/Tests/Domain/Repository/EscalationRepositoryTest.php
Resolve BAM-397, BAM-433, and BAM-398
=> feat(API): add API endpoint for commands cover with unit tests

www/class/centreonLDAP.class.php
Fixes # (broken CI)
Launch locally Ldap.feature, before and after applied this patch
=> fix(CI): LDAP acceptance test on the CI

doc/en/administration_guide/poller/enable_services.rst, doc/fr/administration_guide/poller/enable_services.rst
Complete previous PR
Fixes #7284
=> fix(doc): add missing part of PR #7284

www/front_src/src/styles/partials/_side-nav.scss
<h5> Community contributors & Centreon team …
=> enh(UI) Color the open level 2 and 3 menus

features/bootstrap/KnowledgeBaseContext.php, features/bootstrap/WidgetContext.php
Fix some acceptance tests.
Not relevant, as it should fix existing tests.
=> Some acceptance tests fixes

www/include/Administration/brokerPerformance/brokerPerformance.php
Disallow inclusion of files from incorrect folders in broker performance.
Resolves: MON-3312
Fix security problem for file inclusion outside of correct folder.
Fixes # 3312
refer to: #7101
=> fix(security): fix vulnerability for file loading

src/Centreon/Domain/Repository/InformationsRepository.php, src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php, src/CentreonRemote/Application/Validator/WizardConfigurationRequestValidator.php, src/CentreonRemote/Application/Webservice/CentreonRemoteServer.php, src/CentreonRemote/Domain/Service/NotifyMasterService.php, www/front_src/src/helpers/validators.js
Allows the user to define remote server by address not only by IP
Fixes # MON-3257
- [x ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ x] 18.10.x
=> feat(remote-server): allow usage of domain names

features/ContactTemplateConfiguration.feature, features/TopCounterPollers.feature, features/bootstrap/ServiceTemplateConfigurationContext.php
Increasing existing spin's time and adding a spin to the delete service template acceptance test
=> fix(ci): adding or increasing spin in service template acceptance tests

.github/PULL_REQUEST_TEMPLATE.md
Either provide checkboxes to select correct answers or ask to remove superfluous lines, but not both. I'd rather stick with the checkboxes so I removed the deletion requests.
Not applicable.
- [ ] ~I have made sure that **acceptance tests** related to the story are successful (**local and CI**)~
=> fix: remove deletion requests from Pull Request template file.

www/include/monitoring/status/ServicesHostGroups/serviceGridByHG.php, www/include/monitoring/status/ServicesHostGroups/serviceSummaryByHG.php, www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php, www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php, www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
<h1> Fix SQL injection</h1>
Fix SQL injections in services by hostgroup page
Fix SQL injections in services by servicegroup page
Fixes # (issue): None
Please contact me in private
=> fix(secu): sql injections in the service by hostgroups and servicegroups pages

Jenkinsfile
Tests are now video-recorded. In case of failure a _.flv_ file is provided in the log directory. This PR allows video files to be archived by Jenkins.
Please refer to centreon/centreon-test-lib#124.
If there are failed tests, check in Jenkins that video files are available.
=> Archive flv artifacts after acceptance tests.

www/include/monitoring/status/Services/serviceJS.php
ref : https://github.com/centreon/centreon/commit/7d94d87162512526644fd0681fe1c4e80c67ac3d#diff-1adbd0d1d188a77b97f72149d1d4f674
=> fix(monitoring): remove double encoding of host name

www/include/configuration/configObject/meta_service/listMetaService.php, www/include/configuration/configObject/service/listService.ihtml, www/include/configuration/configObject/service/listServiceByHost.php, www/include/configuration/configObject/service/listServiceByHostGroup.php, www/include/configuration/configObject/service_categories/listServiceCategories.php, www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php, www/include/configuration/configObject/servicegroup/listServiceGroup.php
saving user's filters from configuration > services > menu
=> Mon 3562 services configuration and pagination

www/include/configuration/configObject/contact/listContact.php, www/include/configuration/configObject/contact_template_model/listContactTemplateModel.php, www/include/configuration/configObject/contactgroup/listContactGroup.php, www/include/configuration/configObject/timeperiod/listTimeperiod.php
Saving filters in configuration contact pages
- [X ] Patch fixing an issue (non-breaking change)
=> Mon 3563 contact configuration and pagination

www/include/common/pagination.php, www/include/configuration/configObject/command/command.php, www/include/configuration/configObject/command/listCommand.ihtml, www/include/configuration/configObject/command/listCommand.php, www/include/configuration/configObject/connector/listConnector.php
Saving filters in the pages of the configuration > command menu
- [X ] Patch fixing an issue (non-breaking change)
=> Mon 3564 commands configuration and pagination

www/include/configuration/configCentreonBroker/listCentreonBroker.php, www/include/configuration/configNagios/listNagios.php, www/include/configuration/configObject/escalation/listEscalation.php, www/include/configuration/configObject/host_dependency/listHostDependency.php, www/include/configuration/configObject/hostgroup_dependency/listHostGroupDependency.php, www/include/configuration/configObject/metaservice_dependency/listMetaServiceDependency.php, www/include/configuration/configObject/servicegroup/listServiceGroup.php, www/include/configuration/configObject/servicegroup_dependency/listServiceGroupDependency.php, www/include/configuration/configObject/traps-groups/listGroups.php, www/include/configuration/configObject/traps-manufacturer/listMnftr.php, www/include/configuration/configObject/traps/listTraps.php, www/include/configuration/configResources/listResources.php, www/include/configuration/configServers/listServers.php
Saving filters in the other pages of the configuration > command menu
Except for Knowledge base
- [X ] Patch fixing an issue (non-breaking change)
=> Mon 3565 other configuration and pagination

www/api/class/webService.class.php
Use the existing web service or initialize it.
Need to use web service with cron script.
=> fix(api) Use the web service or initialize it

tmpl/install/redhat/centcore.systemd, tmpl/install/redhat/centreontrapd.systemd
Use options defined into /etc/sysconfig directory for centcore and centreontrapd (log file, severity log option, ...)
Without this fix:
```
● centcore.service - Centreon Core
Loaded: loaded (/usr/lib/systemd/system/centcore.service; disabled; vendor preset: disabled)
Active: active (running) since mer. 2019-04-03 10:33:21 BST; 1s ago
Main PID: 5277 (centcore)
CGroup: /system.slice/centcore.service
└─5277 /usr/bin/perl /usr/share/centreon/bin/centcore
avril 03 10:33:21 centreon-central-1810 systemd[1]: Started Centreon Core
```
with the fix:
```
● centcore.service - Centreon Core
Loaded: loaded (/usr/lib/systemd/system/centcore.service; disabled; vendor preset: …
```
=> enh(systemd): use /etc/sysconfig/cent* files to get options

www/class/centreon-clapi/centreonAPI.class.php
=> add variables setter on centreonAPI

www/include/core/header/header.php, www/include/monitoring/status/Services/service.php, www/include/monitoring/status/Services/templates/service.ihtml
<h1> Filter status fix </h1>
<h2> Fix monitoring filters </h2>
Fixes 3570
=> Mon 3570 filter status

www/include/configuration/configObject/host/listHost.ihtml, www/include/configuration/configObject/service/listServiceByHost.php
<h1> Fix filtering services by host </h1>
Fixes 3568
=> Mon 3568 filter hosts v2

src/CentreonLegacy/Core/Module/Upgrader.php
Currently modules maintenance releases of a previous serie have to be handled manually and inserted within the upgrade path of newer series. The upgrade system now process all upgrade scripts that are newer than the current version.
Try to update modules from their Centreon Web 2.8 compatible versions. Upgrade should work normally.
- [ ] ~I have made sure that **acceptance tests** related to the story are successful (**local and CI**)~
=> Handle new modules maintenance releases in their upgrade.

.gitignore, composer.lock
adding "secret" file to .gitignore
adding a tempalte to .gitignore
=> enh(git): adding secret file to gitignore and a template

Jenkinsfile
Parallelize acceptance tests on as much nodes as possible. Run time should go down from 2.5 hours to less than 40 minutes.
Just run acceptance tests.
=> Parallelize acceptance tests

cron/centreon-send-stats.php, doc/en/ceip.rst, doc/fr/ceip.rst, www/class/centreonStatistics.class.php, www/class/centreonStatsModules.class.php, www/class/centreonVersion.class.php
Add more CEIP statistics:
* Add usage of widgets in custom views
* Send OS name and version
* Check if a module can provides additional statistics
Check data sent
=> enh(ceip): Add additional statistics including modules if present

www/Themes/Centreon-2/style.css, www/front_src/src/components/navigation/index.js, www/front_src/src/styles/partials/_side-nav.scss, www/front_src/src/styles/partials/_variables.scss
- [ ] I have **rebased** my development branch on the base branch (master, …
=> Poc4 version2

features/bootstrap/WidgetContext.php, www/class/centreonContactgroup.class.php, www/include/Administration/brokerPerformance/brokerPerformance.php, www/include/configuration/configObject/host_categories/listHostCategories.php, www/main.get.php
Coding style and PSR2 corrections for the CI
=> fix(CI): codingStyle and PSR2

www/include/configuration/configObject/host/formHost.php
This patch allows you to enlarge the width of the input field of a host's geographical coordinates.
=> fix(host/form): change size (6 => 30) of input geo coordinates on host form

www/install/sql/centreon/Update-DB-2.8.27.sql
Add missing upgrade script for the **2.8.27**
Upgrade from 2.8.26 < **version** < 19.04
=> upgrade(core): add missing 2.8.27 upgrade script

www/class/centreonLDAP.class.php, www/include/monitoring/status/Hosts/xml/hostXML.php, www/include/options/accessLists/resourcesACL/formResourcesAccess.php
- Fix searching for users
- Add @ before ldap_sort() as it is deprecated
<h1> Fix LDAP </h1>
<h2> Fix ldap searching users </h2>
Fixes #3519
<h2> LDAP fix </h2>
=> fix(LDAP): fix users search

www/include/configuration/configObject/service/DB-Func.php
<h1> Fix NULL insert : convert string to NULL </h1>
Correct an SQL error.
In an host configuration : 
* create an new host
* select a template (your template must contain a service with Notification -> "Inherit only contacts/contacts group from host" is "No")
* select yes for "Create Services linked to the Template too"
When you save the host, you have an SQL error. With this patch, the SQL error is corrected.
=> fix(sql) NULL insert : convert string to NULL

tests/clapi_export/clapi-configuration.txt, www/Themes/Centreon-2/style.css, www/class/centreon-config/centreonMainCfg.class.php, www/class/config-generate/engine.class.php, www/include/configuration/configNagios/DB-Func.php, www/include/configuration/configNagios/formNagios.ihtml, www/include/configuration/configNagios/formNagios.php, www/install/createTables.sql, www/install/sql/centreon/Update-DB-19.04.0.sql
* Better display of Broker Options on Centreon Engine configuration
* Add filter for sent macros from Centreon Engine to Centreon Broker
Refs: MON-3629
=> feat(engine): Add configuration for filter sent macros

www/include/views/graphs/graphs.php
Use require_once on the graph page
Display the graph page in **Monitoring -> Performance**
=> fix(graph): use require_once for the graph page

src/CentreonModule/Infrastructure/Source/ModuleSource.php
add optional parameter require_license for modules to show error in extension page
Fixes # MON-3612
=> add required license option to module source

www/api/class/centreon_configuration_command.class.php, www/include/configuration/configCentreonBroker/listCentreonBroker.php, www/include/configuration/configNagios/listNagios.php, www/include/configuration/configObject/command/listCommand.php, www/include/configuration/configObject/contact/listContact.php, www/include/configuration/configObject/contact_template_model/listContactTemplateModel.php, www/include/configuration/configObject/contactgroup/listContactGroup.php, www/include/configuration/configObject/escalation/listEscalation.php, www/include/configuration/configObject/host/listHost.php, www/include/configuration/configObject/host_categories/listHostCategories.php, www/include/configuration/configObject/host_dependency/listHostDependency.php, www/include/configuration/configObject/host_template_model/listHostTemplateModel.php, www/include/configuration/configObject/hostgroup_dependency/listHostGroupDependency.php, www/include/configuration/configObject/meta_service/listMetaService.php, www/include/configuration/configObject/metaservice_dependency/listMetaServiceDependency.php, www/include/configuration/configObject/service/listServiceByHost.php, www/include/configuration/configObject/service/listServiceByHostGroup.php, www/include/configuration/configObject/service_categories/listServiceCategories.php, www/include/configuration/configObject/service_dependency/listServiceDependency.php, www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php, www/include/configuration/configObject/servicegroup/listServiceGroup.php, www/include/configuration/configObject/servicegroup_dependency/listServiceGroupDependency.php, www/include/configuration/configObject/timeperiod/listTimeperiod.php, www/include/configuration/configObject/traps-groups/listGroups.php, www/include/configuration/configObject/traps-manufacturer/listMnftr.php, www/include/configuration/configObject/traps/listTraps.php, www/include/configuration/configResources/listResources.php, www/include/configuration/configServers/listServers.php
- Fix the reinitialized user's filter
- Restore previous changes overwritten by a commit
=> Mon 3723 fix filters configuration users

www/api/class/centreon_configuration_command.class.php
quickfix for notification command listing
Fixes # 3726
=> update get row count in command listing

www/include/configuration/configNagios/help.php
* Adding the help for the enable filtering
* Adding the help for the Macro whitelist field
Display the help off each mentionned issues.
- [] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
=> fix(help): add missing help for new engine configuration options

www/front_src/src/route-components/administration/extensions/manager/index.js, www/front_src/src/styles/partials/_content.scss
=> enh(ui): rename filters in extensions page

www/api/class/centreon_configuration_command.class.php, www/include/configuration/configNagios/help.php
- Replace service command select2's method 
- Coding style
=> minor fixes for the CI

www/front_src/src/redux/reducers/globalsReducer.js, www/front_src/src/redux/reducers/index.js
- [ ] I have **rebased** my development branch on the base branch (master, …
=> fix for progress, back to sagas

www/front_src/src/components/navigation/navigation.scss
<h2> Add scrollbar when the submenu is too long</h2>
- [ ] I have **rebased** my development branch on the …
=> fix(navigation-submenu): Add scrollbar when the menu is to long.

www/front_src/src/components/navigation/navigation.scss
- [x ] I followed the **coding style guidelines** provided by Centreon
<h5> Centreon …
=> fix(MENU) deletion of arrows in hover and mini mode

www/front_src/src/components/serviceStatusMenu/index.js, www/include/monitoring/status/Services/service.php
Update the sub-menu links in top counter to match the indicators with the status details page
=> fix(top_counter): Update the sub-menu links in top counter

www/front_src/src/components/navigation/navigation.scss
<h2> Submenu title overflow fix. Uppercase first letter of the submenu items. </h2>
- [ ] I have …
=> Mon 3749 submenu section title is not correctly displayed

www/front_src/src/route-components/administration/extensions/manager/index.js
- [x ] I followed the **coding style guidelines** provided by Centreon
- [x ] I have …
=> fix(UI)  MON-3716 Colors of widgets titles

package-lock.json, package.json, src/CentreonLegacy/Core/Module/License.php, src/CentreonModule/Infrastructure/Entity/Module.php, src/CentreonModule/Infrastructure/Source/ModuleSource.php, src/CentreonModule/Tests/Application/DataRepresenter/ModuleDetailEntityTest.php, src/CentreonModule/Tests/Application/DataRepresenter/ModuleEntityTest.php, src/CentreonModule/Tests/Application/DataRepresenter/UpdateActionTest.php, src/CentreonModule/Tests/Resource/Traits/SourceDependencyTrait.php, tests/php/CentreonLegacy/Core/Module/LicenseTest.php
API now returns an array of information about the license instead of only the expiration date
=>  enh(license): update format of license check returned by API

www/front_src/src/components/navigation/navigation.scss, www/front_src/src/styles/partials/_content.scss
<h2> Submenu height fix on different resolutions</h2>
- [ ] I have **rebased** my development branch on the …
=> fix(submenu): Submenu height fix on different resolutions.

www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
fix for the service by servicesgroup page
=> fix(DB): removing bindValue on orderby param

www/front_src/src/components/navigation/navigation.scss
<h2> Submenu fixes </h2>
- [ ] I have **rebased** my development branch on the base branch (master, …
=> fix(submenu): Submenu fixes.

www/front_src/src/components/navigation/navigation.scss
- [ ] I have **rebased** my development branch on the base branch (master, …
=> Mon 3767 new menu odd behaviour fix

www/include/common/common-Func.php
get the origin service information, not only his children
Fixes #7121
=> Mon 3630 service template macro

doc/en/api/api_rest/index.rst, doc/fr/api/api_rest/index.rst
18.10.x version of this PR: https://github.com/centreon/centreon/pull/7509
=> fix(doc): correct api doc

doc/en/api/api_rest/index.rst, doc/fr/api/api_rest/index.rst
Fix Rest API doc mistake from centreon_auth_token to centreon-auth-token en and fr doc
- [ ] I have made sure that **acceptance tests** …
=> Fix Rest API doc mistake

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md
- Add the fact that Github is **not** meant for support
- Add component list to the ISSUE_TEMPLATE
Fixes # None
Display the CONTRIBUTING and ISSUE_TEMPLATE
=> enh(ISSUE_TEMPLATE.md): enhance GitHub information for issues

www/include/views/graphs/graph-periods.html, www/include/views/graphs/graph-split.html, www/include/views/graphs/graphs.html, www/include/views/graphs/javascript/centreon-graph.js
=> fix(graph): manage timezone to display graphs

www/include/common/common-Func.php
Fixes #7121 
next of #7515 
#7121
=> keep initial information order

www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php, www/include/reporting/dashboard/csvExport/csv_HostLogs.php, www/include/reporting/dashboard/csvExport/csv_ServiceGroupLogs.php, www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php
Fix ACL calculation when interfering with the GET request
Fixes # (support)
- [x ] 2.8.x
- [] 18.10.x
- [] 19.04.x (master)
For more details, please ask me in private
=> Mon 3801 csv export acl on 2 8 x

www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php, www/include/reporting/dashboard/csvExport/csv_HostLogs.php, www/include/reporting/dashboard/csvExport/csv_ServiceGroupLogs.php, www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php
Fix ACL calculation when interfering with the GET request
Fixes # (support)
For more details, please ask me in private
=> Mon 3801 csv export acl

www/include/monitoring/status/Common/commonJS.php, www/include/monitoring/status/Hosts/host.php, www/include/monitoring/status/Hosts/hostJS.php, www/include/monitoring/status/Services/serviceJS.php, www/include/monitoring/status/ServicesHostGroups/serviceGridByHG.php, www/include/monitoring/status/monitoringHost.php, www/include/monitoring/status/monitoringService.php
Fix a double webservice call when we use the Host Status filter and the Status filter on the page  Monitoring  >  Status Details  >  Hosts 
Fixes #MON-3574
#7483 and #7506 to fix the service page
- [ ] I have made sure that …
=> fix(monitoring) fix host filter

www/include/eventLogs/export/data.php, www/include/eventLogs/viewLog.php, www/include/eventLogs/xml/data.php
Correct the date in the exported csv files :
1 - Convert the timestamps to formatted dates/times for each occurences.
2 - Homogenize the formatted start and end date.
3 - improve string sent from request security
4 - setting a default start date if the user didn't chose a period, nor a start date (to avoid to display/export logs since 1/1/1970 -> timestamp = 0 )
Fixes # (support)
1 - Go to Monitoring -> event logs, choose a resource -> export the csv -> then check the csv output
2 - Go to …
=> Mon 3834 display datetime in csv export

.github/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, doc/README.md
- [x ] Updating documentation (missing information, typo...)
Display informations on GitHub
- [x ] I have **rebased** my development branch on the base branch (master, maintenance).
- [ ] I have made …
=> GitHub enhancements

www/include/Administration/parameters/engine/form.php
Correct the redirection after submitting the form's of the Administration > Parameters > Monitoring page.
Check that the redirection (when after savig the form, you click on the "modify" button), 
open the page :
- centreon/main.php?p=50111&o=engine
instead of : 
- centreon/main.php?p=50111&o=nagios
=> Mon 3859 correct administration parameters monitoring modify form redirect

doc/fr/quick_start/add_host.rst, doc/fr/quick_start/add_host_from_template.rst, doc/fr/quick_start/add_services.rst, doc/fr/quick_start/add_svc_from_template.rst, doc/fr/quick_start/add_user.rst, doc/fr/quick_start/basic_plugins.rst, doc/fr/quick_start/login.rst
=> fix(doc): minor typo corrections

www/include/configuration/configObject/service/formService.php, www/include/configuration/configObject/service/listServiceByHost.php, www/include/configuration/configObject/service/listServiceByHostGroup.php, www/include/configuration/configObject/service/serviceByHost.php, www/include/configuration/configObject/service/serviceByHostGroup.php
Some variables have been reverted to previous naming, when others have been kept in camelCase
Resulting in errors when calling the variable from dynamic sql request.
As a non admin user, allowed to reach the status > monitoring pages;
Check that the pages are correctly displayed, and no errors are shown in the logs
=> fix(BE): correct camelcase naming

doc/en/release_notes/centreon-18.10/centreon-18.10.5.rst, doc/en/release_notes/centreon-18.10/index.rst, doc/en/release_notes/centreon-19.04/centreon-19.04.1.rst, doc/en/release_notes/centreon-19.04/index.rst, doc/en/release_notes/centreon-2.8/centreon-2.8.28.rst, doc/en/release_notes/centreon-2.8/index.rst, doc/fr/release_notes/centreon-18.10/centreon-18.10.5.rst, doc/fr/release_notes/centreon-18.10/index.rst, doc/fr/release_notes/centreon-19.04/centreon-19.04.1.rst, doc/fr/release_notes/centreon-19.04/index.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.28.rst, doc/fr/release_notes/centreon-2.8/index.rst
Release note added for 2.8.28, 18.10.5 and 19.04.1
**Fixes** None
- [] 19.04.x
Display the release_note
=> Releases notes master

doc/en/release_notes/centreon-2.8/centreon-2.8.28.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.28.rst
Release note added for 2.8.28
**Fixes** None
Display the release_note
=> doc(release): Adding 2.8.28 release note

doc/en/release_notes/centreon-18.10/centreon-18.10.5.rst, doc/en/release_notes/centreon-2.8/centreon-2.8.28.rst, doc/en/release_notes/centreon-2.8/index.rst, doc/fr/release_notes/centreon-18.10/centreon-18.10.5.rst, doc/fr/release_notes/centreon-2.8/centreon-2.8.28.rst, doc/fr/release_notes/centreon-2.8/index.rst
Release note added for 2.8.28, 18.10.5
**Fixes** None
Display the release_note
=> Releases notes 18.10.x

www/include/configuration/configObject/contact/DB-Func.php, www/include/configuration/configObject/contactgroup/DB-Func.php, www/include/configuration/configObject/escalation/DB-Func.php, www/include/configuration/configObject/host/DB-Func.php, www/include/configuration/configObject/host_categories/DB-Func.php, www/include/configuration/configObject/host_dependency/DB-Func.php, www/include/configuration/configObject/hostgroup_dependency/DB-Func.php, www/include/configuration/configObject/meta_service/DB-Func.php, www/include/configuration/configObject/metaservice_dependency/DB-Func.php, www/include/configuration/configObject/service/DB-Func.php, www/include/configuration/configObject/service_dependency/DB-Func.php, www/include/configuration/configObject/servicegroup_dependency/DB-Func.php, www/include/options/accessLists/actionsACL/DB-Func.php
Fix most of the master branch acceptance tests.
N/A
=> Fix 19.10 acceptance tests

src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php, src/CentreonRemote/Domain/Service/TaskService.php, www/class/centreonRestHttp.class.php, www/include/configuration/configServers/help.php
Correct CI Sonar's warnings on Jenkins
Launch a job on jenkins and pass the unit test step
=> fix(CI): correct coding style and psr2

composer.json
packagist.org doesn't publish branches with an invalid license identifier
=> fix(base): change license identifier with a valid SPDX license identifier

www/front_src/src/index.js
=> fix(front): expose properly react router dom

www/front_src/src/App.js, www/front_src/src/components/reactRouter/index.js
=> fix(front): load hooks on app load

www/install/sql/centreon/Update-DB-2.8.27_to_2.8.28.sql, www/install/sql/centreon/Update-DB-2.8.28_to_18.10.0.sql
Add missing SQL upgrade script to allow upgrade from 2.8.28 to 18.10.x
=> fix(upgrade): add missing upgrade script for 2.8.28

www/include/common/javascript/datepicker/localizedDatepicker.js, www/include/monitoring/downtime/AddDowntime.php, www/include/monitoring/downtime/listDowntime.php, www/include/monitoring/downtime/template/AddDowntime.ihtml, www/include/monitoring/external_cmd/popup/massive_downtime.php, www/include/monitoring/external_cmd/popup/templates/massive_downtime.ihtml
fix(datepicker): change end date when start date is greater than end date and the opposite
=> fix(datepicker): change dates

www/install/sql/centreon/Update-DB-19.04.1.sql
=> Mon 3901 upgrade issue

www/front_src/src/styles/partials/form/_form.scss
=> MON-3858 #comment adding scroll to remote server wizard

www/class/centreonACL.class.php
Define an ACL resource like
all hosts
all hostgroups
exclude some hosts
Given a user with ACL limiting resource access
When I go to Reporting > Dashboard > By hostgroups
I can see only my hosts
=> fix(acl) exclude hosts excluded from hg

www/include/configuration/configObject/host/listHost.php, www/include/configuration/configObject/service/listServiceByHost.php, www/include/configuration/configObject/service/listServiceByHostGroup.php
In the web interface : Configuration > Services > Services by host/ host group.
When selecting "Disabled" in the status dropdown and clicking 'Search' the filter does not applies and the dropdown is reset.
=> Mon 3807 service disabled filter

README.md
Adding new developer to the README: **Jiliang Wang**
Jiliang Wang joins the Centreon Map developers team.
**Fixes** None
Display the README file.
=> enh(README): add new developers to Centreon developers team

www/include/Administration/about/about.php
Adding Jiliang Wang and Sylvestre Gallon
Removing Rabaa Ridene and Guillaume Baldo
Update developers list
**Fixes** None
- [] Patch fixing an issue (non-breaking change)
Display the **about page.**
=> enh(about): update Centreon developers list

www/include/monitoring/objectDetails/template/hostDetails.ihtml
**Fixes** #7549 
Steps to reproduce
create a service with a "+" in its description
Generate and export configuration
Go to monitoring > services
go to service detailed of previously created one
=> fix(url) use variables with urlencode

www/include/eventLogs/viewLog.php
* fix groups arrows
* add default hour filter
* fix host filter for csv export 
**Fixes** #7417
Given a user accessing and filtering by host(s)
When he export data
The export should contain only filtered data
=> Mon 3864 event log export

composer.lock, www/class/centreonTraps.class.php, www/install/createTablesCentstorage.sql, www/install/sql/centstorage/Update-CSTG-19.10.0.sql
fix acceptance traps with sql strict mode
=> fix(sql) fix strict mode

www/include/configuration/configObject/command/DB-Func.php
fix acceptance ppm Update of commands of a plugin pack
=> fix(sql) fix insert command with sql strict mode

bin/centreon_health, cron/centreon-send-stats.php, header.txt
Integrate header on files where licence headers are missing.
Check that script are able to execute. It's a comment, no risk to break anyting.
=> Add missing headers

package-lock.json
- [x ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x ] I have made corresponding changes to the **documentation**.
- [ x] I have **rebased** my development branch on the base branch (master, maintenance).
- [x ] I have …
=> MON-3782-package-lock-json

lib/perl/centreon/script/centcore.pm
If you select many pollers attached to a Remote Server some commands are overwritten (export conf, restart/reload engine, etc).
=> fix(centcore): do not overwrite commands

www/install/createTables.sql, www/install/sql/centreon/Update-DB-19.10.0.sql
Add possibility to store FQDN in database
**Fixes** #7615
Use FQDN instead of IP address
=> fix(remote-server): store FQDN

www/class/centreonCustomView.class.php
=> fix(sql) use pearDb

tests/clapi_export/clapi-configuration.txt
=> fix(TA): Clapi.feature mock updates

lang/es_ES.UTF-8/LC_MESSAGES/help.po, lang/fr_FR.UTF-8/LC_MESSAGES/help.po, lang/pt_BR.UTF-8/LC_MESSAGES/help.po, lang/pt_PT.UTF-8/LC_MESSAGES/help.po, www/include/Administration/parameters/engine/help.php
Improve help tooltip for mail binary in administration page.
Go to "Administration > Parameters > Monitoring” and check help for “Directory + Mailer Binary” field
=> enh(ui): improve mail bin help tooltip

lib/perl/centreon/script/centreontrapd.pm
Can @HOSTID@ in special commands (could be useful for centreon-dsm).
Use @HOSTID@ in special trap command definition. The variable should be subsitute by the host_id.
=> add centreontrapd @HOSTID@ macro

composer.json, src/Centreon/Infrastructure/Event/FileLoader.php, src/Centreon/ServiceProvider.php, www/include/configuration/configObject/contact/contact.php, www/include/configuration/configObject/contact_template_model/contact_template.php, www/include/configuration/configObject/contact_template_model/formContactTemplateModel.ihtml, www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
integrate event dispatcher in contact template pages it's almost the same as in contact pages. From the visual part of UI, there are no changes
=> Bam 517 contact tpl ba section

www/include/configuration/configObject/contact_template_model/contact_template.php, www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
to fix the code style
**Fixes** BAM-517
=> Improve code style warnings

doc/coding-style/js/README.md
Change the 4 spaces to 2 spaces indentation in the coding style desc
=> enh(JS): 2 space indentation in README.md

www/Themes/Centreon-2/style.css
hen you acceeses to the graph of services (top counter, services, click on graph icon) => all the graphs icon sould have the cursor pointer.
=> MON-3381 #comment adding cursor pointer to icons

composer.lock, doc/en/api/clapi/objects/hosts.rst, doc/fr/api/clapi/objects/hosts.rst, tests/clapi_export/clapi-configuration.txt, tests/rest_api/rest_api.postman_collection.json, tests/rest_api/rest_api.postman_environment.json, www/class/centreon-clapi/centreonContact.class.php, www/class/centreon-clapi/centreonEngineCfg.class.php, www/class/centreon-clapi/centreonLDAP.class.php, www/class/centreonTraps.class.php, www/include/configuration/configNagios/DB-Func.php, www/include/configuration/configObject/command/DB-Func.php, www/include/core/header/header.php, www/install/createTables.sql, www/install/createTablesCentstorage.sql, www/install/sql/centreon/Update-DB-19.10.0.sql, www/install/sql/centstorage/Update-CSTG-19.10.0.sql
=> Mon 3581 compatibility strict mode

composer.json, src/Centreon/Infrastructure/Event/FileLoader.php, src/Centreon/ServiceProvider.php, www/include/configuration/configObject/contact/contact.php, www/include/configuration/configObject/contact_template_model/contact_template.php, www/include/configuration/configObject/contact_template_model/formContactTemplateModel.ihtml, www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
integrate event dispatcher in contact template pages it's almost the same as in contact pages. From the visual part of UI, there are no changes
it is a cherry-picked from the PR #7555 
=> Bam 517 contact tpl ba section (#7555)

lang/pt_BR.UTF-8/LC_MESSAGES/help.po
=> fix(translation): fix syntax in portuguese translation

www/include/configuration/configGenerate/xml/generateFiles.php
From @mhaskar 's PR https://github.com/centreon/centreon/pull/7663 -> rebased and conflict resolved.
PR already reviewed !
To be cherry-picked on the 18.10.x and 19.04.x branches after QA validation. For 2.8.x, an other PR is needed.
https://shells.systems/centreon-v19-04-remote-code-execution-cve-2019-13024
**Fixes** # (CVE)
=>  add escapeshellarg to  nagios_bin binary passed to shell_exec

www/Themes/Centreon-2/style.css
- [ x] Patch fixing an issue (non-breaking change)
- [x ] 18.10.x
- [ x] I followed the **coding style guidelines** provided by Centreon
- [x ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. …
=> MON-3381 cursor pointer rebased 18.10.x

www/include/configuration/configGenerate/xml/generateFiles.php
=> fix(generate) fix requirement

doc/en/administration_guide/data_retention.rst, doc/fr/administration_guide/data_retention.rst, lang/es_ES.UTF-8/LC_MESSAGES/messages.po, lang/fr_FR.UTF-8/LC_MESSAGES/messages.po, lang/pt_BR.UTF-8/LC_MESSAGES/messages.po, lang/pt_PT.UTF-8/LC_MESSAGES/messages.po, www/class/centreonPurgeEngine.class.php, www/include/Administration/configChangelog/viewLogs.php, www/include/Administration/parameters/DB-Func.php, www/include/Administration/parameters/centstorage/form.ihtml, www/include/Administration/parameters/centstorage/form.php, www/install/createTablesCentstorage.sql, www/install/sql/centstorage/Update-CSTG-19.10.0.sql
<h1> Adds audit log purge log </h1>
<h2> allows people to configure data retention for audit logs </h2>
This adds a new field in the form in administration -> parameters -> options at the bottom of the page. Field that allows people to configure the retention duration for their audit log. It also displays logs from CLAPI actions
-head over the administration -> parameters -> options and set a value for your audit log retention duration.
-create a backup of your database so you'll be able to repeat the next step as much as you want
-mysqldump -u centreon -p centreon_storage log_action log_action_modification > /tmp/backup_audit_log_tables.sql
In my exemple, I have the following logs …
=> enh(purge): add audit log purge

doc/en/installation/from_sources.rst, doc/fr/installation/from_sources.rst
=> enh(doc): update installation doc using sources

doc/fr/api/clapi/objects/hosts.rst
Added the command geo_coords in the setparams possibilities of hosts in CLAPI for FR documentation
=> Update Host.rst FR

doc/en/administration_guide/poller/ssh_key.rst, doc/en/installation/from_VM.rst, doc/fr/administration_guide/poller/ssh_key.rst, doc/fr/installation/from_VM.rst
Correct a mistake in the documentation
**Fixes** #7620
=> fix(doc): correct SSH exchange notice #7620

www/include/configuration/configObject/contact/formContact.php
=> Fix creating user with admin rights

www/include/configuration/configObject/contact/contact.php, www/include/configuration/configObject/contact/displayNotification.php, www/include/configuration/configObject/contact/formContact.php
=> fix(security): fix contact permissions if user is not administrator

src/Centreon/Application/DataRepresenter/AclGroupEntity.php, src/Centreon/Application/Webservice/AclGroupWebservice.php, src/Centreon/Domain/Entity/AclGroup.php, src/Centreon/Domain/Repository/AclGroupRepository.php, src/Centreon/Domain/Repository/Traits/CheckListOfIdsTrait.php, src/Centreon/Infrastructure/CentreonLegacyDB/EntityPersister.php, src/Centreon/Infrastructure/CentreonLegacyDB/Mapping/ClassMetadata.php, src/Centreon/Infrastructure/CentreonLegacyDB/Mapping/MetadataInterface.php, src/Centreon/Infrastructure/CentreonLegacyDB/ServiceEntityRepository.php, src/Centreon/Infrastructure/Service/CentreonWebserviceService.php, src/Centreon/ServiceProvider.php
the main point is the API for a list of ACL groups, and accompanying changes are related with way of describing a meta-information in Entity objects and loading of data in Entity objects
**Fixes** # BAM-606
with `GET` request to `/centreon/api/internal.php?object=centreon_acl_group&action=list` have to return list of ACL groups if user has a valid session
=> Bam 573 bv api form

www/class/config-generate/meta_service.class.php
=> fix(generate) fix meta service generation with special char

composer.lock, www/class/centreonGraph.class.php, www/include/monitoring/recurrentDowntime/listDowntime.php
=> fix(acceptance) fix graph query 

doc/en/index.rst, doc/en/migration/index.rst, doc/en/migration/upgradetoCentreon19.10.rst, doc/en/release_notes/centreon-19.10/index.rst, doc/en/release_notes/index.rst, doc/en/upgrade/from_packages_1810.rst, doc/en/upgrade/from_packages_1904.rst, doc/en/upgrade/from_packages_34.rst, doc/en/upgrade/index.rst, doc/fr/index.rst, doc/fr/migration/index.rst, doc/fr/migration/upgradetoCentreon19.10.rst, doc/fr/release_notes/centreon-19.10/index.rst, doc/fr/release_notes/index.rst, doc/fr/upgrade/from_packages_1810.rst, doc/fr/upgrade/from_packages_1904.rst, doc/fr/upgrade/from_packages_34.rst, doc/fr/upgrade/index.rst
Update the 19.10 upgrade documentation.
Try to upgrade to 19.10 using the documentation. All steps should be performed smoothly.
=> 19.10 update upgrade documentation

www/api/class/centreon_performance_service.class.php
Create meta services
Create user with ACL and don't select meta services
In "Monitoring  >  Performances  >  Graphs" menu for "Graphs select you can see meta services
**Fixes** #6534 
1. Create a meta services
2. Create a user and ACL to see only one
3. Connect with the new user and go to "Monitoring > Performance"
4. Search for "meta"
5. You must see only meta service selected in ACL
=> fix(internal api): add ACL to select meta-services for services

www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php, www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php, www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php, www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
=> fix(pagination) fix pagination display in service monitoring
