centreon/centreon

- www/class/centreonGraph.class.php
Replace hash by hash isn't useful
I replace simple quote by space because graph wasn't displayed with this character
> Replace simple quote by space in legend

- doc/fr/faq/performance.rst
usermod : l'indicateur -a n'est autorisé qu'avec l'indicateur -G
Change -g to -G
> Fix usermod options

- lib/perl/centreon/script.pm
This fixes centstorage_purge on a DB not using the standard port
> Use db_port in centreon scripts

- www/include/common/webServices/rest/centreon_performance_service.class.php
Hello,
The line below is written in /var/log/centreon/sql-error.log:
2016-04-28 13:46|0|0|DB Error: syntax error QUERY : SELECT SQL_CALC_FOUND_ROWS DISTINCT i.service_description, i.service_id, i.host_name, i.host_id, m.index_id FROM index_data i, metrics m , centreon_acl aclWHERE i.id = m.index_id  AND acl.host_id = i.host_id AND acl.service_id = i.service_id AND acl.group_id IN ('99','197','48') AND (i.service_description LIKE '%pmisanas1app%' OR i.host_name LIKE '%pmisanas1app%') ORDER BY i.host_name, i.service_description LIMIT 0,60
The reason of this issue: a blank is missing => "centreon_acl aclWHERE".
Thanks.
> Wrong SQL query

- www/include/monitoring/status/TopCounter/xml/statusCounter.php
Hello,
When a poller is not running, the name of the poller is displayed twice in the poller status tooltip.
Thanks.
> Avoid displaying poller twice in poller status

- www/class/centreon-clapi/centreonAPI.class.php
Hello,
I think it's more efficient to use reload configuration on poller in "all-in-one" centreon clapi command APPLYCFG.
Regards.
> Use reload instead of restart function in APPLYCFG

- www/class/centreon-clapi/centreon.Config.Poller.class.php
Hello,
When you use command POLLERRESTART and you specify the name of the poller, no error is displayed.
However the command RESTART:<poller_name> is sent to centcore.
The error message in centcore.log is "Cannot restart Engine for poller".
Change code to be compliant with POLLERRELOAD command.
Regards.
> Issue when using poller name with POLLERRESTART

- www/class/centreon-clapi/centreonHost.class.php
Running centreon -e fail with the following error : 
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Array host_register LIKE '0'' at line 4' in /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /usr/share/centreon/lib/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/centreon/lib/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /usr/share/centreon/lib/Zend/Db/Adapter/Pdo/Abstract.php(245): …
> Remove extra parameter that make centreon extract goes on error.

- www/include/monitoring/status/Services/service.php
This URL option allows to clean previous stored filters to access to correct data using others filters (hg, sg, host_search, etc.).
> Add new url option to clear filters

- www/include/home/customViews/index.ihtml
Hi,
If "create view" is selected in "Add view", we see the whole "Edit view" part : 
If "load view" is selected in "Add view", some fields are hidden :
> Bug : Edit menu view

- www/include/monitoring/downtime/AddDowntime.php
If user is non-admin user, the path to access to alt_error.ph is wrong and the page is empty.
> Bad path to access to alt_error.ph

- www/include/monitoring/objectDetails/common-func.php
Fix #4976
Fix the blank page in monitoring status when a command argument has a single quote.
> Escaping problem in executed command

- www/Themes/Centreon-2/style.css
- www/include/monitoring/objectDetails/template/serviceDetails.ihtml
* Use word wrap for long output in service detail
* Add a scroll when a command argument is very long in service detail page
Ref: #4974 #4975
> Better display in service detail with long output or long command

- www/class/centreonHost.class.php
Function $this->serviceObj->insert already insert extended information for service so remove call to $this->serviceObj->insertExtendInfo
> #5010 - Do not insert twice service extended info

- doc/en/exploitation_guide/04realtime.rst
- doc/fr/exploitation_guide/04realtime.rst
In the real-time page, details of a host, the host shortcut icons and the Tools menu no longer exist in 2.7x and 2.8x versions.
> Delete Paragraph Shortcut and Tool in Real-Time View

- www/class/centreon-clapi/centreonObject.class.php
This way, I go from 7 hours to 1 hour import time for a 100K lines file.
> fix excessively long id search in logs

- cron/centreon-backup.pl
The password for mysqldump should be escaped; other with an error will occur and database backup fails.
> Failure with special character in password for mysqldump

- cron/centKnowledgeSynchronizer.php
- www/class/centreon-knowledge/wiki.class.php
Bacause empty values are present in centreon database, the following check is always OK:
if (!count($options))
> ref #5269 - check if wiki is configured and extend error message

- www/include/configuration/configObject/traps/traps.php
$dupNbr is an array and not a string
> ref #5272 - Can't duplicate trap definition

- www/class/centreon-clapi/centreonCentbrokerCfg.class.php
Remove for CLAPI epxort empty Centreon Broker configuration parameters. for example:
@@ -1363,20 +1363,11 @@
CENTBROKERCFG;SETPARAM;Central Broker;daemon;1
CENTBROKERCFG;ADDINPUT;Central Broker;CentralMaster;ipv4
CENTBROKERCFG;SETINPUT;Central Broker;1;port;5669
-CENTBROKERCFG;SETINPUT;Central Broker;1;host;
-CENTBROKERCFG;SETINPUT;Central Broker;1;failover;
-CENTBROKERCFG;SETINPUT;Central Broker;1;retry_interval;
-CENTBROKERCFG;SETINPUT;Central Broker;1;buffering_timeout;
CENTBROKERCFG;SETINPUT;Central Broker;1;protocol;bbdo
CENTBROKERCFG;SETINPUT;Central Broker;1;tls;no
-CENTBROKERCFG;SETINPUT;Central Broker;1;private_key;
-CENTBROKERCFG;SETINPUT;Central Broker;1;public_cert;
-CENTBROKERCFG;SETINPUT;Central Broker;1;ca_certificate;
CENTBROKERCFG;SETINPUT;Central Broker;1;negociation;yes …
> Do not export empty Centreon Broker parameters with API

- tmpl/install/sudoersCentreonEngine
Centreon engine is able to read his own files. So the rule is useless.
> remove sudo rule for centengine -v call

- www/include/configuration/configObject/traps/formTraps.php
Meta services are active only and it is not necessary to link a SNMP trap
> Do not list meta service to link to a SNMP trap - issue #5418

- features/bootstrap/AclAccessGroupsContext.php
The multiple contacts were manually added to the contact group
by manipulating select2 elements instead of relying on the Page.
Refs: #5570
> fix(test): use ContactGroupsPage in AclAccessGroups tests.

- www/class/centreonGraphService.class.php
- www/include/monitoring/objectDetails/serviceDetails.php
- www/include/views/graphs/graphs.html
The problem is when we click on  the link of a service graph from monitoring page.
My patch also fixed:
* metrics with backslash and ':' in the name
> Fix graph display with special characters #5554

- doc/en/api/clapi/overview.rst
- doc/fr/api/clapi/overview.rst
fix(doc): Clarify documentation of Centreon clapi authentication
Added in the documentation the possibility to use the encrypted password (in base) or the password in clear
refs: #5625
> Clarify documentation of centreon clapi authentication

- www/include/monitoring/status/TopCounter/xml/statusCounter.php
fix(monitoring) : Metaservices not counted properly in statuses filter
Merge SQL requests for statuses of services to:
- combine ACL in one SQL request
- combine selection of total services per status and total of ACK and DT services per status
This allow to correct issue with calculation of Meta-services
refs: #5458
> Correct svc top counter with meta and merge SQL requests

- doc/en/installation/from_packages.rst
- doc/fr/installation/from_packages.rst
fix(doc): Improve Centreon documentation
For UK and FR installation chapter using package, I moved post-installation subchapter before finish Centreon web installation to do not have errors during process.
I added notice label to advice user that they have to restart server after disable SElinux.
I have corrected some spelling errors
refs: #5611
> 5611 improve centreon documentation

- www/include/home/customViews/widgetParam.php
When saving preferences, customViewId is not set in the redirect URL.
> fix(C.V.): Fix missing parameter in redirect action

- www/include/configuration/configObject/host/formHost.ihtml
fix(conf): Multiple 'update mode' fields in massive changes
Remove duplicate 'update mode' fields
refs: #5266
> fix(conf): Multiple 'update mode' fields in massive changes

- features/bootstrap/MassiveChangeHostsContext.php
The massive change option was removed from the contact groups field of the
host configuration page. Tests should not use it.
> fix(test): do not use massive change option that was removed from the interface

- features/bootstrap/InfluxdbContext.php
It seems like test is sometimes failing because of this missing condition.
The service status containing performance data seems to be processed
before the InfluxDB endpoint is connected, so no perfdata gets stored.
> fix(test): wait for Centreon Broker to be connected in InfluxDB test.

- www/install/sql/centstorage/Update-CSTG-2.8.13_to_2.8.14.sql
Comments are referenced through their entry_time, host_id, service_id,
instance_id and internal_id. While this was properly made in the
fresh install script, users migrating from earlier versions never had
a chance to get the UNIQUE constraint set right.
> fix(install): update /comments/ table UNIQUE constraint.

- features/bootstrap/DowntimeStartAndStopContext.php
Increase downtime length to prevent early downtime termination (might need to be 3 minutes long if 2 minutes is not enough).
> Master fix downtime start stop tests

- www/install/installBroker.sql
- www/install/sql/centstorage/Update-CSTG-2.8.13_to_2.8.14.sql
If we set two downtimes at the same date, the same host and the same
service. Broker considers them as the same.
> fix(installBroker) Db conf changed to improve downtimes settings

- www/class/centreon-clapi/centreonAPI.class.php
Add "\" before CentreonUserLog and CentreonAuthLDAP to load this Centreon classes in CentreonClapi namespace
refs: #/5710
> fix(api): Add backslash to load Centreon class in CentreonClapi namespace

- www/install/createTables.sql
- www/install/php/Update-2.8.14_to_2.8.15.php
Except for people upgrading from a pre-2.7 version of Centreon Web,
the traps_group table did not have a primary key on an auto-increment
field. This prevented the manipulation of trap groups in the interface.
> Correctly set traps_group primary key

- Jenkinsfile
PPM 2.2 should be superseeded by PPM 2.3 soon.
> chore(build): run PPM 2.3 build at the end of Jenkinsfile

- www/include/monitoring/status/TopCounter/xml/statusCounter.php
fix(monitoring) : Metaservices not counted properly in statuses filter
Merge SQL requests for statuses of services to:
combine ACL in one SQL request
combine selection of total services per status and total of ACK and DT services per status
This allow to correct issue with calculation of Meta-services
refs: #5458,  #5616
> Apply PR #5616 on master for top counter

- features/Clapi.feature
This should fix the following error.
```
[centos7] Feature: Clapi
[centos7]   As a Centreon admin
[centos7]   I want to configure my centreon by command line
[centos7]   To industrialize it
[centos7] 
[centos7]   Background:               # features/Clapi.feature:6
[centos7]     Given a Centreon server # ClapiContext::aCentreonServer()
[centos7] 
[centos7]   @critical
[centos7]   Scenario: import/export                                   # features/Clapi.feature:10
[centos7]     Given a Clapi configuration file                        # ClapiContext::aClapiConfigurationFile()
[centos7]     And it was imported                                     # ClapiContext::itWasImported()
[centos7]       Cannot execute command on container web: Line 85 : Object already exists (Simple User) (command was …
```
> fix(test): use a freshly installed server when testing Clapi import/export

- www/include/monitoring/status/Hosts/xml/hostXML.php
Correct call to replaceMacroInString function using name of object to translate custom macro
ref: #5846
> fix(monitoring): Custom MACRO not interpreted in URL in host real time

- www/Themes/Centreon-2/style.css
Css properties added to fix an issue with Internet Explorer 11, in Montoring->Perfomance, the second graph added was many times wider than the first one.
ref: MON-2052 #5081 #5683
> fix(MON)Graphs streched in IE

- www/class/centreon-clapi/centreonCentbrokerCfg.class.php
When $res->fetch() brings nothing, $listName is undefined and generates this warning :
PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/centreon/www/class/centreon-clapi/centreonCentbrokerCfg.class.php on line 411
So I suggest to initialize it as an empty array before.
> Fix (CLAPI) : uninitialized array causing php warning

- Jenkinsfile
> chore(build): trigger AWIE job on successful build

- Jenkinsfile
> chore(build): trigger Export (PPE) job on successful build

- Jenkinsfile
> chore(build): trigger AutoDiscovery job on successful build

- www/include/monitoring/external_cmd/popup/popup.php
- www/include/monitoring/status/Services/serviceJS.php
Fix loading of smarty and remove double encoding of the host name. monitoring/status/Common/commonJS.php @ putInSelectedElem(id)
> fix(monitoring): remove double encoding of host name

- bin/centreon
- bootstrap.php
- config/centreon.config.php
- www/api/class/centreon_administration_module.class.php
- www/api/class/centreon_administration_widget.class.php
- www/api/class/centreon_clapi.class.php
- www/api/class/webService.class.php
- www/api/index.php
- www/api/interface/di.interface.php
- www/api/internal.php
- www/api/trait/diAndUtilis.trait.php
- www/class/centreon-clapi/centreonDependency.class.php
- www/class/centreon-clapi/centreonHostGroup.class.php
- www/include/configuration/configObject/traps/listTraps.php
disable all PHP errors in CLAPI (bin/centreon)
add interface and trait insteed checking for method
add missing arguments in Factory constructor
remove loading of centreon.conf.php when bootstrap.php is in use
add moduleId in centreon_administration_module when use methods for upgrading and removing a module
fix undefined variable in centreonDependency.class.php
fix undefined offset in centreonHostGroup.class.php
use sendResult instead sendJson in class CentreonWebService
add default status if missing in traps list
Resolves CP7M-64
> fix(api): API and CLAPI testing

- www/class/centreonMonitoring.class.php
Minor change, sorts services in the "Services Grid" view by service name after status.  Currently they are sorted by status only, which means that two hosts with the same services sometimes get displayed in different orders.
> Sort by service name after status in service grid

- www/class/centreonDowntime.Broker.class.php
- www/class/centreonDowntime.class.php
Try to prevent error in ​downtimeManager.log by create an dedicated file for Centcore each time the cron needs to send external commands:
`PHP Warning:  file_put_contents(/var/lib/centreon/centcore.cmd): failed to open stream: Permission denied in /usr/share/centreon/www/class/centreonDowntime.Broker.class.php on line 505`
> Prevent permission denied centcore cmd for downtimemanager

- www/include/monitoring/status/Notifications/notifications.php
Hello,
In httpd error_log, the message below is written multiple times:
[Thu May 03 13:23:42 2018] [error] [client 10.90.17.242] PHP Notice:  Undefined index: centreon in /usr/share/centreon/www/include/monitoring/status/Notifications/notifications.php on line 50, referer: https://centreon.xit.rxcorp.com/centreon/main.php
This pull request is to test if the session $_SESSION['centreon'] is defined (as done in other files /usr/share/centreon/www/include/monitoring/status/TopCounter/xml/statusCounter.php).
Regards,
> Avoid PHP notice Undefined index: centreon in notifications.php

- www/api/class/centreon_clapi.class.php
At the moment, trying to use the REST API to retrieve a value containing a semicolon causes the serialization to break.  This is broken on the default install by the host-notify-by-jabber command, which contains the HTML entities `&#039;`.
The problem is caused by the semicolon being used to split the values.  This causes there to be more values than headers, and `array_combine` then returns `false` for that item.
To get around this, this PR checks for there being more values than headers, and if so, recombines all of the last items into one value.  This catches the case where the last item contains a semicolon (e.g. the "line" parameter of command).  This will not work if semicolon is present in any field other than the last.
This isn't an ideal solution - it would be better to either …
> Prevent semicolon in last value breaking rest clapi serialization

- www/class/centreon-clapi/centreonACLGroup.class.php
When importing ACL groups, CLAPI is expecting contact alias to be provided with setcontact action.
Refs: #6223
> fix(clapi): fix acl group setcontact export

- www/class/centreon-clapi/centreonResourceCfg.class.php
When importing resource macro, CLAPI is expecting macro's id to be provided with setparam action.
Refs: #6221
> fix(clapi): fix resource setparam export

- www/class/centreon-clapi/centreonCentbrokerCfg.class.php
Ids start at 0 when using the web UI, were starting from 1 from CLAPI.
Refs: #5011
> fix(clapi): fix broker endpoint ids offset

- www/include/common/autoNumLimit.php
The history limit is being updated in www/main.php after the current page has loaded, so the autoNumLimit.php file sets a wrong $num on the first load of the pagination results.
> fix(pagination): remove history limiting check

- www/include/configuration/configObject/escalation/formEscalation.php
**Steps to reproduce the issue:**
1. Create a ldap configuration which is unreachable
2. Go to the escalation page
**Describe the results you received:**
Page is not displayed
**Describe the results you expected:**
Page is displayed
> clean(code): remove dead code from escalation page

- www/include/configuration/configGenerateTraps/formGenerateTraps.php
Fix trap generation form reindexing pollers id when adding All Pollers entry.
Fix: https://github.com/centreon/centreon/issues/6205
> fix(conf): trap generation reindexing pollers id

- cron/centAcl-Func.php
If severities are present on actual object, do not try to get severities from templates
> fix(acl): do not get severity of parents if present on actual object

- www/include/options/oreon/modules/listModules.ihtml
- www/include/options/oreon/modules/listModules.js
- www/include/options/oreon/modules/moduleDependenciesValidator.php
The column containing the expiration date of a module was linked to the old licensing system.
It is now possible to manage this date directly in the modules.
> Listing modules : manage the license expiration date

- bin/centreon
- bin/export-mysql-indexes
- bin/generateSqlLite
- bin/import-mysql-indexes
- cron/downtimeManager.php
- libinstall/check_pear.php
- libinstall/clean_session.php
This will ensure that the correct PHP runtime will be used when binaries are run.
> Use @PHP_BIN@ macro everywhere

- cron/centreon-backup.pl
- www/install/php/Update-2.8.26_to_18.10.0.php
As Nagios Plugins are now placed under /usr/lib64 on CentOS 7, their path have to be updated if necessary.
> Update Nagios Plugins path

- www/include/common/javascript/datepicker/localizedDatepicker.js
I Need to split the method for MBI, to avoid re-initializing the datepickers when user's format need to be set again.
> Mon-datepicker-split-method

- www/class/centreonContactgroup.class.php
if there are multiple ldap configuration, and each ldap has several same
ldap groups DN, it is now possible to link all those contactgroup in an
acl access group
> fix(ldap): manage multiple ldap group with same dn

- lang/fr/LC_MESSAGES/messages.po
MON-2837
The translation already existed but was commented so I just enabled them.
> fix(sidemenu): MBI side menu translation doesn't work

- www/include/core/pathway/pathway.php
> fix(breadcrumb): retrieve menu when open breadcrumb link in a new tab

- doc/en/configuration_guide/process_description/managetraps.rst
This error was detected in the SNMP trap guide.
> fix(doc):  update Rest syntax for a code block

- src/Centreon/Domain/Repository/TopologyRepository.php
Call the getAccessGroups method of CentreonACL.class.php from TopologyRepository.php instead of accessing the private property accessGroups directly
> fix(access): Fix a blank page when login with a non-admin user

- lib/perl/centreon/script.pm
- lib/perl/centreon/script/centcore.pm
- src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
* CLAPI enableREmote define Remote Server variable in /etc/centreon/conf.pm
* CLAPI disableREmote set Centreon variable in /etc/centreon/conf.pm
* Centcore on Central Server forward external commands to Remote Server attached to Poller if defined
*  Centcore on Central Server synchronise configuration folders with Remote Server attached to Poller if defined, and forward associated external command
* Centcore on Remote Server apply commands
> enh(centcore): Use Remote Server to send conf and external commands

- www/include/configuration/configNagios/DB-Func.php
when inserting data from a duplicate poller two regex are broking the query : 
` ,- '~!$%^&\\*"|' <>?,()=', `
and  ` '~$^&"|' <>', `
where the single quotes after the pipes weren't escaped
> fix(db): escaping the regex which broke the query

- www/include/core/login/login.php
- www/include/core/login/template/login.ihtml
Change copyright date calculation code and replace mailto link by a direct link to our website - in order to avoid that some final user send email directly to Centreon
> enh(copyright): update copyright date calculation code and change mailto link

- src/CentreonRemote/Application/Clapi/CentreonWorker.php
* Prevent empty centreon_path for Poller Display migration because poller configuration is present and the user don't use the wizard (centreon_path => NULL in database)
* Add more debug information
> fix(remote-server) Minor fixes for remote server worker

- www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
For users with ACL, the SQL request get the list of all host / service couple and not only host list.
> fix(acl): Host number calculation with ACL is not correct in HG summary

- www/include/configuration/configObject/contact/formContact.php
- www/include/configuration/configObject/contact/formContactLight.ihtml
Because not all configuration is exported on a Remote Server, it is impossible to edit a contact because notification commands are required in the form.
This light form allows to configure new Centreon user to log in the web interface on a Remote Server and add them to ACL.
> enh(remote-server): Add light form to edit contact on a Remote Server

- cron/centreon-backup.pl
RESOLVE: MON-2917
There was a missing trim that made the cp of PHP configuration files fail.
> fix(backup): fix missing trim for PHP files to backup

- src/Centreon/Domain/Repository/TopologyRepository.php
Update topology for react endpoint to return topologies that have topology_url not topology_page not null
Resolves: MON-3147
> fix(acl-react): update topology extract where clause from db

- doc/en/migration/upgradetoCentreon18.10.rst
The documentation forgot to mention that the content of the directory "/usr/share/centreon/installDir/install-18.10.0-YYYYMMDD_HHMMSS/ must be moved in usr/share/centreon/www/install in order to finalize the migration.
Besides there is wrong break lines in the bloc 'Upgrading Centreon' and a french expression 'IP_DU_SERVEUR_CENTREON' were not translated
> fix(doc) Migration 1810: move the installDir EN

- doc/fr/migration/upgradetoCentreon18.10.rst
The documentation forgot to mention that the content of the directory "/usr/share/centreon/installDir/install-18.10.0-YYYYMMDD_HHMMSS/ should be moved in usr/share/centreon/www/install in order to finalize the migration.
Besides, the following sentence can be misunderstood, some user think that the web installation is included, some of them think it's excluded:
"Installez un nouveau serveur Centreon à partir de l’ISO ou des paquets et terminez le processus d’installation jusqu’à vous connecter à l’interface web."
> fix(doc) Migration 1810: moove the installDir FR

- doc/en/upgrade/from_packages.rst
- doc/fr/upgrade/from_packages.rst
Because otherwise some dependencies might be broken.
> Update procedure should include all centreon* packages.

- doc/en/upgrade/from_packages.rst
- doc/fr/upgrade/from_packages.rst
Without this command, centos scl repository is not taken
into account, and upgrade process fails
> fix(doc): add clean yum cache command for 18.10 upgrade

- doc/fr/installation/architecture/03e.rst
notice:
* Remote Server is a proper noun
* Chart is correctly displayed on official documentation
Ref: #6957
> fix(doc): correct typo in RS architecture FR chapter

- doc/fr/migration/upgradetoCentreon18.10.rst
need to clear /var/lib/mysql on new DB serveur to avoid having ibdata1 ect not corresponding to table files (error with 'remote_servers' table during update steps)
> clear /var/lib/mysql + correct rsync

- doc/fr/administration_guide/partitioning/user/exploitation.rst
il semble que le paramètre attendu après le "-m" soit le nom de la table et non le nom du fichier de définition xml.
Avec la commande originale : 
<code># php /usr/share/centreon/bin/centreon-partitioning.php -m /etc/centreon/centreon-partitioning/partitioni
ng-data_bin.xml
[Fri, 21 Dec 18 08:58:44 +0000] PARTITIONING STARTED
[Fri, 21 Dec 18 08:58:44 +0000] Config file '/usr/share/centreon//config/partition.d/partitioning-/etc/centreon/centre
on-partitioning/partitioning-data_bin.xml.xml' does not exist
[Fri, 21 Dec 18 08:58:44 +0000] PARTITIONING EXITED
</code>
> [DOC] Correction commande incorrecte

- www/class/centreonXML.class.php
UTF-8 encoding control use lot of memory and engine conf generation fails when there are few thousands of resources
we'd better use the default php implementation instead (mb_detect_encoding)
> MON-3298 enhance utf-8 check

- bin/centreon-post-module-install.sh
Useful when modules require their classes to be loaded through the autoloader.
> feat(build): add a post module installation script that will regenerate the autoloader.

- www/front_src/src/styles/partials/_side-nav.scss
Enhancment of menu visibility by indenting the third-level elements.
Open the left menu bar then you should see that the third level menu items are indented.
**\*** updating the …
> enh(UI): Indent the third level menu

- doc/en/release_notes/centreon-19.04/centreon-19.04.0.rst
- doc/fr/release_notes/centreon-19.04/centreon-19.04.0.rst
- www/include/configuration/configObject/command/minPlayCommand.php
Original author : @gquere
Adding : bindValue methods to prevent SQL injection and PSR2 
<h1> Authenticated RCE</h1>
<h2> An RCE was exploitable in minPlayCommand.php </h2>
Check :
https://github.com/centreon/centreon/pull/7099
Fixes # (issue) : none
Ask me in private please.
> fix(secu): rce vulnerability when using command's testing feature

- www/front_src/src/styles/partials/_side-nav.scss
Indentation of third level menu for better delimitation of levels.
Open the left menu then see if the third level menu items are a little bit indented.
**\*** updating the release note results in adding the **pull request id** and **description** at the end of the file. **Product Managers** will rework it for the release. Release notes can be found [here](https://github.com/centreon/centreon/tree/master/doc/en/release_notes).
<h5> Centreon …
> enh(ui) : indent third level menu

- .gitignore
adding centreon-build/ to .gitignore file
Fixes # (issue): none
> enh(git): adding centreon-build to .gitignore

- doc/en/installation/common/install_packages.rst
- doc/fr/installation/common/install_packages.rst
It is an update in the documentation to restart the type of service responsible for the timezone change described in the documentation. Because a new include file is created for PHP, the service that needs to be reinitialized is PHP-FPM.
All changes to php settings are managed by the PHP-FPM service.
- [ ] I have made sure that **acceptance …
> fix(doc) Restart php-fpm instead of Apache for changes in php.ini

- www/install/steps/process/createDbUser.php
When an installation of the Centreon is done using the database server (MySQL) on an external server and it is on another network being accessed only via NAT, an ip address is mistakenly assigned in the user permission `centreon` of MySQL.
Currently it uses a server variable to get the client ip (`$_SERVER['SERVER_ADDR']`). however, when the server is in another network location, the ip that needs to be allocated in the user's permission is the network gateway (which does the NAT).
As for getting to this `centreon` user creation function, it is necessary to have the connection using valid `root`, I am taking into account that there is a valid connection and functioning as `root`. ~~So, I have a attribute available in the PDO …
> fix(install) Get the ip address of an existing connection to set the permission correctly

- cron/centreon-send-stats.php
- www/install/step_upgrade/process/process_step5.php
- www/install/step_upgrade/step5.php
- Fix bug on update, manage $parameters["send_statistics"] only if form appears or keep last value in DB.
- Ask to participate to CEIP on major release version if 'send_statistics' never exist in DB or if it was disabled.
- Prevent centreonRestHTTP exception in logs:
```
PHP Fatal error:  Uncaught RestNotFoundException: Page not found in /usr/share/centreon/www/class/centreonRestHttp.class.php:185
Stack trace:
#0 /usr/share/centreon/cron/centreon-send-stats.php(43): CentreonRestHttp->call('https://sstatis...', 'POST', Array, Array, true)
#1 {main}
thrown in /usr/share/centreon/www/class/centreonRestHttp.class.php on line 185
```
- Have a Centreon version 18.10.x (x > …
> Improve ceip install update

- www/index.php
- Fix the undefined index :
`PHP Notice:  Undefined offset: 1 in /usr/share/centreon/www/index.php on line 112` in :
`/var/opt/rh/rh-php71/log/php-fpm/centreon-error.log`
- Correct style and psr2 issues
Open the IHM, this notice should appear in the PHP log very frequently
> fix(log): correct the undefined index notice in the logs

- doc/en/administration_guide/parameters.rst
- doc/en/developer/translatecentreon.rst
- doc/en/faq/performance.rst
- doc/en/faq/remote_server.rst
- doc/en/installation/common/install_packages.rst
- doc/en/installation/from_sources.rst
- doc/en/installation/prerequisites.rst
- doc/en/upgrade/from_packages.rst
- doc/fr/administration_guide/parameters.rst
- doc/fr/developper/translatecentreon.rst
- doc/fr/faq/performance.rst
- doc/fr/faq/remote_server.rst
- doc/fr/installation/common/install_packages.rst
- doc/fr/installation/from_sources.rst
- doc/fr/installation/prerequisites.rst
- doc/fr/upgrade/from_packages.rst
Replace standard *httpd* service with *httpd24-httpd* in the documentation.
Follow documentation for prerequisites, installation, upgrade, performance (normal and remote server). Centreon should work as expected without further tweaking of _httpd_ and/or _httpd24-httpd_ services.
- [ ] ~I have made sure that **acceptance tests** related to the story are successful (**local and CI**)~
> Use httpd24-httpd service in the documentation.

- www/install/sql/centreon/Update-DB-2.8.26_to_2.8.27.sql
- www/install/sql/centreon/Update-DB-2.8.27_to_18.10.0.sql
The 2.8.27 has been released but the 18.10.x branch has not been updated. Therefore the **Update-DB-2.8.26_to_2.8.27.sql** was missing on the 18.10.x branch.
The **Update-DB-2.8.26_to_18.10.0.sql** has been renamed to **Update-DB-2.8.27_to_18.10.0.sql** and updated.
Update a 2.8.27 version of Centreon Web to the latest 18.10.x and everything should work
> upgrade(core): add missing SQL upgrade script

- www/class/config-generate/broker.class.php
Broker configuration doesn't generate rrdcached external information in a new install. 
Install a new centreon. (Or delete rrdcached external information: delete from cfg_centreonbroker_info where config_key IN ('path', 'port') AND config_group_id = 0 AND config_group = 'output')
Add rrdcached configuration in 'Administration > Paramaters > rrdtool' and generate configuration for the central server:
* before the patch: you don't have rrdcached information in /etc/centreon-broker/central-rrd.xml file
* after the patch: you have  rrdcached information in /etc/centreon-broker/central-rrd.xml file
<h5> Community …
> fix(rrd): broker config generate external values

- bin/centreon_health
- lib/perl/centreon/health/checkbroker.pm
- lib/perl/centreon/health/checkdb.pm
- lib/perl/centreon/health/checklogs.pm
- lib/perl/centreon/health/checkmodules.pm
- lib/perl/centreon/health/checkrrd.pm
- lib/perl/centreon/health/checkservers.pm
- lib/perl/centreon/health/checksystems.pm
- lib/perl/centreon/health/misc.pm
- lib/perl/centreon/health/output.pm
- lib/perl/centreon/health/ssh.pm
- lib/perl/centreon/script/centreon_health.pm
Script that gathers various information useful for centreon diagnostic.
PR made from @Sims24 one (_reworked a little bit_)
Script to quickly gather an overall overview of centreon scope and parameters. Very helpfull when things goes bad. Easily extensible.
Cover following topics : 
- rrd
- database
- module
- server
- systems
- broker
- logs
Centreon version : More complete for 2.8.x, but also manage 2.7.x (el6 and el7).
Offers following output format : 
- MARKDOWN
- JSON
- TEXT 
- DUMPER (debug perl)
Only prerequiste is perl binding for SSH C lib and centreon_plugins for Linux (SNMP) : 
+ el6 
``` 
yum install libssh libssh-devel 
git clone https://github.com/garnier-quentin/perl-libssh
cd perl-libssh/
perl Makefile.PL
make && make …
```
> feat(core): centreon_health script to gather various data

- www/class/centreon-knowledge/procedures.class.php
- www/class/centreon-knowledge/procedures_Proxy.class.php
- www/class/centreon-knowledge/wiki.class.php
- www/class/centreon-knowledge/wikiApi.class.php
- www/include/common/autoNumLimit.php
- www/include/common/pagination.php
- www/include/configuration/configKnowledge/display-hostTemplates.php
- www/include/configuration/configKnowledge/display-hosts.php
- www/include/configuration/configKnowledge/display-serviceTemplates.php
- www/include/configuration/configKnowledge/display-services.php
- www/include/configuration/configKnowledge/pagination.php
- www/include/configuration/configKnowledge/popup_form.php
- www/include/configuration/configKnowledge/proxy/proxy.php
- www/include/configuration/configKnowledge/search.php
- www/include/configuration/configKnowledge/templates/display.ihtml
- www/include/core/header/htmlHeader.php
- www/install/step_upgrade/step5.php
- Pagination and filters fix for the "configuration > knowledgeBase" pages
- fix the broken serviceTemplate's  wikiURL
- correct the getServiceId() method's query
- replace $oreon with $centreon
- style, psr2 and license update
- remove the php notice array to string conversion in the htmlHeader.php file
- fix $o in the ternary of the common/pagination.php file
Save a filter and check that when you change the pagination filter, the filter fields aren't empty and the displayed results are what they should be
> Mon 3659 mediawiki configuration and pagination

- www/front_src/src/components/pollerMenu/index.js
- www/front_src/src/components/userMenu/index.js
- www/front_src/src/styles/partials/_header.scss
When clicking on configure poller, or Edit Profile the whole page was reloaded.
* Using Link from react-router-dom instead of <a>
* Handle the toggle of the menu once the link clicked
* Update scss file for the "Edit Profile" style
- Click on the **configure pollers** button => only the iFrame should be refreshed and **not** the whole page
- Click on the **Edit profile** link => only the iFrame should be refreshed and **not** the whole page
> enh(ui): only refresh iFrame when click on link

- lang/fr/LC_MESSAGES/messages.po
Part of the graph page texts aren't translated in french
Fixes # ( https://github.com/centreon/centreon/issues/7425 )
Change localization to fr_FR.UTF8, then go to page 20401
> fix(ui): missing french translations in the graph page

- www/front_src/src/components/serviceStatusMenu/index.js
The link in the top counter does not have the good url when we click services in OK status.
Click on the top counter link to check the services in status OK.
The number of services in the OK status must be identical to the number indicated in the topcounter.
> fix(topcounter): Fix the top counter link to check the services in status OK

- www/class/centreonCustomView.class.php
If the view is being added for the first time, we make sure that the widget parameters are going to be set
Get all widget's parameters from the view that is being added and add every widget parameters to the current user
you can test this pull request by creating a new view with various widgets on it and configure them so that they do not show the default data and/or the warning message telling you ton configure them. 
When done, just make your view public so that people can add this view to their home page. 
Switch to another user, try to load the public view, you'll notice that every single widget in the view is not …
> fix(widget) : widget params on public view

- www/include/configuration/configObject/service/listServiceByHost.php
- www/include/configuration/configObject/service/listServiceByHostGroup.php
Fix "configuration > service > service by host" page's broken list.
Correct variable naming and remove camelCase to fit the parent's name
go to "configuration > service > service by host" and check if a list is displayed and if there's no errors in the PHP log
> fix(query) in configuration - service by host, for non admin users

- www/class/centreonAuth.LDAP.class.php
- www/class/centreonLDAP.class.php
- www/include/monitoring/status/Hosts/xml/hostXML.php
Correct the ACLs locking away every non-admin users from the monitoring > status > hosts page
Log in as a non-admin user, check that you have at least one host active in the top counter.
Go to the monitoring > status > host page and check that every hosts status values displayed in the top counter are effectively displayed in the list.
> fix(ldap) monitoring status host list for acl on non admin

- www/include/Administration/configChangelog/viewLogs.php
**To be merged only after Centreon 19.04.0 version released**
Remove the notice :
`PHP Warning:  Invalid argument supplied for foreach() in `
`/usr/share/centreon/www/include/Administration/configChangelog/viewLogs.php on line 213`
Go to Adminsitration > logs and check the PHP logs
> fix(logs): administration viewLogs, remove the log's undefined notice

- doc/en/installation/common/install_packages.rst
- doc/fr/installation/common/install_packages.rst
>h1> Pull Request Template </h1>
In the case of a dedicated SQL server, user must be aware that the
actual Centreon code (SQL request) is not compatible with the SQL
strict mode. Those changes are planned to be done in next releases
Display the documentation and check that restriction has been added for the installation of a dedicated SQL server
> enh(doc): add restriction on SQL strict mode for dedicated server

- doc/en/installation/common/install_packages.rst
- doc/fr/installation/common/install_packages.rst
Define how to create distant root MySQL user
Fixes #7491
Follow actual documentation, you can't perform installation if you don't know how to create distant DBMS root user.
> enh(doc): create distant MySQL root user for installation

- www/class/centreonLogAction.class.php
- www/include/Administration/configChangelog/viewLogs.ihtml
- www/include/Administration/configChangelog/viewLogs.php
Fix the pagination in the administration > logs page
Fix the rows count to be displayed in the page
Correct the filtering of the results to be displayed
Fixes # (https://github.com/centreon/centreon/issues/7487)
**Issue 1** -> Go to Administration > logs, and check that the pagination is working properly using the filters of your choice.
**Issue 2** -> All the results in the DB weren't properly displayed, if a host/service relation isn't found, while an event for this resource have been saved in the DB.
For the test : Go to Configuration > Hosts, and create a host with a service template (like OS-Linux-SNMP...)
Reload the poller, then …
> fix(ui): pagination and results in the administration logs page

- www/include/monitoring/status/Common/commonJS.php
When the option for one of the Poller, Servicegroup, or Hostgroup groups is selected, a double Webservice call is performed.
Open de debug tab in your webrowser. In the debug tab select the network tab and change option from one of these lists: Poller, Hostgroup, Servicegroup.
For each change, only one webservice call is performed.
> fix(status details): Fix a double webservice call

- www/include/monitoring/status/Services/service.php
- www/include/monitoring/status/Services/xml/serviceXML.php
- www/include/monitoring/status/Services/xsl/service.xsl
Fixed statusFilter that changed before the xls call was completed.
Fixed the xls file to display the hard_state_duration column only when the state filter is 'ok' or 'pending'.
> fix(monitoring service): Fix hard_state_duration column

- .babelrc
- doc/en/administration_guide/ui_access.rst
- doc/en/installation/from_sources.rst
- doc/fr/administration_guide/ui_access.rst
- doc/fr/installation/from_sources.rst
- package-lock.json
- package.json
- webpack.config.js
- www/.htaccess
- www/front_src/public/index.html
- www/front_src/src/App.js
- www/front_src/src/Provider.js
- www/front_src/src/axios/index.js
- www/front_src/src/components/clock/index.js
- www/front_src/src/components/externalRouter/index.js
- www/front_src/src/components/header/index.js
- www/front_src/src/components/hook/index.js
- www/front_src/src/components/hostMenu/index.js
- www/front_src/src/components/pollerMenu/index.js
- www/front_src/src/components/serviceStatusMenu/index.js
- www/front_src/src/components/userMenu/index.js
- www/front_src/src/config/index.js
- www/front_src/src/index.js
- www/front_src/src/redux/reducers/globalsReducer.js
- www/front_src/src/redux/reducers/index.js
- www/front_src/src/route-components/administration/extensions/manager/index.js
- www/front_src/src/store/index.js
- www/front_src/src/utils/dynamicImport.js
- www/index.php
* do not generate "www/template" folder anymore
* index.php only replace basename in index.html
* prepare usage of webpack dev server (and react-hot-loader ?)
Refs: MON-3793
try to rebuild centreon frontend : npm install && npm run build
> enh(front): use relative path to remove _CENTREON_PATH_PLACEHOLDER_

- www/class/centreonGraph.class.php
Hi,
This PR activates thresholds display on graphs when in Split chart mode, so when there is only one curve per graph.
Fixes #7342
Should also close #7235.
Display a graph with several curves, and with at least with thresholds.
With all curves on the same graph, thresholds are not displayed.
Go in Split chart mode, and verify here that thresholds are correctly shown.
Thank you 👍
> fix(graph): display thresholds in Split chart mode

- www/api/class/centreon_configuration_objects.class.php
- www/include/common/javascript/centreon/centreon-select2.js
- www/include/monitoring/downtime/listDowntime.php
- Correct the displayed saved researched value in the select2 components.
out of scope : 
- correct undefined variable in the logs when opening the downtime form
- minor style correction
- [] Patch fixing an issue (non-breaking change)
Open a form using a select2 filter.
Enter three letters of the name to be searched.
Select the occurence.
The popin should close.
Reopen the filter by clicking on it, your last research should be fully diplayed, and the select2 should display the other occurences available.
> Mon 3798 select2 previous search behavior

- www/include/views/graphs/javascript/centreon-graph.js
Hi,
Issue is detailed in #7330.
This PR solves it making no-unit series having their own y-axis.
Leading to this beautiful graph example :
Fixes #7330
As detailed in #7330, generate graphs with several series, some with a unit, some without unit.
Be then sure that series without unit are on their own y-axis.
Thank you 👍
> fix(graph): no-unit series now trigger a second axis

- src/CentreonLegacy/Core/Module/Installer.php
- src/CentreonLegacy/Core/Module/Remover.php
- src/CentreonLegacy/Core/Module/Upgrader.php
- src/CentreonModule/Tests/Application/Webservice/CentreonModulesWebserviceTest.php
- src/CentreonModule/Tests/Infrastructure/Source/ModuleSourceTest.php
- tests/php/CentreonLegacy/Core/Module/InstallerTest.php
- tests/php/CentreonLegacy/Core/Module/RemoverTest.php
- tests/php/CentreonLegacy/Core/Module/UpgraderTest.php
- www/class/centreon.class.php
- www/install/createTables.sql
- www/install/sql/centreon/Update-DB-19.10.0.sql
In the current system, modules have to declare wether they have *lang*, *SQL* or *php* files for install/update/uninstall in their conf.php. This has to be set in addition to the existence of the forementioned files so that they are properly processed.
Experience showed that this is not ideal and flag management might be overlooked, especially in updates' conf.php.
First, modules should have their *_files flags removed from their conf.php.
Then all installations, updates or removals should work normally.
> Do not care about *_files module flags

- doc/en/installation/common/web_install.rst
- doc/fr/installation/common/web_install.rst
- src/CentreonLegacy/Core/Install/Step/AbstractStep.php
- www/install/steps/functions.php
- www/install/steps/process/createDbUser.php
- www/install/steps/process/insertBaseConf.php
- www/install/steps/process/installConfigurationDb.php
- www/install/steps/process/installStorageDb.php
- www/install/steps/process/process_step6.php
- www/install/steps/templates/step6.tpl
Add a field to set database root user at installation if the root user is not actually root.
Closes: #6051 
Install a fresh 19.04.x instance.
> enh(config): add a field to set database root user at installation 

- composer.lock
- www/include/configuration/configObject/contact/ldapImportContact.php
Remove useless LDAP data sent to BE when importing contacts.
Please check the description and screenshots on ticket MON-3871
Please check the ticket MON-3871 for screenshots
> enh(BE): optimizing the data sent when importing contact

- www/install/php/Update-18.10.5_to_18.10.6.php
Complete the PR #7416
But the previous PR doesn't make the job for platform already in Centreon 18.10.4 version migrating from 2.8.27.
Install a Centreon 3.4.x version (Centreon Web 2.8.27)
In centreon.informations table, 'appKey, isCentral & isRemote entries are missing
Update to 18.10.5, information must be present.
> fix(update): re execute missing PHP update from 2.8.27

- www/include/configuration/configNagios/DB-Func.php
When you edit the Centreon Engine form and modify the Service Interleave Factor
The value stored is '2' and not your value
Got to "Configuration > Pollers > Engine" and edit a configuration.
Go on "Tuning" tab and change the value of **Service Interleave Factor**
Save the form
> fix(engine): add possibility to save service_interleave_factor

- install.sh
- libinstall/functions
Starting with Centreon Web 19.04.1, the frontend application build detection is not working anymore in the shell installer.
Install Centreon Web using the shell installer. Installation should go through with the message "Frontend application is built".
> Properly detect that frontend application is built

- bin/generateSqlLite
- doc/en/release_notes/centreon-18.10/centreon-18.10.6.rst
- doc/fr/release_notes/centreon-18.10/centreon-18.10.6.rst
- www/install/createTables.sql
- www/install/sql/centreon/Update-DB-18.10.5_to_18.10.6.sql
- www/install/sql/centreon/Update-DB-19.04.3.sql
Because some commands size are greater than 255, move varchar(255) db storage to text
**Fixes** #7062 
Edit a SNMP trap and add a command definition greater than 255 chars
> enh(traps): increase trap special command field size 

- www/class/centreonCustomView.class.php
- www/class/centreonWidget.class.php
backport #7104 for 2.8
Widgets' preferences of some old widgets (in custom views) aren't modifiable without deleting them and creating new ones.
New widget's aren't affected.
> fix(widget) fix preference

- www/include/configuration/configServers/DB-Func.php
If severals pollers a Remote Server and if a user update properties of one of them, all properties into remote_servers tables are updated
> fix(remote-server): update only properties of selected poller

- src/CentreonRemote/Infrastructure/Export/ExportManifest.php
Because on bug fixes version the SQL schema can't change, the task import of Remote Server should work on different bug fixes versions between Centreon central server and Remote Server
**Fixes** #7629
Given a Central server in 19.04.2 and a Remote server in 19.04.0
When I export the configuration of the Remote Server
The import task on my Remote Server should work
> fix(remote-server): do not compare bugfix version on task import

- src/Centreon/Domain/Entity/Task.php
- src/CentreonRemote/Application/Clapi/CentreonWorker.php
Before if an error appears during import/export task process
The error was present into centcore.log file but the task was completed in database instead of the task status.
Now logs and task table will display failed status
> fix(remote-server): set task in failed status if an error appears

- src/CentreonRemote/Domain/Resources/RemoteConfig/BrokerInfo/OutputForwardMaster.php
The actual Centreon Remote default configuration made by the wizard doesn't filter IPv4 output to Centreon central server.
This can generate conflict with RRD on Centreon central server.
This PR create an output to forward data with the NEB filter as category.
> fix(remote-server): filter output to master on NEB category only

- package-lock.json
- package.json
- www/front_src/src/App.js
This change is needed to be able to prioritize styling of emotion styled Components over Material-ui.
> chore(ui): Wrap App into StylesProvider with injectFirst to allow emotion styling

- www/include/Administration/myAccount/formMyAccount.php
- www/include/Administration/parameters/ldap/form.php
- www/include/configuration/configObject/contact/formContact.php
When using chrome browser, some password fields are autocompleted.
**Fixes** #6283 MON-4023
> fix(front): remove chrome password autocomplete in several form

- doc/en/api/api_rest/index.rst
- doc/en/api/clapi/objects/hosts.rst
- doc/fr/api/api_rest/index.rst
- doc/fr/api/clapi/objects/hosts.rst
- www/class/centreon-clapi/centreonHost.class.php
@smutel 's PR : https://github.com/centreon/centreon/pull/7557
rebased on the 19.04.x
need to be cherry-picked on the master (19.10.x) after successful validation
**Change the output of the command get param in centreon-clapi.
The output now follow the same output than the other commands.**
**Fixes** #6178
**Test of centreon clapi:**
`centreon -u admin -p XXXXX -o host -a getparam -v "Centeon-central;alias|address|timezone"`
**Test of the centreon REST API:**
`curl -H 'centreon-auth-token:xxxxxx' -H "Content-Type: application/json" -d '{"action": "getparam","object": "host","values": "Centeon-central;alias;address|timezone"}' "https://XX.XX.XX.XX/centreon/api/index.php?action=action&object=centreon_clapi"`
- [ ] I have made sure that …
> enh(api): update output of getparam command on host object

- cron/centreon-backup.pl
Configuration path for apache in 19.04 (httpd24-httpd) is now on /opt/rh/httpd24/root/etc/httpd/conf.d instead of /etc/httpd/conf.d.
This PR try to change the backup script accordingly.
> Change backup path for httpd24-httpd

- lib/perl/centreon/script/centcore.pm
- lib/perl/centreon/script/centreonSyncArchives.pm
- lib/perl/centreon/script/centreonSyncPlugins.pm
Based on PR #7630 to rebase on master and solve conflicts
Using a non default SSH port on a Remote Server leads to the following in `centcore.log`,
on the Central Server :
```
2019-06-18 16:54:19 - INFO - Export files on poller "remote-server" (32)
2019-06-18 16:54:28 - INFO - Result : [sender] io timeout after 6 seconds -- exiting
rsync error: timeout in data send/receive (code 30) at io.c(195) [sender=3.1.2]
```
This is due to a non valid usage of the port option of the rsync command.
While here, I found other SSH and rsync commands not using the configured port, so I fixed them.
Use a non default SSH port for your Remote Server and verify it is correctly used by centcore.
- [ ] I have made sure that **acceptance tests** related to the …
> Mon 3936 use correct ssh port

- src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
- src/CentreonRemote/Domain/Value/ServerWizardIdentity.php
When configuration a Remote Server through the wizard several API calls are made.
But one call doesn't used defined HTTP method and port define by user.
**Fixes** #7626
Given a Remote Server configured with HTTPS and with BAM installed
When I create it through the wizard
No error must be present into logs and BAM broker output must be created
Given a Remote Server configured with HTTPS and with BAM installed
When I export configuration and this configuration must contain BA
The BA are available on Remote Server
> fix(remote-server): check bam on remote server is http only

- src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
Fixes parameters string parsing to allow use of fqdn and ip.
Makes 'Notifying Master' process more verbose to understand where the failed action can come from.
Adds better logging.
Handles date/time better so its actually the date and time at the log printing.
Try to enable a remote with the following "url" list : https://regex101.com/r/IGDtNg/2, and see how it is parsed.
> fix(remote): fix enableremote parameters parsing and setting

- www/install/sql/centreon/Update-DB-19.04.0.sql
- www/install/sql/centreon/Update-DB-19.04.3.sql
* Moving the upgrade according to the 19.04.3 release
* Adding IF NOT EXISTS condition for the 19.10.0 release
IF NOT EXIST condition was not set for the 19.10.0 upgrade SQL
Therefore there was an error when upgrading to the latest version
**Fixes** # None
Test the upgrade from 18.10.x -> 19.10.x
> fix(upgrade): fixing issues with upgrade of traps_mode

- www/class/centreonGMT.class.php
If users don't choose a timezone then the GMT will be set to null 
Needed this fix to allow the export of the column Last check from service and host monitoring widgets
By trying to export either service or host monitoring widget while including Last check column  
> fix: GMT is null if user don't choose one

- www/class/centreon-clapi/centreonContactGroup.class.php
If a contactgroup is linked to a ldap server, clapi export/import does not work properly
(cg_ar_id column does not exist)
Refs: MON-4127
* Link Centreon web to ldap server
* Import contact group by linking it to ACL and contact
* Export contactgroup using clapi
* try to import it using clapi
> fix(clapi): fix import of contactgroup when linked to ldap

- www/include/views/graphs/generateGraphs/generateMetricImage.php
When trying to export a splitted graph, the back end call a removed class and throw a fatal error in the logs. Resulting in a blank page
go to performance graphs > choose a host > choose multiple graphs > click on the export png button
> Mon pear class not found in graphs

- www/front_src/src/translations/index.js
Redirect to login page if user try to access directly to a centreon page without being logged in
**Fixes** MON-3911
* Logout from centreon
* try to access directly to http://<ip_address>/centreon/administration/extensions/manager
* you should be redirected to login page
> fix(front): redirect to login page when user is unauthorized

- www/Themes/Centreon-2/style.css
Change default style of select tag
> enh(dropdowns): style default select to be as much like select2 as possible

- src/CentreonRemote/ServiceProvider.php
- www/Themes/Centreon-2/style.css
- www/api/class/centreon_clapi.class.php
- www/api/class/centreon_configuration_host.class.php
- www/api/class/centreon_configuration_hostgroup.class.php
- www/api/class/centreon_configuration_meta.class.php
- www/api/class/centreon_configuration_service.class.php
- www/api/class/centreon_configuration_servicegroup.class.php
- www/class/centreonAuth.SSO.class.php
- www/class/centreonGraphNg.class.php
- www/include/Administration/parameters/DB-Func.php
- www/lib/HTML/QuickForm/select2.php
PR is related to issue with ID BAM-12 and provide a new functionality of the grid and the select2 to display text `Object name (disabled)` if the status of an object is disabled
Fixes # BAM-12
You can test the APIs of services and meta-services, but a grid and select2 can be tested only with changes in BAM -> [BAM-12-show-disabled](https://github.com/centreon/centreon-bam/compare/BAM-12-show-disabled)
> enh(select2): allow to display disabled status in select2 options

- www/include/monitoring/objectDetails/template/hostDetails.ihtml
In command and shortcut, Configure host link display 2 time host name because host name are displayed in php file (hostDetails.php : 546), and in ihtml file (template/hostDetails.ihtml : 381).
Deleting host name display in ihtml.
Before fix
After fix
Check any host detail under monitoring before and after fix.
Before, host name is displayed 2 times.
After only 1 time.
> fix(ui): fix double host name display in host detail

- www/include/views/graphs/exportData/ExportCSVServiceData.php
this is a bandaid patch in order to fix  the column mismatch.
#5959
#7477
go in 
Monitoring  >  Performances  >  Graphs
select a graph with something like 3 to 5 metrics. Export it as CSV. With this patch, in the CSV file, you should have the right value in the right column
> match metric name with metric value #5959 #7477

- www/Themes/Centreon-2/style.css
Avoid host icon to be flattened in Monitoring > Hosts
**Fixes** MON-4156
> fix(ui): avoid host icon to be flattened

- www/install/steps/templates/step8.tpl
Actually the button was already disabled, but CSS was not changed
so that the user sees that it is really disabled.
Proceed with an installation of Centreon. When the last step (asking to install pp-manager, lm and autodicovery) when clicking on install then the button should be grey, not clickable and the text changes to "Installing..."
The checkboxes should also be disabled.
> fix(install): disable button when installing modules last step

- www/front_src/src/components/userMenu/index.js
When opening user menu (top right), it is displayed "asadmin" instead of "as admin"
**Fixes** MON-4153
> fix(ui): retrieve space before alias in user menu

- composer.json
- composer.lock
missing package symfony/translation, and it's added to the requirement list of composer.json
The package is a dependency of the `centreon.validator_translator` service
> fix(dependencies): add missing translation dependency in composer.json

- www/lib/HTML/QuickForm/HTML_QuickForm_checkbox_Custom.php
Fix style of checkboxes when form is frozen
to
**Fixes** MON-4161
> fix(ui): fix style of frozen checkboxes

- src/Centreon/Infrastructure/CentreonLegacyDB/CentreonDBAdapter.php
- www/class/centreonDB.class.php
This PR aims to allow Remote Server .infile configuration files to be loaded when MySQL strict mode is enabled on the Remote Server database.
The "LOAD DATA INFILE" has to be replaced by "LOAD DATA LOCAL INFILE".
The "MYSQL_ATTR_LOCAL_INFILE" option of PDO needs to be set to "true".
Before this patch, try to export and import Remote Server configuration when strict mode is enabled on the Remote Server database.
It will result with the following error :
```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'NULL' for column `centreon`.`giv_components_template`.`host_id` at row 1
```
After the patch, no error is rised.
> enh(db): allow remote server config to be loaded with mysql strict mode enabled

- www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
- www/include/monitoring/status/Services/xml/makeXMLForOneService.php
Sanitize host_id and service_id
Based on #7862 but for 2.8.x compatibility
> fix(security): sanitize host_id and service_id - 2.8.x

- doc/en/administration_guide/poller/enable_remote.rst
- doc/fr/administration_guide/poller/enable_remote.rst
As Remote Server does not have remote database, the grant option must be done to the "localhost" user.
If the grant is done to the "server ip" user, the import will result with the following error : 
```
SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'centreon'@'localhost' (using password: YES)
```
> fix(doc): change grant option for remote server database centreon user

- www/class/config-generate-remote/Generate.php
Set _remote_id_ to NULL and _remote_server_centcore_ssh_proxy_ to 0 for the exported pollers configuration.
Do an export/import process and check the database on the remote server.
> enh(remote-server): set remote_id/remote_server_centcore_ssh_proxy to NULL/0

- www/class/centreonSession.class.php
- www/include/core/login/login.php
- www/include/core/login/processLogin.php
- www/include/views/graphs/generateGraphs/generateImage.php
- www/index.php
- Securing the PHPSESSID cookie from hijack or modifications using the session.strict_mode in the php.ini (these modifications have been removed from current PR; and already merged on centreon-build to be deployed with the next RPMs).
- Regenerating the session_id() value after the login and after the logout
- Minor typo and variable naming corrections
-> Please contact me
> Mon 3204 enable session cookie strict mode for 2 8 x

- www/api/internal.php
- www/include/core/header/header.php
These parameters have been moved in the php.ini file to make these values global.
contact me
> fix(secu): the ini_set session duration param has been moved in php.ini

- www/Themes/Centreon-2/style.css
- www/include/configuration/configNagios/formNagios.ihtml
- www/include/configuration/configNagios/formNagios.php
Fix style of checkboxes in broker modules options field :
**Fixes** MON-4179
> fix(ui): fix style of broker modules options checkboxes

- www/install/createTables.sql
- www/install/sql/centreon/Update-DB-19.10.0-beta.3.sql
- www/install/sql/centreon/Update-DB-19.10.0-rc.1.sql
Move SQL upate to Centreon 19.10 RC.1
**Fixes** PR/#7849
From Centreon 19.10-beta.3 update to RC.1 and check if centreon.rs_poller_relation table exist
> fix(install): move SQL update to Centreon 19.10 RC.1

- www/front_src/src/components/serviceStatusMenu/index.js
- www/include/monitoring/objectDetails/template/hostDetails.ihtml
- www/include/monitoring/status/HostGroups/xsl/hostGroup.xsl
- www/include/monitoring/status/Services/service.php
- www/include/monitoring/status/Services/xsl/serviceGrid.xsl
- www/include/monitoring/status/Services/xsl/serviceSummary.xsl
- www/include/monitoring/status/ServicesHostGroups/xsl/serviceGridByHG.xsl
- www/include/monitoring/status/ServicesHostGroups/xsl/serviceSummaryByHG.xsl
- www/include/monitoring/status/ServicesServiceGroups/xsl/serviceGridBySG.xsl
- www/include/monitoring/status/ServicesServiceGroups/xsl/serviceSummaryBySG.xsl
Save properly "status filter" in Monitoring > Status details > Services
**Fixes** MON-4181
> fix(front): save properly monitoring service status filter

- www/class/centreonExternalCommand.class.php
To remove concurrent access to centcore.cmd file, create a file in /var/lib/centreon/centcore by action
> fix(externalcmd): Create centcore file by action

- www/include/monitoring/objectDetails/common-func.php
- Change method + add default message if can't apply method
- Add PDO bindParam method for SQL requests
- Fix PSR2
**Fixes** #7414
Based on #7859
Create different checks commands
Describe custom macros as password type in host, HTPL, service and STPL
Verify in service status details page if all passwords are replaced by '***'
> fix(status details): Fix hide password in command line for 2.8.x (#7414)

- src/Centreon/Domain/Service/I18nService.php
When several modules bringing there own translations are installed then the translation only works for one of them.
**Fixes** NONE
Install modules that have translations and check that if you change the LANG in the user profile  to French
> fix(i18n): issue with translation when several modules installed

- www/class/config-generate-remote/Generate.php
- www/include/configuration/configServers/formServers.php
* Fix issue on incorrect variable name
* Select also pollers attached to additional remote servers
> Mon 4190 issue with multiple rs

- src/CentreonRemote/Domain/Service/ConfigurationWizard/PollerConfigurationRequestBridge.php
- www/include/configuration/configGenerate/xml/moveFiles.php
- Remote server wizard failed when adding a remote server linked to the central server (without pollers)
- Data was not exported on remote server
**Fixes** BAM-748
> fix(remote-server): fix simple remote server creation

- www/class/config-generate-remote/Abstracts/AbstractHost.php
- www/class/config-generate-remote/Generate.php
- www/class/config-generate-remote/Host.php
- www/class/config-generate-remote/Relations/HostPollerRelation.php
Fix Centreon Remote Server configuration export to export now relation between host and poller. Used to send external command through Centcore process
> fix(remote-server): add missing host poller relation in export

- www/class/centreonWidget.class.php
Correct undefined pagination variable when increasing the number of rows of your custom view
**Fixes** # (MON-4165)
Add a view with 1 column.
Add at least two widgets
Then change the view configuration to 2 or 3 columns.
> fix(widget): undefined pagination variable when editing custom view

- src/CentreonLegacy/Core/Module/Upgrader.php
Take into account the removal of older conf.php files that were located in the upgrade directories of te modules (EMS)
**Fixes** NONE
Upgrade from the 19.04.x to the 19.10.0 with some EMS modules installed.
The WEB upgrade in Administration -> Extensions -> Manager should work
> fix(update): take into account the removal of older conf.php

- www/install/sql/centstorage/Update-CSTG-19.10.0-rc.2.sql
Fixed directly in broker : centreon/centreon-broker#307
It avoid to update columns during upgrade, which can take a long time with lot of data
**Fixes** BAM-750
> fix(upgrade): remove upgrade of bigint columns

- src/CentreonLegacy/Core/Module/Upgrader.php
If upgrade directory was empty, the last version was not set for the module
**Fixes** MON-4247
> fix(module): finish with upgrade to last version

- www/include/monitoring/downtime/AddDowntime.php
You can't set a downtime on a Poller using the popin form on :
"Monitoring > Downtimes > Downtimes" and selecting "Pollers", as no selectbox is available
Create a downtime and select a poller.
Then check the centengine.log of the selected poller and check that the command has been sent to centengine.
> fix(downtimes): apply dt on resources linked to a poller

- www/class/centreon.class.php
- www/include/core/header/htmlHeader.php
Clean css cache at each new version to avoid display issues
**Fixes** waiting ticket from @lpinsivy
> fix(css): clean cache at each new centreon version

- www/include/common/javascript/centreon/centreon-select2.js
- www/lib/HTML/QuickForm/select2.php
"Select All" option in multiselect component could take several minutes to end when lot of option where loaded.
This PR optimize drastically this load by inserting option using bulk
**Fixes** MON-4197
> fix(front): optimize select all in select2 component

- www/include/monitoring/status/Hosts/xml/hostXML.php
remove unused http parameters in hostXML.php file.
**Warning -> rebased on the MON-4314-fix-sql branch**
> fix(secu): remove unused http parameters in hostXML.php file for PHP7

- www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
- www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
Security fix which remove unused http parameters (eg: $_GET) or sanitize them in service by hostgroup
> fix(secu) remove unused params or sanitize them in service by hostgroup

- www/include/monitoring/status/Services/xml/serviceGridXML.php
- www/include/monitoring/status/Services/xml/serviceSummaryXML.php
- www/include/monitoring/status/Services/xml/serviceXML.php
Security fix which remove unused http parameters (eg: $_GET) or sanitize them in service pages
> fix(secu) remove unused params or sanitize them in service pages

- www/include/monitoring/status/Services/xml/serviceXML.php
remove unused http parameters in specified file.
> fix(secu): remove unused http parameters in serviceXML.php file for 2.8

- www/Themes/Centreon-2/style.css
- www/install/step_upgrade/step3.php
An user that wants to upgrade to the actual latest Centreon version will get all the 19.10.0 release notes displayed since this commit https://github.com/centreon/centreon/commit/5b035978f9de75a802d54635c7d0db5af3f04769
The goal here is to condense the display of those release notes per clickable sections.
* Upgrade to 19.10.x
* Go through the web upgrade
* Step 3 displays the release note
Latest RN version should be opened.
There is a hover on lines to show that those are clickable to display the content of the release note.
> enh(upgrade): display release notes per section

- package-lock.json
- package.json
With old version, "npm install" can fail cause centreon-react-components@19.10.0 has been unpublished from npm registry.
> chore(dependencies): update dependency of centreon-react-components

- www/api/class/centreon_administration_widget.class.php
- www/api/class/centreon_clapi.class.php
- www/api/class/centreon_configuration_objects.class.php
- www/api/class/centreon_home_customview.class.php
- www/api/class/centreon_keepalive.class.php
- www/api/class/centreon_metric.class.php
- www/api/class/centreon_proxy.class.php
- www/api/class/centreon_realtime_base.class.php
- www/api/class/centreon_results_acceptor.class.php
- www/api/class/centreon_submit_results.class.php
- www/api/class/centreon_topcounter.class.php
- www/api/class/centreon_wiki.class.php
- www/api/external.php
Some webservices was fully accessible using external.php
This PR allow to check access properly before executing webservice
**Fixes** MON-4301
curl '<ip_address>/centreon/api/external.php?object=centreon_metric&action=listByService'
==> should be forbidden
> fix(acl): filter access to api using external entry point

- cron/centAcl.php
The ACL extensions calculation is launched only if global Centreon ACL have been changed
Now the ACL extensions calculation is launched all time
Use module extension with ACL
Change ACL on module
Check if new ACL are applied
> fix(acl): calculate acl extension all time

- www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
service by servicegroups summary XML file
> fix(secu): remove unused http parameters in service by servicegroup summary XML

- www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
service by servicegroups grid XML file
> fix(secu): remove unused http parameters in service by servicegroup grid XML

- www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
- www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
- avoid SQL injection in service by service group pages
- correct the status 500 when the serviceBySGGridXML.php is called (variable was not bound in the second query)
- clean code
> fix(secu): Avoid SQL injections in service by servicegroup pages

- www/include/configuration/configObject/host/formHost.ihtml
- www/include/configuration/configObject/service/formService.ihtml
User can unhide password macros...
**Fixes** MON-4445
> fix(security): do not allow to unhide password macros

- www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
- www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
services by hostgroup XML files
> fix(secu): remove unused http parameters in services by hostgroup files

- www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
> fix(secu): remove unused http parameters in hostgroup xml.php

- unattended.sh
the unattended script fails when the firewall is installed but inactive
The unattended.sh script fails when a firewall is installed but not active.
This PR adds a test to check the firewall status and do not try to configure it if it is not active.
This is a record of the failure: https://asciinema.org/a/iIG8TdptGJa3Rjt58hW9oqQte
The script is ending too early, centreon services are not started and http request to the service (via curl command) fails.
- [] 19.04.x
Sart a new VM with a Centos/7 vagrant box, launch the script and check if centreon services are started and available.
https://app.vagrantup.com/centos/boxes/7
> fix(unattended): unattended failure

- www/install/steps/process/createDbUser.php
As the Centreon wasn't released with the mariaDB 10.2 as expected, the MySQL 8.0 modifications are incompatible with mariaDB 10.1.
As the ALTER USER clause were introduced on the mariaDB 10.2.
Resulting in an error blocking the installation script on a fresh install
**Fixes** # (blocking)
Try to install a fresh install using the current RPM -> an error occurs and you can't acheive the installation
Apply the fix, then try again -> The installation should work as expected
> fix(install): check mariaDB version before using ALTER USER

- www/Themes/Centreon-2/style.css
In some pages, the centreon popin is behind the scrollbar of the select 2.
Go to configuration > add > select all availables host in the select2 and check that the popin is properly displayed
> fix(UI): replace popin z-index

- www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
- www/include/monitoring/status/Hosts/xml/hostXML.php
- www/include/monitoring/status/Services/xml/serviceGridXML.php
- www/include/monitoring/status/Services/xml/serviceSummaryXML.php
- www/include/monitoring/status/Services/xml/serviceXML.php
- www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
- www/include/monitoring/status/ServicesHostGroups/xml/serviceSummaryByHGXML.php
- www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
- www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
Replace the regexp filter sanitize on the $order parameter with a whitelist.
Correct coding style for the CI
**Fixes** # (CI - 2.8.x)
1 - test the "order" of the status > monitoring pages
> enh(BE): replace order filter's regexp using whitelist 

- src/Centreon/Domain/Repository/NagiosServerRepository.php
- www/include/configuration/configGenerate/xml/restartPollers.php
- www/include/configuration/configServers/DB-Func.php
- www/install/createTables.sql
- www/install/sql/centreon/Update-DB-19.10.0-rc.1.sql
- www/install/sql/centreon/Update-DB-20.04.0-beta.1.sql
Add a new field to nagios_server table called `updated` which is a flag if the poller needs to be restarted (configuration changed) or not. This allows us manually to mark a poller as need-restart, for example when Business Activity changes.
**Fixes** #BAM-766
Update Business Activity and check the poller page.
> Poc new update field pollers

- www/include/home/customViews/index.ihtml
Hi,
When widgets page load, edit mode is disabled, but every widget edit mode remains enabled, as shown in the screenshot below. This PR then fixes this.
Display widgets pages and be sure edit buttons are hidden for every widget.
Thank you 👍
Edit : issue still present in 19.10.1.
> fix(UI): correctly toggle edit when widgets load

- www/class/centreonAuth.LDAP.class.php
- www/include/Administration/parameters/ldap/form.php
- www/install/php/Update-19.04.5.php
Correct the double slash added on specific characters of the DN
Add a mandatory rule to avoid auto-import silently fails (only displayed in the ldap.log), when no contact template have been added to the LDAP configuration form
1- auto login fix
Link an LDAP to your centreon, and check that you can manually import a contact.
Enable the auto-import feature
Use the auto-import feature, and login using one of the LDAP account never used
Check that the user have been correctly imported.
Logout
Login again
No error should be displayed in the logs. Each login should be successfull
2- LDAP form mandatory contact template
Go to the contact template page and delete every contact template available.
Go to the LDAP configuration …
> fix(ldap): ldap users using the auto-import cannot login - for 19.04

- www/class/centreonAuth.LDAP.class.php
- www/include/Administration/parameters/ldap/form.php
Correct the double slash added on specific characters of the DN
Add a mandatory rule to avoid auto-import silently fails (only displayed in the ldap.log), when no contact template have been added to the LDAP configuration form
1- auto login fix
Link an LDAP to your centreon, and check that you can manually import a contact.
Enable the auto-import feature
Use the auto-import feature, and login using one of the LDAP account never used
Check that the user have been correctly imported.
Logout
Login again
No error should be displayed in the logs. Each login should be successfull
2- LDAP form mandatory contact template
Go to the contact template page and delete every contact template available.
Go to the LDAP configuration …
> fix(ldap): ldap users using the auto-import cannot login - for master

- www/class/centreonAuth.LDAP.class.php
- www/include/Administration/parameters/ldap/form.php
- www/install/php/Update-19.10.2.php
Correct the double slash added on specific characters of the DN
Add a mandatory rule to avoid auto-import silently fails (only displayed in the ldap.log), when no contact template have been added to the LDAP configuration form
1- auto login fix
Link an LDAP to your centreon, and check that you can manually import a contact.
Enable the auto-import feature
Use the auto-import feature, and login using one of the LDAP account never used
Check that the user have been correctly imported.
Logout
Login again
No error should be displayed in the logs. Each login should be successfull
2- LDAP form mandatory contact template
Go to the contact template page and delete every contact template available.
Go to the LDAP configuration …
> fix(ldap): ldap users using the auto-import cannot login - for 19.10

- package.json
- www/front_src/src/components/breadcrumbWrapper/index.jsx
- www/front_src/src/redux/selectors/navigation/breadcrumbs.js
- www/front_src/src/redux/selectors/navigation/breadcrumbs.test.js
When clicking on 2nd level, we could be redirected to an unexpected menu.
This could happen on some configuration entries which redirect to plugin pack page
**Fixes** BAM-778
> fix(breadcrumb): fix breadcrumb url for parent's levels

- www/class/config-generate-remote/HostGroup.php
- www/class/config-generate-remote/ServiceGroup.php
If you export more than one remote server configuration at once, you won't have hostgroups/servicegroups files (if you same hostgroups/servicegroups between remote servers).
- Add one hostgroup only
- Export one poller attached to 2 remote servers
- Second remote server won't get data imported (no hostgroups.infile created)
> fix(remote-export): hostgroup and servicegroup not exported

- www/class/centreonSession.class.php
- www/include/common/common-Func.php
- www/include/configuration/configObject/host/formHost.ihtml
- www/include/configuration/configObject/host/refreshMacroAjax.php
The call of hosts macros can be performed without valid session.
**Fixes** # (CVE-2019-17644)
Please contact us
> fix(macro): Fix call of host macros list without authentication

- www/class/centreonSession.class.php
- www/include/common/common-Func.php
- www/include/configuration/configObject/service/formService.ihtml
- www/include/configuration/configObject/service/refreshMacroAjax.php
The call of services macros can be performed without valid session.
**Fixes** # (CVE-2019-17645)
Please contact us
> fix(macro): Fix call of service macros list without authentication

- www/class/centreonAuth.LDAP.class.php
- www/install/php/Update-19.04.5.php
The DN is escaped twice before inserting its value in the DB.
Resulting on a first successfull connection and the impossibility to connect again using the account.
As the ldapSearch method will use a DN which doesn't exist
Add to your LDAP specific escaped characters (like : " \, ") and manually import a contact.
The contact will be displayed in the list, but in the DB, the contact_ldap_dn will have two slashes.
> fix(ldap): correct double slashes in the saved DN - for 19.04.x

- www/class/centreonAuth.LDAP.class.php
- www/install/php/Update-19.10.2.php
The DN is escaped twice before inserting its value in the DB.
Resulting on a first successfull connection and the impossibility to connect again using the account.
As the ldapSearch method will use a DN which doesn't exist
Add to your LDAP specific escaped characters (like : " \, ") and manually import a contact.
The contact will be displayed in the list, but in the DB, the contact_ldap_dn will have two slashes.
> fix(ldap): correct double slashes in the saved DN - for master

- www/class/centreonACL.class.php
When user's ACL are calculated on a single lvl 3 element, a notice pop in the log
Add to a user rights to a single lvl3 page. Check that the notice isn't displayed anymore in the php logs
> enh(BE): remove ACL notice on lvl3 calculation

- www/Themes/Centreon-2/style.css
Revert the https://github.com/centreon/centreon/pull/8088
As the CSS classes of the widgets are not properly used, the centreon style.css z-index fix impact the host monitoring, service monitoring and metric select2 widgets.
The z-index correction need to be reverted to remove the side effects, until a more consistent fix is developed.
Add one of the 3 listed (above) widget, open the configuration popin, check that the select2 work properly
> fix(UI): revert popin z-index value from #8088

- src/CentreonRemote/Domain/Exporter/ConfigurationExporter.php
Host and service templates not properly imported on the remote-server. 
- export a remote-server
- there are no service templates and host templates
> fix(remote-server): Host and service templates not properly imported

- www/class/centreonWidget.class.php
When double quotes (") are defined in a widget title, the custom view won't load.
edit widget title
add double quote
refresh
> fix(widget): fix double quote in widget title

- www/class/centreonTraps.class.php
We can't save a trap configuration because it missed a comma and "trap_mode" was in double.
Edit a trap and do a modification. Click on save
> fix(traps) Can't save a trap configuration

- www/install/steps/process/createDbUser.php
Remove two notices in the php logs when installating Centreon
`[02-Dec-2019 11:57:01 Europe/Paris] PHP Notice:  Undefined index: version in /usr/share/centreon/www/install/steps/process/createDbUser.php on line 102
[02-Dec-2019 11:57:01 Europe/Paris] PHP Notice:  Undefined index: version_comment in /usr/share/centreon/www/install/steps/process/createDbUser.php on line 104
`
Install a Centreon from scratch, before the step 8, these two logs should be displayed in the php logs
> fix(install): remove 2 notice from the logs

- doc/en/api/api_rest/index.rst
- doc/en/api/clapi/objects/hosts.rst
- doc/fr/api/api_rest/index.rst
- doc/fr/api/clapi/objects/hosts.rst
- www/class/centreon-clapi/centreonHost.class.php
Add the capability to set parameter "acknowledgement timeout" of host through the API.
Add other missing parameters.
```
curl -s -H "centreon-auth-token:$CENTREON_TOKEN" -H "Content-Type: application/json" -d '{"action":"setparam", "object":"HOST", "values": "tf_host;acknowledgement_timeout;10"}' "${CENTREON_URL}/centreon/api/index.php?action=action&object=centreon_clapi"
```
> feat(api): Add some new parameters

- www/class/centreonTraps.class.php
It's impossible to save a SNMP trap configuration if we have a simple quote in "comments" or "special command" field.
It’s a blocking issue because we use simple quotes in special commands for Centreon DSM.
How to reproduce
Please go on "Configuration  >  SNMP Traps" and edit the LinkDown trap.
By default, the comment is "A linkDown(2) trap signifies that the sending protocol entity recognizes a failure in one of the communication links represented in the agent's configuration."
So you can't save it because there is a simple quote in "agent's"
> fix(sql): prepare update traps query

- package-lock.json
- package.json
Fix security issue on serialize-javascript, which is a dependency of terser-webpack-plugin
> fix(security): bump terser-webpack-plugin to 1.4.2

- lib/perl/centreon/script/centcore.pm
centcore always try to use ssh to restart/reload centengine
This PR allows centcore to restart/reload centengine on localhost without using ssh
**Fixes** MON-4195 MON-4152
restart centengine using CLAPI
> fix(centcore): fix restart/reload of centengine on localhost

- package-lock.json
- package.json
- www/front_src/src/App.js
- www/front_src/src/components/hostMenu/index.js
- www/front_src/src/components/pollerMenu/index.js
- www/front_src/src/components/serviceStatusMenu/index.js
- www/front_src/src/components/userMenu/index.js
- www/front_src/src/translations/index.js
Cannot reproduce
But it seems that if the top counter endpoint return 200 status and bad formatted date, it breaks the page
==> blank screen
**Fixes** MON-4590
Mainly check that the top counter is working properly
> fix(ui): check format of top counter's endpoints return data

- www/api/class/centreon_topcounter.class.php
On a fresh install, top counter was not display cause monitoring was never set.
This fix allows to display 0 values instead
Mysql COALESCE function allows to return 0 if the first result return NULL
**Fixes** MON-4590
* Install Centreon Web
* Check top counter without generate configuration
> fix(ui): display top counter even if monitoring is off

- tests/clapi_export/clapi-configuration.txt
- www/class/centreon-clapi/centreonHost.class.php
If configuration use host parentship the clapi export contains overlap
**Fixes** #7562
1. create an host "host1"
2. create an host "host2" which has parent "host1"
3. try to export using clapi
==> host line is not properly formatted
eg, host Poller1 with host parent Centren_DB :
[...]
HOST;setparam;Poller1;contact_additive_inheritance;0
HOST;setparam;Poller1;cg_additive_inheritance;0
HOST;setparam;Poller1;host_locked;0
HOST;setparam;Poller1;host_register;1
HOST;setparam;Poller1;host_activate;1
Centren_DBHOST;ADD;Mwameme;Mwameme;localhost;;Central;
> fix(clapi): fix overlapping in clapi export

- www/include/common/common-Func.php
The initialization of Smarty templates for "popins" & "custom view widgets" was on a different function.
To keep the compatibility with all consumers of this function, it is not destroyed but it uses the "main" function with the same arguments. 
Also, the path to the folders was not very aligned with the standards (__DIR__) so I changed that too so that it would be consistent and compatible everywhere.
Refs: STUDIO-2228
Check if the display and operation of the widgets of the different modules is still ok
> enh(smarty/tpl): simplify the initSmartyTplForPopup function & compatibility

- www/include/configuration/configServers/formServers.ihtml
- www/include/configuration/configServers/formServers.php
- www/include/configuration/configServers/servers.php
1- 
gorgone data shouldn't be displayed on the central poller configuration form.
This PR is intended to hide these options when the localhost parameter has been set.
Before :
After : 
2- 
Correct the error in the browser console (legacy)
**Fixes** # (VF MON-4509)
check the sreenshots above
> fix(UI): do not display gorgone options on central's form

- www/include/Administration/brokerPerformance/brokerPerformance.php
Adapt Broker statistics parsing to match new folder tree caused by Gorgone.
* Go to 'Administration > Platform Status > Broker Statistics'
* Select any monitoring instance
* Broker statistics are displayed (if enabled)
> enh(admin): adapt broker stats page to new folder tree

- doc/en/configuration_guide/timeperiod.rst
- doc/fr/configuration_guide/timeperiod.rst
This tab doesn't exist anymore in "Configuration > Users > Time Periods" menu
> fix(doc): Remove Extended Settings paragraph for TP

- www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
On "Monitoring > Status Details > Services by Servicegroup" page, we can't apply the two filters Display and Display details
Go to the "Monitoring > Status Details > Services by Servicegroup" page,
Select "Summary" in "Display" drop-down list,
Select all the options in "Display details" drop-down list,
Result is not filtered accordingly.
> fix(filter) apply second filter whatever the first

- libinstall/CentWeb.sh
- libinstall/functions
Some files are not copied from the binary to the final destination with the changes in Centreon 19.10.
- New `.env` file and `container.php` in the root directory.
- All files in the `config` directory are also absent.
Also, the Symfony cache folder is not created during the setup and the install dashboard will fail in this step (also because `.env` is not here).
Try to install Centreon on Ubuntu/Debian with the `install.sh -i` script and to run the HTTP dashboard. Both will fail at several steps.
> fix(install): update libinstall scripts for Centreon 19.10.x

- libinstall/functions
Installation by sources
The configuration is missing in the apache configuration file
It is necessary to modify the libinstall/functions file
function prepare_apache_config()
Installation by sources,
API is reachable.
> fix(install): modify the libinstall/functions file for APIv2

- www/include/options/media/images/listImg.php
when you search for image in administration -> parameters -> images, it doesn't work at all
let say you enter "dazdzadazdazd" in the search bar, and hit the enter key you'll still see all your images. After that, you can hit the f5 key, and now the filter is going to be applied.
- go in your administration->parameters->images menu
- write the name of an image you're looking for
- click the search button
- it should display only your image
- hit the F5 key, and your filter should still be applied
- remove what you wrote in the search field, hit the search button, it should display every images.
> fix(code) fix search image

- lib/Centreon/Object/Downtime/RtDowntime.php
- www/class/centreon-clapi/centreonRtDowntime.class.php
The CLAPI commands "-o RTDOWNTIME -a show -v "HOST"" and "-o RTDOWNTIME -a show -v "SVC"" use the internal_id for the downtimes, instead of the downtime_id which is unique.
Same for "-o RTDOWNTIME -a cancel".
This way, you cannot cancel the exact downtimes you want.
* Add several downtimes on several hosts and services of several pollers
* Use CLAPI to list real-time downtimes
* Try to delete some of those downtimes using listed IDs
* You will delete the downtimes you want (The external commands in engine will use the internal_id)
> fix(clapi): use downtime_id to show and cancel rtdowntimes (master)

- lib/Centreon/Object/Downtime/RtDowntime.php
- www/class/centreon-clapi/centreonRtDowntime.class.php
The CLAPI commands "-o RTDOWNTIME -a show -v "HOST"" and "-o RTDOWNTIME -a show -v "SVC"" use the internal_id for the downtimes, instead of the downtime_id which is unique.
Same for "-o RTDOWNTIME -a cancel".
This way, you cannot cancel the exact downtimes you want.
* Add several downtimes on several hosts and services of several pollers
* Use CLAPI to list real-time downtimes
* Try to delete some of those downtimes using listed IDs
* You will delete the downtimes you want (The external commands in engine will use the internal_id)
> fix(clapi): use downtime_id to show and cancel rtdowntimes (19.x)

- www/class/centreonGraph.class.php
- www/class/centreonGraphNg.class.php
- Re allow to use wildcard in curve definition
- Fix variable name to prevent PHP warning
**Fixes** #8131 
- [] Patch fixing an issue (non-breaking change)
1. Edit/create a curve definition
2. Use PRCE in curve name
3. Display a chart that one of the metrics can be validated by the definition
4. Check the curve definition is used (legend name, color of curve, ...)
> fix(chart): Re allow to use wildcard in curve definition

- www/api/class/centreon_configuration_service.class.php
fix select2 for services.
Caused by https://github.com/centreon/centreon/pull/8214
add a service downtime
> fix(select) remove unknown column

- doc/en/faq/performance.rst
- doc/fr/faq/performance.rst
A paragraph in Centreon FAQ for RRDCacheD is obsolete because we implement a FLUSH command in order to display chart in UI.
**Fixes** #8176
> fix(doc): remove obsolete paragraph - #8176

- www/class/centreonAuth.class.php
- www/class/centreonLog.class.php
Hi,
This PR follows PR #7502 (not merged).
Goal is for the system administrator to be able to use tools such as fail2ban to ban IPs generating too many failed login attempts.
First step is then to have correctly formatted authentication messages.
This PR is then rather simple.
Related Fail2Ban PR is here (already merged) : https://github.com/fail2ban/fail2ban/pull/2550
Generate failed logins and have a look into `/var/log/centreon/login.log`.
Thank you :+1:
Edit : still missing from 19.10.4.
> enh(sec) Improve authentication messages in login.log

- www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
- Correct displayed services status
When multiples host are linked to a same service in the servicegroup and only one host is still enabled, the status displayed in the detail view of the servicegroup is false.
- Correct pagination
The pagination displays unconsistent number of services. 
> fix: servicegroup details displayed status

- www/include/configuration/configObject/command/minHelpCommand.php
Macro problem, replace only $USERx$
Path problem, execute only plugins in /usr/lib64/nagios/plugins/
Go to 'Configuration > Services > Templates'
Select a command in 'Check Command' field
Click on the :info: icon
Popup will always display "Error: Cannot Execute this command due to a path security problem."
> fix(helper) fix path of the check command

- www/include/monitoring/downtime/AddDowntime.php
In the "Add downtime" form, the "End Date" format is bloked to m/d/Y while "Start date" format depending to the contact language.
When connected, change the language since the contact profile and change the language by fr_FR.
Next from the Monitoring > Downtime click on "**Add a downtime**", in the form the "**End date**" format is not equal to the "**Start date**" format.
> fix(monitoring): fix the End date format according to contact language

- www/class/centreonACL.class.php
If you disable a service and you try to filter on it in "Monitoring > Event Logs > Event Logs", this filter is not used
On a platform with event
Disable a service
Go to "Monitoring > Event Logs > Event Logs" menu
Select this service in "Services" filter
Select a period
Click on "Apply period"
You must see event regarding your filter
> fix(eventlogs): allow to filter on disabled objects

- www/include/configuration/configObject/command/minHelpCommand.php
Following of #8255
If command is a Centreon Plugins it will lead to “/usr/lib/centreon/plugins/centreon_linux_snmp.pl --help” that is not enough,
We should have --plugin=… and --mode=… to have the actual helper of the plugin’s mode,
I know its Centreon Plugins specific but as we want users to use those plugins, we should provide a way to make this feature match.
My command checking disk I/O on linux here in the conf:
$CENTREONPLUGINS$/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=diskio --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --device '$_SERVICEDISKNAME$' --name --warning-read='$_SERVICEWARNINGREAD$' --critical-read='$_SERVICECRITICALREAD$' …
> Mon 4634 check command helper option

- www/include/monitoring/status/Common/setHistory.php
- www/include/monitoring/status/Services/service.php
- www/include/monitoring/status/Services/xml/serviceXML.php
Save user's chosen serviceState and status filters to be able to keep current data when refreshing the page
On page "Monitoring  >  Status Details  >  Services"
The chosen service state and status should be saved and restored on a refresh of the page.
This PR isn't intended to override the slug of the URL.
ie : When you click on the topCounter, the URI is modified accordingly. So on a refresh, the user will lost the chosen service state and status overriden by the params in the slug.
eg : click on the topcounter "services OK" button -> the slug will override the state as "ALL" and the status as "OK".
> fix(filters): save service state filters to get consistent data on refresh

- src/Centreon/Infrastructure/Service/CentreonPaginationService.php
improve CentreonPaginationService::getListing to keep the same object of the repository.
Every time when we call `$this->db->getRepository(Repo::class)` we will receive a new object of the Repo class, to fix the problem described in the issue we need to keep the same object of the repository class
**Fixes** BAM-927
the CentreonPaginationService::getListing  has been using in API `/centreon/api/internal.php?object=centreon_command&action=list` with GET method and active session has to return JSON result
> [Pagination] BA: the pagination doesn't work

- webpack.config.dev.js
- webpack.config.js
This fixes the squares displayed instead of fonticons (like in the extension page). 
- Go to the extension page
- all icons should be displayed (no blank squares)
> fix(ui): Fix icons not loading and live reload (19.10.x)

- www/Themes/Centreon-2/style.css
Community Pull Request from @aladdinchan -> https://github.com/centreon/centreon/pull/8223
Fix the badge splitted on multiple lines on dense environments
**Fixes** # (8223)
From a listing page using text badges, like on the monitoring > status > services.
Check that the badge stay on a unique line no matter the density or the lenght of the displayed page
If you want to test in chinese, you can use the translation made by @zheddiewen -> here : https://github.com/zheddiewen/centreon-translation/tree/master/zh_CN/LC_MESSAGES
> enh(UI): Add nowrap style to badge class - from aladdinchan

- www/include/common/mobile_menu.php
Add third level menus with mobile access
Connect to Centreon using mobile
Go to a third level menu and click to acces
> enh(mobile): add third level menu in mobile

- doc/en/administration_guide/acl.rst
- doc/fr/administration_guide/acl.rst
- www/include/common/javascript/tool.js
Educate user about giving access to configuration menus in "Read/Write" mode.
- Check in Centreon documentation for "Administration > Access control list" chapter that special note and warning appear for "Menus Access" sub chapter
- Check in "Administration > ACL > Menus Access" menu in Centreon that when you check a main box for "Configuration" menus that all radio boxes are in "Read Only" mode
> Mon 4834 educate user menus access

- www/include/core/footer/footerPart.php
- www/include/monitoring/external_cmd/popup/popup.php
PHP Fatal error:  Cannot use isset() on the result of an expression
> fix(popup) check session id

- www/include/Administration/parameters/css/form.php
The introduction of react has disabled the CSS customization. But the page is broken and insert an error in the PHP and SQL logs.
Issue still not fixed on the latest 18.10.x
PR made only for the 18.10.x
Go to adminsitration > CSS and check that the form is displayed without errors in the specified logs
> fix(UI): correct blank CSS page

- libinstall/CentWeb.sh
replace the PHP_BIN macro in the files of the cron folder in the source installation script
> fix(install): replace macro in cron files

- doc/en/installation/from_sources.rst
- doc/fr/installation/from_sources.rst
Remove from documentation the useless "sed" replacement steps
> enh(doc): remove useless checks

- config/packages/serializer/Centreon/Monitoring.Service.yml
retrieve service status in API service listing, which was removed since a few days
get list of services using APIv2
check that state is returned
> fix(api): retrieve service state in service listing

- lib/perl/centreon/script/centcore.pm
Correct the export 
**Fixes** # (7741) from @tanguyvda 
when you have a poller linked to a remote server, if you export the trap configuration on it, it will fail because the central server doesn't create the trap directory related to the poller on the remote server.
this could have been handled using rsync instead of scp (rsync allows you to create parent directories when sending file. Since we use scp, we're better copying the whole directory instead of the sdb file.
have a poller linked to a remote server. export the snmp trap configuration from the central to the poller on the central server, you should have at least 3 objects inside the /etc/snmp/centreon_traps directory: one centreontrapd.sdb file one directory named after the ID of …
> fix(trapd): correct export on poller behind RS

- www/include/monitoring/comments/commentHost.php
- www/include/monitoring/comments/comments.php
- www/include/monitoring/comments/common-Func.php
- fix comments deletion for services and hosts
- sanitize data
**Fixes** # (#8308, #8306) - from rk4an
create a comment from the monitoring > status > downtime > comment page, then try to delete it
> fix(web): delete comments

- src/Centreon/Domain/Entity/NagiosServer.php
- src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
when the BA is creating the selected value in `Display on remote server` is not stored
**Fixes**  BAM-944
create BA with selected `Display on remote server` and after that open it again for editing, the drop-down has to be with a pre-selected value
> fix(api): improve linking a remote server to a BA

- webpack.config.js
This PR fixes Regexp path about fonts for windows
Front builds should pass.
> fix(webpack): Adapt font regexp path for Windows

- src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php
Fix the search parameter IN using only one parameter.
> fix(API v2): Fix the search parameter IN

- www/class/config-generate-remote/Abstracts/AbstractHost.php
Export hosts geo_coords attributs to Remote Server.
* On the Central server, add an host with geo coordinates,
* Check the database:
```
MariaDB [centreon]> SELECT geo_coords FROM host WHERE host_id = '11';
+----------------------------+
| geo_coords                 |
+----------------------------+
| 32.123456789,23.1234567890 |
+----------------------------+
1 row in set (0.000 sec)
```
* Export the configuration to the Remote Server,
* Check the database:
```
MariaDB [centreon]> SELECT geo_coords FROM host WHERE host_id = '11';
+----------------------------+
| geo_coords                 |
+----------------------------+
| 32.123456789,23.1234567890 |
+----------------------------+
1 row in set (0.000 sec)
```
> fix(configuration): export hosts geo_coords to remote server

- config/packages/serializer/Centreon/Monitoring.Resource.yml
- doc/API/centreon-api-v2.yaml
- src/Centreon/Domain/Monitoring/Resource.php
- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
improvements and feedback related to #8388
- skip executing of the SQL query for the Resource list if the filters are in conflict
- change the type of `last_check` to be like duration
- replace some properties to be virtual as short_type, duration, last_check (with type string)
**Fixes** MON-4887
> feat(api): set in Resource some properties as vritual and skip executing of the query if the filters are in conflict

- config/packages/serializer/Centreon/Monitoring.Resource.yml
- config/routes/Centreon/monitoring/metric.yaml
- doc/API/centreon-api-v2.yaml
- src/Centreon/Application/Controller/Monitoring/MetricController.php
- src/Centreon/Application/Controller/MonitoringResourceController.php
- src/Centreon/Domain/Monitoring/Resource.php
- tests/php/Centreon/Application/Controller/Monitoring/MetricControllerTest.php
new endpoints : 
- /monitoring/hosts/{hostId}/services/{serviceId}/metrics/performance
- /monitoring/hosts/{hostId}/services/{serviceId}/metrics/status
new properties of resource endpoint : 
- performance_graph_endpoint
- status_graph_endpoint
**Fixes** MON-4792
Check API documentation and validate new endpoints : 
- /monitoring/hosts/{hostId}/services/{serviceId}/metrics/performance
- /monitoring/hosts/{hostId}/services/{serviceId}/metrics/status
new properties of resource endpoint : 
- performance_graph_endpoint
- status_graph_endpoint
> enh(api): update service graph endpoints

- www/front_src/src/route-maps/route-map.js
- www/install/insertTopology.sql
- www/install/sql/centreon/Update-DB-20.04.0-beta.1.sql
Move `monitoring > resources (beta)` to `home > events view (beta)`
**Fixes** MON-4984
> enh(events): move resources to events view

- doc/en/installation/from_sources.rst
- doc/fr/installation/from_sources.rst
- install.sh
- libinstall/CentWeb.sh
- libinstall/functions
Manage gorgone integration on update using sources
Duplicate ssh keys in /var/lib/centreon-gorgone to be able to communicate with pollers and remote (using the legacy mode and without modifications)
> fix(core): duplicate SSH key on source upgrade

- lib/perl/centreon/script/centcore.pm
Depending on the external command, web UI writes one file per external command in the centcore directory (ie /var/lib/centreon/centcore/) or multiple in the centcore file (ie /var/lib/centreon/centcore.cmd).
For downtimes, we are in the first case.
So when we schedule lots of downtimes, in can take several seconds to schedule all downtimes.
This is because the loop in charge of processing files does it one at a time and call the function in charge to process the external command, often only one, that multliply the number of ssh connection opening/closing.
This cause a useless hanging of external commands.
In internal ticket.
> enh(centcore): move external command processing loop

- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
the services attached to the down host are not visible, the host is visible
**Fixes** MON-5019
> fix(api): prevent smart grouping of the services related to host with status down

- www/include/Administration/parameters/ldap/form.ihtml
correct the "undefined variable assumed to be ..." in the 
go to the LDAP form and check that the undefined warning log is not displayed anymore
> fix(web): undefined variable in ldap form

- www/install/steps/process/process_step8.php
- www/install/steps/templates/step8.tpl
Several issues occured during fresh installations of Centreon.
In fact sometimes the installation order is not correct (installing auto-discovery without license-manager and/or pp-manager).
This should not occur to prevent broken installations of modules.
- Do a fresh installation of Centreon.
- On Step 8 if you only select auto-discovery to install, license-manager and pp-manager should also be installed.
**Important**
There is no message clearly indicating the dependencies. This will be handled later on the Extension -> Manager and in the long term when redoing the installation wizard. This is a **simple quickfix**
> enh(install): add dependency mechanism to fresh installation

- www/install/steps/templates/step8.tpl
When the install was done of the modules/widgets in the step 7 of a fresh installation, the checkboxes were not correctly refreshed
- Prepare a fresh install of Centreon (with rpm installed modules like autodisco, bam, map, mbi)
- On step 7 of fresh installation when the selected modules are installed (click on the button)
- Dependencies of the modules should be automatically installed
- The checkboxes are turned into a green tick and disabled.
> fix(install): wrong value used for checkboxes refresh

- www/include/configuration/configServers/popup/popup.php
Use the `remote_server_use_as_proxy` option to determine wether Central or Remote is the "parent" of the Poller.
* Have a Central > Remote > Poller kinf of setup,
* Use ZMQ communication type for Poller,
* Set "Use the Remote Server as a proxy" to "Yes",
* Generate Gorgone configuration, authorized_clients key should be Remote thumbprint,
* Set "Use the Remote Server as a proxy" to "No",
* Generate Gorgone configuration, authorized_clients key should be Central thumbprint,
> fix(config): fix gorgone config generation for poller not using remote as proxy

- www/api/class/centreon_home_customview.class.php
Sanitize widgetId and viewId arguments in API request
**Fixes**  MON-4964
> fix(api): Sanitize arguments in API request

- features/bootstrap/URIContext.php
Reload page during spin() in URI tests. This should prevent URI tests from failing.
Run acceptance tests. URI tests should not fail randomly.
> Reload page during spin() in URI tests.

- www/front_src/src/Resources/index.tsx
when http code 500 is returned from resources endpoint, listing is reset to empty.
Furthermore, the snackbar error message is now more clearer
**Fixes** MON-5034
set search filter to `*test`
==> the listing should be empty
> fix(listing): set events view listing to empty on api error

- www/include/configuration/configServers/formServers.ihtml
- www/include/configuration/configServers/formServers.php
This PR fix an issue where when accessing the form to modify a Central or Remote poller configuration a PHP Notice was reported. 
This PR also fix a PHP Warning where an illegal offset was use in a template condition.
**Fixes** MON-5088
When opening the form for editing a poller configuration (Configuration -> Pollers) you shouldn't see any error in PHP logs
> fix(poller): Fix PHP errors on edit poller configuration form

- www/class/centreonUser.class.php
- www/include/Administration/myAccount/formMyAccount.php
- www/include/common/javascript/centreon/dateMoment.js
- www/include/common/javascript/datepicker/localizedDatepicker.js
- www/include/monitoring/downtime/AddDowntime.php
- www/include/monitoring/downtime/common-Func.php
- www/include/monitoring/downtime/downtime.php
- www/include/monitoring/downtime/template/AddDowntime.ihtml
- www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
- www/include/monitoring/external_cmd/cmd.php
- www/include/monitoring/external_cmd/cmdPopup.php
- www/include/monitoring/external_cmd/popup/massive_downtime.php
- www/include/monitoring/external_cmd/popup/popup.php
- www/include/monitoring/external_cmd/popup/templates/massive_downtime.ihtml
- www/include/monitoring/recurrentDowntime/templates/specific_date.html
- www/include/monitoring/status/Hosts/hostJS.php
- www/include/monitoring/status/Services/serviceJS.php
- www/include/views/graphs/graphs.php
- www/main.get.php
Fix an issue where datetime of downtimes weren't correctly computed, when not using the english localization :
- the ending datepicker was not set properly and displayed unconsistent date
- adding a downtime on two days, did not actualize the starting date of the datepicker
- setting an end time before the start date was possible and resulted on useless downtime (not processed by centengine)
**Fixes** MON-3935 & https://github.com/centreon/centreon/pull/7606 from @UrBnW  + https://github.com/centreon/centreon/issues/5963 + https://github.com/centreon/centreon/issues/7337 + https://github.com/centreon/centreon/issues/8266 + #8362 + #8383.
- Choose for example the french language.
- Select a default duration on the Administration > parameters …
> fix(web): correctly compute localized downtime's datepickers

- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
fix the problem with searching by parameter s.description in Resource list
example of the request
```http://localhost/centreon/api/beta/monitoring/resources?page=1&limit=10&search={%22s.description%22:{%22$rg%22:%22Ping%22}}```
**Fixes** MON-4882
> fix(api): fix search parameter s.description in Resource list

- www/front_src/src/Resources/Filter/index.tsx
- www/front_src/src/Resources/index.test.tsx
Search resources when search field is focused and enter is pressed
**Fixes** MON-5095
Type search in search field and press enter
==> check search is applied, without need of clicking on search button
> enh(ui): search resources when pressing enter key

- config/packages/serializer/Centreon/Monitoring.Host.yml
- config/packages/serializer/Centreon/Monitoring.Model.ResourceDetailsHost.yml
- config/packages/serializer/Centreon/Monitoring.Model.ResourceDetailsService.yml
- config/packages/serializer/Centreon/Monitoring.Service.yml
- config/routes/Centreon/monitoring_resource.yaml
- src/Centreon/Application/Controller/MonitoringResourceController.php
- src/Centreon/Domain/Monitoring/Host.php
- src/Centreon/Domain/Monitoring/Interfaces/ResourceRepositoryInterface.php
- src/Centreon/Domain/Monitoring/Interfaces/ResourceServiceInterface.php
- src/Centreon/Domain/Monitoring/Model/ImportTrait.php
- src/Centreon/Domain/Monitoring/Model/ResourceDetailsHost.php
- src/Centreon/Domain/Monitoring/Model/ResourceDetailsService.php
- src/Centreon/Domain/Monitoring/Model/ResourceDetailsTrait.php
- src/Centreon/Domain/Monitoring/ResourceService.php
- src/Centreon/Domain/Monitoring/Service.php
- src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
add new APIs of detail of host and services as part of the resources. The host\service objects are extended with the missing information
**Fixes** MON-5071
GET `/centreon/api/beta/monitoring/resources/hosts/14`
GET `/centreon/api/beta/monitoring/resources/hosts/14/services/24`
- [ x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
> feat(api): Add missing information to host and service endpoints

- www/install/php/Update-20.04.0-beta.1.php
- www/install/var/gorgone/gorgoneCoreTemplate.yaml
- www/install/var/gorgone/gorgoneRemoteTemplate.yaml
Manage the creation of remote configuration file on update for legacy mode
Add broker statistics on remote
Rename and improve broker statistics on central
Remove success message displayed in the logs after the update
**Fixes** # (MON-5119)
When updating to the 20.04, the remote should have a default configuration to be able to use the legacy mode in SSH
> fix(update): generate remote conf file on update

- www/include/configuration/configServers/popup/remote.yaml
Add to the remote template the broker statisctic module and enable it.
In the export configuration popup
**Fixes** # (MON-5121)
Export the configuration on a remote server and check that the broker statistics are retrieved
> fix(conf): add broker stat to remote conf

- www/class/config-generate/broker.class.php
- www/class/config-generate/engine.class.php
Add a gRPC port for Centreon Engine & Centreon Broker during generation of configuration
1. Generate configuration
2. Must see in centengine.cfg
`grpc_port=(50000 + <engine_configuration_id>)`
3. Must see in <broker_conf_name>.json:
```
"grpc": {
"port": 51002
}
```
> enh(generation): add grpc port in generation for engine & broker

- www/api/class/centreon_metric.class.php
Add new method to list only metrics name from a selected hostId-serviceId couple.
Needed for Anomaly Detection
> enh(api): add new method to list only metrics name from a selected svc

- www/front_src/src/components/hostMenu/index.js
This PR replace 'Critical' label by 'Down' in Top Counter Hosts. 
- Click on Toggle icon inside Top Counter Host
- 'Down' label should replace 'Critical' label
> fix(UI): Wrong label in Top Counter Host (Critical instead of Down)

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.0-beta.1.php
In Centreon Broker Storage (Perfdata Generator (Centreon Storage) output type) configuration page, add an entry for the connections_count variable.
add broker Perfdata Generator (Centreon Storage) output type
> enh(broker) add countConnections for storage output

- www/install/createTables.sql
- www/install/sql/centreon/Update-DB-20.04.0-beta.1.sql
There are a lot of requests ( UPDATE `ods_view_details` SET `rnd_color` = '#99ff00' WHERE `index_id` = '1005229' for instance) that consume a lot of database CPU. 
Indeed, it's because there is no index on this column.
> Add missing index on ods_view_details.index_id

- src/Centreon/Domain/Monitoring/Entity/AckEventObject.php
- src/Centreon/Domain/Monitoring/Entity/DowntimeEventObject.php
- src/Centreon/Infrastructure/Acknowledgement/AcknowledgementRepositoryRDB.php
- src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
- src/Centreon/Infrastructure/Monitoring/TimelineRepositoryRDB.php
the property author_id is empty in the following APIs:
- `/centreon/api/beta/monitoring/hosts/14`
- `/centreon/api/beta/monitoring/hosts/14/timeline`
- `/centreon/api/beta/monitoring/hosts/14/services/19`
- `/centreon/api/beta/monitoring/hosts/14/services/19/timeline`
**Fixes** MON-5105
> fix(api): author_id not filled in timeline endpoint

- src/Centreon/Application/Controller/MonitoringResourceController.php
- src/Centreon/Domain/Monitoring/Interfaces/ResourceRepositoryInterface.php
- src/Centreon/Domain/Monitoring/Interfaces/ResourceServiceInterface.php
- src/Centreon/Domain/Monitoring/ResourceService.php
- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
performance_graph_endpoint and status_graph_endpoint are always defined, even when no graph data are available. 
The User should not be able to display a graph when no data is there to be displayed. Since the Frontend only has the endpoint at first and needs to query the data before checking its content, it’s more efficient to prevent from getting any endpoint from the backend instead. 
**Fixes** MON-5128
> feat(api): do not define status_graph_endpoint and performance_graph_endpoint whenever graph data are empty

- www/include/monitoring/objectDetails/serviceDetails.php
Hi,
One may intentionally disable graphs for one or more services, or for its whole installation, switching of RRDs processing.
This then leads to an empty "_There's no data_" graphs in the _Services Status Details_ pages, which is useless and can (well does) confuse users.
Let's then get rid of these empty graphs when there's no data (from `data_bin`) to plot.
Fixes : N/A (no issue has been opened for this, I directly submitted the corresponding PR)
Well, hard to tell, between the 2 followings :
Disable RRD processing (be sure then your `data_bin` table is empty), or at least remove graphs / empty `data_bin` table for a service, and verify, in the _Services Status Details_ pages, that the following empty graph does not show up :
Thank you …
> enh(UI): Hide empty graphs from service details

- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Pending host status brokes events view listing
**Fixes** MON-5132
Check events view listing with a pending host
> fix(api): return properly pending hosts

- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
the parameters that are passed in SQL query are switched in ResourceRepositoryRDB::getListOfResourcesWithGraphData
**Fixes** MON-5128
> fix(api): the SQL parameter of are switched

- config/packages/serializer/Centreon/Monitoring.Model.ResourceDetailsHost.yml
- config/packages/serializer/Centreon/Monitoring.Model.ResourceDetailsService.yml
- config/packages/serializer/Centreon/Monitoring.Resource.yml
- src/Centreon/Domain/Monitoring/Model/ResourceDetailsService.php
- src/Centreon/Domain/Monitoring/Model/ResourceDetailsTrait.php
- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
the properties parent and severity_code are not loaded correctly in Resource details endpoints (http://localhost/centreon/api/beta/monitoring/resources/hosts/14/services/19)
**Fixes** MON-5071
> fix(api): improve the parent object of Resource details endpoints and add data for severity_code

- src/Centreon/Domain/Monitoring/ResourceFilter.php
Pending status filter was not working for hosts in pending status.
- Get a host in pending status
- Display the Event View page and filter on pending status
- Services and hosts in pending statuses should be listed
> fix(ResourceFilter): pending mapping code incorrect for host object

- www/install/sql/centreon/Update-DB-20.04.0-beta.1.sql
radio button in broker form disappears
check logger in borker configuration : Configuration  >  Pollers  >  Broker configuration
> fix(sql) resolve broker form radio button dependencies

- src/Security/ContactBySession.php
When client connects via session (api request through react), they always got all roles, no matter if user was admin or not. This PR enables acl role check.
**Fixes** # MON 5102
Try to acknowledge a resource without having the needed role.
> Mon 5102 fix acl for apiv2

- www/include/core/footer/footerPart.php
- www/include/core/pathway/pathway.php
when we have a page with the parent page that on react the breadcrumb doesn't cover this case and the user is redirected to the page as `/centreon/main.php?p=626`
example of a page with react parent is `/centreon/main.php?p=62606` (Configuration  >  Business Activity  >  Indicators)
**Fixes** BAM-950
> fix(ui): Breadcrumb on "Legacy" BAM conf pages leads to wrong link

- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Remove limit 1 on query for getting list of resources with metrics.
**Fixes** # MON-5146
Check the resources listing page (unified view) and see that all services with graph data display icon for graph.
> fix(api): return properly all services that have a graph

- doc/en/installation/index.rst
- doc/fr/installation/index.rst
- unattended.sh
Use 19.10.x unattended.sh in 19.10.x documentation.
This PR also backports a fix from the master in a separate commit.
Use unattended installation instruction from the documentation. Install should go smoothly.
> Use 19.10 unattended in doc

- config/routes/centreon.yaml
- doc/en/administration_guide/ui_access.rst
- doc/fr/administration_guide/ui_access.rst
- libinstall/CentWeb.sh
- libinstall/functions
- src/EventSubscriber/CentreonEventSubscriber.php
- www/front_src/src/Resources/ApiNotFoundMessage.tsx
- www/front_src/src/Resources/index.tsx
- www/front_src/src/Resources/translatedLabels.ts
- www/front_src/src/store/index.js
- www/index.php
- Manage every kind of base URI (/centreon, /monitoring, /, /monitoring/centreon ...)
- Display error message with documentation link when apache API configuration is not good
**Fixes** MON-4844
- Remove API configuration section in apache configuration
- Check events view error message (snackbar)
- Update centreon base URI and check centreon web is working properly
> fix(ui/api): manage every kind of centreon base URI

- www/install/steps/templates/step8.tpl
The issue here was that when only modules or widgets were selected the `Object.values` function threw an exeption. We need to check that the data['modules'] and data['widgets'] aren't undefined before processing the code.
- Install first a module only -> Should work and others checkboxes can be clickable
- Install then a widget only -> Should work and others checkboxes can be clickable
- Install everything -> should work and next button should appear
> fix(install): issue when only modules or widgets selected

- www/class/config-generate-remote/Engine.php
_nagios_id_ was missing from _cfg_nagios_ causing inconsistency between _nagios_server_ and _cfg_nagios_ tables, impacting Engine statistics collection.
Add _cfg_file_ for consistency.
On a Remote Server after config export, following query should give a result:
`SELECT id, nagiostats_bin, cfg_dir, cfg_file FROM cfg_nagios JOIN nagios_server WHERE ns_activate = '1' AND nagios_id = id;`
> fix(config): add missing fields of engine conf in remote export

- www/front_src/src/Resources/columns/index.tsx
Fix order by duration in events view
**Fixes** MON-5199
Try to order events view by duration
> fix(ui): allow to order events view by duration

- features/bootstrap/AutologinOptionsContext.php
- www/class/centreonAuth.class.php
- www/include/Administration/myAccount/formMyAccount.php
- www/include/common/common-Func.php
- www/include/core/header/header.php
in this PR are fixed two issues
- after the login redirect to react page if selected as the default page
- fix the default page drop-down
**Fixes** MON-5149
> fix(base): Can't use the new event view as my default page (ACL manageable?)

- src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
According to the order of the data in the database, the searched parameter was not the right one.
> fix(bug): Fixed the query preventing the retrieval of the right parameter.

- www/api/class/centreon_topcounter.class.php
- www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
- www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
- www/front_src/src/Resources/models.ts
- www/front_src/src/components/clock/index.js
Take into account user timezone in downtime popin
/!\ this does not fix the table columns which do not use timezone
note : did not find a way to unit test timezone in popin
**Fixes** MON-5122
- Set a timezone to the user
- Add a downtime to a resource and check that dates and times take into account user timezone
> fix(ui): use timezone in downtime popin

- package-lock.json
- package.json
- www/front_src/src/Resources/Details/Body/tabs/Details/DetailsCard/cards.tsx
- www/front_src/src/Resources/Details/Body/tabs/Details/DetailsCard/index.tsx
- www/front_src/src/Resources/Details/Body/tabs/Details/ExpandableCard.tsx
- www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
- www/front_src/src/Resources/Details/index.test.tsx
- www/front_src/src/Resources/Details/index.tsx
- www/front_src/src/Resources/Details/models.ts
- www/front_src/src/Resources/translatedLabels.ts
This PR makes the following fixes:
-  Show flapping card only when flapping is defined / show 'Yes' label when value is true, 'N/A' otherwise
- Fix command line not showing the correct value, and add a copy button. The card is not shown if command line value is not defined
- Reduce the font sizes of cards content
> enh(ui): Fixes to details panel

- config/Modules/Centreon.yaml
The HostConfigurationService must be defined on public.
> fix(symfony): Configure the service HostConfigurationService in public

- config/packages/serializer/Centreon/Monitoring.Host.yml
- src/Centreon/Domain/Monitoring/Host.php
In centreon_storage timezone is listed as ":Europe/Paris". The semicolon is required for Engine to work properly, so I added a new method to return the cleaned string, because React FE needs it without the symbol.
**Fixes** # MON-5205
Check host detail API to see the returned string for 'timezone' property.
> fix(api): update hosts to return sanitized timezone string

- www/front_src/src/Resources/Filter/index.tsx
**Fixes** MON-5212
Check filter collapse in events view
> enh(ui): move filter collapse icon to the left

- www/front_src/src/Resources/Filter/index.tsx
- www/front_src/src/Resources/SearchHelpTooltip.tsx
- www/front_src/src/Resources/columns/State/index.tsx
- www/front_src/src/Resources/index.test.tsx
- www/front_src/src/Resources/translatedLabels.ts
Improve search help tooltip in events view : 
- stay persistent, until the close button is clicked
- add close icon button
- set background to white
- some minor improvements to avoid unneccessary rendering (remove arrow functions)
**Fixes** MON-5211
Check help tooltip in events view
> enh(ui): improve search help tooltip in events view

- www/front_src/src/Resources/Filter/index.tsx
toggle events view panel only on icon click
**Fixes** MON-5243
Check that event views filter is toggled only when you click on expand icon
> enh(ui): toggle events view panel only on icon click

- www/front_src/src/Resources/index.test.tsx
- www/front_src/src/Resources/index.tsx
Use last value of search field when a filter triggers a listing search
**Fixes** MON-5228
- Type something in events view search field without clicking on search button (and without pressing enter key)
- Change another filter (eg: "All" instead of "Unhandled Problems"
- Check the listing take into account search field
> fix(ui): use last value of search field when a filter triggers a listing search

- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
fit in the cases when in the search criteria are joined by OR/AND operator from different subqueries in the Resource list endpoint
**Fixes**  MON-5207
> fix(api): improve the filtering in subqueries of Resource list endpoint

- www/front_src/src/components/hostMenu/index.js
- www/front_src/src/components/serviceStatusMenu/index.js
Add missing translations for "hosts" and "services"
Change lang of Centreon and check that translations are done for those 2 strings
> fix(header): Add missing translations for hosts and services

- www/front_src/src/components/hostMenu/index.js
- www/front_src/src/components/serviceStatusMenu/index.js
The indicator had disappeared from the top counter in the latest version.
This PR is here to restore it.
- Add a passive service/host
- Do not check it yet so that its status stays pending
- The blue lights should be displayed in the top counter next the host/service icon
> fix(ui): restore pending blue light for host and service

- unattended.sh
As pointed out in #8600, documentation links in unattended.sh are no longer correct. This PR updates documentation links in unattended.sh.
Run unattended.sh. All documentation links printed should be correct and related to the new documentation.
> Update documentation links in unattended.sh.

- www/class/config-generate/broker.class.php
Fix Centreon Broker null lua_parameters generation
```
(...)
{
"name": "forward-to-anomaly-detection",
"path": "/usr/share/centreon-broker/lua/centreon-anomaly-detection.lua",
"type": "lua",
"lua_parameter": [
{
"type": "number",
"name": "max_queue_size",
"value": "100"
}
]
},
{
"lua_parameter": null
}
(...)
```
> fix(generation): correct broker empty lua parameters generation

- www/front_src/src/Resources/columns/State/DetailsTable/Acknowledgement.tsx
- www/front_src/src/Resources/columns/State/DetailsTable/Downtime.tsx
- www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
> fix(ui): Fix column widths for ACK and DT Details tables

- www/include/configuration/configServers/DB-Func.php
- www/include/configuration/configServers/formServers.php
This PR fix a bug where multiples Poller could be define as Default Poller.
1 - the value binded while updating has been corrected.
2 - create a new function to handle case where no Pollers was set to Default.
**Fixes** # MON-5260
- Set a configuration with multiples Remote Servers, Distant Pollers. 
- Only one poller should be by default. 
- Set another poller as default , it should be the only as default.
- Set this same poller to Default Poller  "No"
-  Your local poller should be the Default Poller.
> fix(poller): correctly bindValue and define local poller as default

- package-lock.json
This updates centreon-ui, in order to remove the TopFilter white background.
> chore(npm): Update package-lock

- www/front_src/src/route-components/legacyRoute/index.js
Since the footer has not a fixed position anymore, the manual margin added to the legacy page creates a gap at the bottom and needs to be removed. 
**Before the change**:
**After the change**
> fix(ui): Remove legacy pages bottom margin

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/install/step_upgrade/step3.php
- www/install/step_upgrade/step4.php
During the upgrade process we will now use the release notes that will be written in the new documentation.
The timeout on the button has been also dicreased from 10s to 3s
**Before**
**After**
* Upgrade to latest 20.04.x from 19.10.x for example
* New step 3 should be displayed
> enh(upgrade): externalize release note documentation during upgrade

- www/api/class/centreon_topcounter.class.php
Get notice error in centreon-error.log (and also a wrong information in poller top counters)
You need to get latency on your pollers and if you connect with an admin, you'll get notices.
> MON-5234: fix unitialized values

- www/install/step_upgrade/step3.php
Final URL to release note updated
- Upgrade from 19.10.x to 20.04.0
- Step 3 of the upgrade should display a new message with a link to the release note on the new documentation
> fix(upgrade): use the final URL for the release notes

- www/install/step_upgrade/step4.php
Fix PHP warning on step4 upgrade
```
[16-Apr-2020 23:41:10 Europe/Paris] PHP Warning: Use of undefined constant _CENTREON_PATH_ - assumed '_CENTREON_PATH_' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/install/step_upgrade/step4.php on line 84
```
- Upgrade from version x to 20.04.0
- No PHP warning should be printed for step4 in the logs
> fix(upgrade): fix PHP warning on step4

- src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
- src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
- src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
- src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
Adding a notification method in case of configuration change
> enh(poller): Adding a notification method in case of configuration change

- www/include/core/header/header.php
fix default page after login when non admin user is not allowed to access to it
**Fixes** MON-5329
> fix(acl): fix default page when user cannot access to it

- www/class/centreonACL.class.php
- www/include/configuration/configObject/host/DB-Func.php
Correct the broken queries when all duplication names are already used.
**Fixes** # (MON-5324)
Duplicate a host. Then duplicate a second time the same host. No blank page should be displayed and the list of host should stay the same.
No stack trace should be thrown to the PHP log... nor the SQL
> fix host duplication when strict mode is enabled

- www/front_src/src/route-components/legacyRoute/index.js
This removes the gap in legacy pages when displayed in fullscreen mode. It also removes the now deprecated resize handler.
> fix(ui): Fix bottom gap in fullscreen mode

- config/packages/serializer/Centreon/Monitoring.ResourceSeverity.yml
- doc/API/centreon-api-v2.yaml
- src/Centreon/Domain/Monitoring/ResourceSeverity.php
- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
Avoid to get severity url, which is useless for events view page
**Fixes** MON-5365
> fix(api): do not get useless severity url

- www/front_src/src/Resources/columns/index.tsx
This PR prevents the resource name and parent resource name columns from wrapping into multiple lines.
This also means that the information column will now shrink in case of longer resource / parent names.
**Before the fix**
**After the fix**
> enh(ui): Improve resource name and parent resource name display in Event view page

- .gitignore
- www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
- www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
- www/front_src/src/Resources/Actions/Resource/index.tsx
This PR makes sure that the Acknowledge and Downtime dialogs are mounted only when they show up, to avoid unnecessary renders, as well as outdated current date in the Downtime case.  
In the event view page: Make sure the Downtime dialog always shows the current start date, even if the page haven't been refreshed for a while. Also make sure that the Acknowledge dialog work as before
> fix(ui): Mount Event view Acknowledge and Downtime components only when necessary 

- babel.config.js
- package-lock.json
- package.json
- webpack.config.dev.js
- webpack.config.js
- www/front_src/src/App.tsx
This PR introduces the webpack-dev-server with HMR and react-hot-loader. This improves greatly the development workflow by reloading modules on the fly when something changes instead of having to reload the whole page.
HMR is not supported for external modules yet as it's not compatible with System js at the moment. We might need to wait for webpack 5 to be able to build external ES modules or give https://github.com/alexisvincent/systemjs-hot-reloader a try
**This PR should be merged after final 20.04 build**
> chore(dev): Setup webpack-dev-server with HMR

- setupTest.js
This prevents the build from failing because of jest timeouts, preventing others from being blocked in their development. 
This fix will last until some further investigation has been done and fixes are made to improve test performance.
> fix(ci): Increase temporarily jest timeout

- www/class/centreonServicegroups.class.php
> MON-5112: fix select2 service templates linked to a servicegroup

- www/install/php/Update-20.04.1.php
- www/install/steps/process/configFileSetup.php
- www/install/var/databaseTemplate.yaml
Escape doubles quotes and backslashes to keep db password consistency.
For upgrade and new installations
**Fixes** # (MON-5391)
On the DB :
Create a user using a password with special characters and at least one double quote.
Grant privileges to this user
On a terminal : 
Modify the /etc/centreon/centreon.conf.php file using this user data.
Upgrade your platform and check the /etc/centreon/config.d/10-database.yaml.new
> enh: escape specific characters from database password

- www/include/monitoring/status/Common/commonJS.php
When adding service templates in service groups, and not service directly, non-admin user will not be able to see them in Status Details > Service page.
**Fixes** # MON-5118
- Create a service template,
- Create a host template,
- Link the service template with the host template,
- Create a service group,
- Link the host/service templates couple to the service group,
- Create a user,
- Create ACL for this user allowing it to see all service groups and everything else,
- Create a host/service couple that uses the service template,
- Push config,
- Logging with user,
- You will not see the service group even though you can see them all and it is pushed to Engine
> fix(monitoring): change SQL Request to get ServiceGroups as non-admin user

- src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
- www/class/centreon-clapi/centreonInstance.class.php
- www/include/configuration/configServers/DB-Func.php
Check if FILTER_VALIDATE_DOMAIN is a valid FILTER_FLAG_HOSTNAME
**Fixes** #8456
> fix(security): correct PR #8456

- lib/perl/centreon/script/centreontrapd.pm
Fix https://github.com/centreon/centreon/issues/8237
Refs MON-5296
Launch centreontrapd and in the log file, you should get an error message. Patch and launch it again: the message would be visible only in info severity.
> Fix #8237: centreontrapd messages from error to info

- www/front_src/src/Resources/Filter/index.tsx
* Do not change background color of filter panel when search field is focused
* Remove useless styling (collapseWrapper)
**Fixes** MON-5154
* Click on search field in events view
* Check background of filter panel does not change
> fix(ui): do not display filter background when search field is focused

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/front_src/src/Resources/SearchHelpTooltip.tsx
- www/front_src/src/Resources/translatedLabels.ts
**Fixes** MON-5328
Check search tooltip in events view page
> enh(ui): display link to regex101 in search tooltip

- www/front_src/src/Resources/Graph/Performance/index.tsx
- www/front_src/src/Resources/Graph/Performance/timeSeries.ts
This corrects the legend name in the chart tooltip:
- Open a performance chart
- Hover the time series
- The tooltip should display the data using the same name as the legend
> enh(ui): Use legend name in performance chart tooltip

- src/Centreon/Domain/Engine/EngineService.php
Avoid check latency when a check is scheduled from events view
**Fixes** MON-5427
* Go to events view page
* schedule check on a host / service
* check latency in details panel
> fix(engine): fix schedule check latency

- www/include/common/common-Func.php
fix default page when user is already logged in
**Fixes** MON-5369
* Add a default page to a user
* Login with the user (==> check the user is properly redirected)
* Refresh centreon base uri (==> check the user is properly redirected)
> fix(ui): fix default page when user is already logged in

- src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
- src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerServiceInterface.php
- src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
- src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
Added the possibility to search for a monitoring server by its id
> enh(api): Added the possibility to search for a monitoring server by its id

- www/include/monitoring/acknowlegement/xml/broker/makeXMLForAck.php
- www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
remove error in the logs when the user alter the http request with unconsistent data : 
```
==> /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log <==
[06-May-2020 16:31:06 Europe/Paris] PHP Notice: Undefined variable: service_id in /usr/share/centreon/www/include/monitoring/acknowlegement/xml/broker/makeXMLForAck.php on line 88
[06-May-2020 16:31:06 Europe/Paris] PHP Notice: Undefined variable: service_id in /usr/share/centreon/www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php on line 90
[06-May-2020 16:31:06 Europe/Paris] PHP Notice: Undefined variable: stmt in /usr/share/centreon/www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php on line 119
[06-May-2020 16:31:06 Europe/Paris] PHP Fatal error: Uncaught Error: Call to a member function fetch() on null in …
```
> fix: undefined variable and avoid PDO exception on altered requests

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.2.php
Add to the timezone list the Yangon city from Myanmar
**Fixes** # (MON-5481)
> enh(BE): add Asia/Yangon to the timezone list

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.2.php
Correct timezone format to stay consistent to data injected to the DB
**Fixes** # (MON-5481)
> enh(BE): modify timezone format

- www/class/centreonAuth.LDAP.class.php
In a scenario where LDAP is configured and 'Store LDAP password' is set, Centreon should be able to authenticate an user if the connection with the LDAP server fails and the password has been previously stored. This fallback from the LDAP to local authentication should be automatic. Nowadays, the authentication fails instead.
-Go to Administration  >  Parameters  >  LDAP
-Create your LDAP configuration and select ALL the following options:
-Enable LDAP authentication: Yes
-Store LDAP password: Yes
-Auto import users: Yes
-Save the LDAP configuration
-Login to Centreon using an LDAP user that has not logged in before
-Logout
-Go to the database and confirm that the user account has been imported and password saved (probably, user and …
>  fix(ldap) fix authentication fallback to use local

- www/include/common/javascript/datepicker/localizedDatepicker.js
With last modifications, a downtime end date can be set before the start date.
- check the end date consistency
- modify the end date and time,using the start date, time and the chosen duration
**Fixes** # (MON-3935)
> fix(DT): replace end date when set in the past

- www/include/configuration/configGenerate/formGenerateFiles.php
- www/include/configuration/configGenerateTraps/formGenerateTraps.php
Cannot generate trap or configuration for non allowed users.
Use a non admin users and doesn't provide actions to generate traps and config. It cannot generate anymore.
> MON-3082: cannot generate trap or configuration for non allowed users

- www/include/Administration/corePerformance/nagiosStats.html
- www/include/monitoring/objectDetails/template/hostDetails.ihtml
- www/include/monitoring/status/Services/templates/service.ihtml
- www/include/views/graphs/graph-periods.html
- www/include/views/graphs/graph-split.html
- www/include/views/graphs/graphs.html
isSameOrAfter() method is not supported on momentJS 2.9.0. The host and services status pages do not support this method and need to use the latest momentJS library used in Centreon (2.21.0)
Notice : The lib 2.21.0 and 2.9.0 are already used and available in Centreon here : https://github.com/centreon/centreon/tree/master/www/include/common/javascript
Warning : Do not delete the momentJS 2.9.0 lib as it is still used by BAM
**Fixes** # (MON-3935)
> fix(lib): use moment 2.21 instead of 2.9.0

- features/AutologinOptions.feature
- features/bootstrap/AutologinOptionsContext.php
- www/include/common/common-Func.php
Fix user default page when default page use options
**Fixes** MON-5369
Check following user default page :
administration > parameters > centreon ui
> fix(ui): fix user default page with options

- www/class/centreon-clapi/centreon.Config.Poller.class.php
- www/class/centreon-clapi/centreonACL.class.php
- www/class/centreon-clapi/centreonContact.class.php
- www/class/centreon-clapi/centreonHost.class.php
- www/class/centreon-clapi/centreonHostGroupService.class.php
- www/class/centreon-clapi/centreonManufacturer.class.php
- www/class/centreon-clapi/centreonService.class.php
- www/class/centreon-clapi/centreonServiceTemplate.class.php
- www/class/centreon-clapi/centreonSeverityAbstract.class.php
- www/class/centreon-clapi/centreonUtils.class.php
Line 21776 : Object already exists
PHP Fatal error: Uncaught Exception: SQLSTATE[HY000] [1040] Too many connections in /usr/share/centreon/www/class/centreonDB.class.php:163
Import clapi  export (centreon -u user -p password -i ) with many lines
> fix(clapi) use same db connection instance

- www/include/eventLogs/xml/data.php
Convert the num, limit, and period parameters to int. Sanitize them and call
intval on them, when performing the XML export on the event logs page.
These parameters are certainly meant to be numeric, since we do calculations
with them later on, such as this:
$limitReq = " LIMIT " . $num * $limit . ", " . $limit;
Casting them to int prevents the possibility for SQL injection in the line
above. Additionally, on line 656 we loop over values derived from $num, and
that can lead to an infinite loop if $num is not numeric.
This change causes no functional changes to the event logs XML export. When
calling this page with non-numeric values for num, limit, or period, the
default options are used instead.
fixe (MON-5477)
> enh(secu): sanitize and cast parameters to int

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/include/monitoring/objectDetails/template/hostDetails.ihtml
Fix an incorrect usage of the english word "information" which is uncountable (can never be used as a plural form)
> fix(typo): incorrect tab name 'Host Informations'

- www/include/configuration/configObject/command/minHelpCommand.php
Sanitize command name from http request alterations.
Remove characters used to alter this feature, like bash "encoded" space
**Fixes** # (MON-5448) - reported by : TheCyberGeek
Please contact me
> fix(secu): avoid RCE using command helper

- www/class/centreonMedia.class.php
As old plugin packs try to insert media in the "/usr/share/nagios/html/images/logo" while this folder isn't created anymore on fresh installs; we need to recusively create the path to the data to save
```
[20-May-2020 20:11:41 Europe/Paris] PHP Warning:  mkdir(): No such file or directory in /usr/share/centreon/www/class/centreonMedia.class.php on line 187
[20-May-2020 20:11:44 Europe/Paris] PHP Warning:  mkdir(): No such file or directory in /usr/share/centreon/www/class/centreonMedia.class.php on line 187
[20-May-2020 20:11:44 Europe/Paris] PHP Warning:  mkdir(): No such file or directory in /usr/share/centreon/www/class/centreonMedia.class.php on line 187
[20-May-2020 20:11:44 Europe/Paris] PHP Warning:  mkdir(): No such file or directory in …
```
> fix: create media folder when inserting an old plugin

- www/class/centreonRestHttp.class.php
Do not use hardcoded tcp:// scheme before the proxy URL. Leave configuration of the scheme to the user.
Specify a proxy in a distribution using an up-to-date (7.52+) version of curl (CentOS 8 for example). Without this fix, it should not work.
> Do not use hardcoded tcp:// scheme when using proxy.

- www/include/configuration/configServers/formServers.php
Function isValidIpAddress was present in www/include/configuration/configServers/DB-Funct.php but not used in www/include/configuration/configServers/formServers.php
> fix(security): add missing IP validation in server form

- src/Centreon/Application/Controller/MonitoringResourceController.php
- src/Centreon/Domain/Monitoring/MonitoringService.php
In the new event view, when we try to hide the password in the command line and an error occurs, a popup message appears with an error instead of displaying an error message in the Command section.
> fix(api): Avoid any exceptions by replacing command line with the error message

- package-lock.json
- package.json
- www/front_src/src/Resources/Graph/Performance/Lines.tsx
- www/front_src/src/Resources/Graph/Performance/index.tsx
This enhances the performance graph display by formatting the unit values (especially ones that are < 0) with more precision. It also adds some transparency to the legend tooltip in order to be able to have some visibility over the graph while looking at the detailed values.
Before:
After:
> enh(ui): Enhance graph unit formatting and Tooltip display in Event view

- www/front_src/src/Resources/Details/Body/tabs/Details/StateCard.tsx
- www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
- www/front_src/src/Resources/Details/index.test.tsx
This displays the full comments of both Downtime and Acknowledgement in the details panel:
- Go to the events view page
- Set a downtime and an acknowledgement
- Open the corresponding details panel
Expected result: the full comments are displayed
> feat(ui): Add Downtime and Acknowledge comments in Events view details panel

- www/front_src/src/Resources/ActionButton.tsx
- www/front_src/src/Resources/Actions/index.test.tsx
This prevents the User with limited ACL on an action to execute it even if the button is disabled. 
- Set a limited ACL for the current User on either acknowledge, downtime or check
- Go to the event view page
- try to click on a resource inline action (single Resource) corresponding to the limited ACL, that should be disabled (either acknowledge, downtime or check) 
Expected result: No action is triggered.
> fix(ui): Prevent disabled actions resulting from limited ACL to be clickable

- www/front_src/src/redux/reducers/refreshReducer.js
This fixes the Host and Service top menus not being displayed. 
The issue was that the interval was being triggered within componentWillReceiveProps. The default value of 10 prevented the method from being called, whenever the received value from the parameter was 10 (including all the values below 10, enforced by the API to be 10).
- Go to Parameters -> Centreon UI
- Set the refresh interval for monitoring to a value of 10 or less than 10
- Save
- Refresh the page
Expected result:
- the Host and Service menus are displayed and the interval is correctly set to the value coming from the parameters.
> Remove initial state for AjaxTimeReloadMonitoring

- www/front_src/src/Resources/Graph/Performance/timeSeries.ts
This fixes the lower limit check so that even if the lower limit is set to 0, graph with only 0 values are displayed anyway:
- Open a performance graph (such as Centreon-ping)
- wait that enough values are available
- Check that a line (for instance Packet-loss for Centreon-ping) is displayed
> fix(ui): Fix lower value display of Event view performance graph 

- config/packages/nelmio_cors.yaml
Avoid security issue when using request.credentials with `include` value
**Fixes** MON-5496
* Login to centreon
* In an other tab, open a file with the following content (by replacing `<ip_address>`) : 
```html
<body>
<script>
fetch("http://<ip_address>/centreon/api/beta/monitoring/resources", {credentials: "include"}).then(response => response.json()).then(function (data) {
document.body.textContent = JSON.stringify(data);
});
</script>
```
* Check resource listing is not returned
> fix(sec): set Access-Control-Allow-Credentials response header to false

- cron/centreon-backup-mysql.sh
The backup script fail when the new temporary partition is not an 'xfs' partition.
**Fixes** # (https://github.com/centreon/centreon/issues/8635)
Launch manually the script located in /usr/share/centreon/cron/centreon-backup-mysql.sh
And check that the tables are correctly displayed and backuped
> fix(backup): keep mount option only for xfs partition type

- lib/perl/centreon/script/centreon_trap_send.pm
When the script was using, the default value from the help manual was used :
```
/usr/share/centreon/bin/centreon_trap_send -d 127.0.0.1 -c public -o 1.3.6.1.4.1.39009.1.2 -a '.1.3.6.1.4.1.39009.3:OCTET_STRING:HOST=$HOSTNAME$,IP=$HOSTADDRESS$,STATUS=$HOSTSTATE$,LOCATION=$HOSTALIAS$'
[root@archimede-central centreontrapd]# cat \#centreon-trap-1591279342617995
1591279342
localhost
UDP: [127.0.0.1]:55318->[127.0.0.1]:162
DISMAN-EVENT-MIB::sysUpTimeInstance 184:4:13:13.42
SNMPv2-MIB::snmpTrapOID.0 SNMPv2-SMI::enterprises.39009.1.2
SNMPv2-SMI::enterprises.12182.2.1 "Test \"20\""
SNMPv2-SMI::enterprises.12182.2.1 10
SNMPv2-SMI::enterprises.12182.2.1 100
SNMPv2-SMI::enterprises.39009.3 "HOST=$HOSTNAME$,IP=$HOSTADDRESS$,STATUS=$HOSTSTATE$,LOCATION=$HOSTALIAS$"
```
As you can seen I still have the …
> fix(trap): remove default value when options configured

- package-lock.json
- www/front_src/src/Resources/Actions/Resource/Acknowledge/Dialog.tsx
- www/front_src/src/Resources/Actions/Resource/Downtime/Dialog.tsx
- www/front_src/src/Resources/Actions/Resource/aclQuery.ts
- www/front_src/src/Resources/Actions/index.test.tsx
Disable "applies to services checkbox when action is not allowed on services : 
- downtime dialog
- acknowledgement dialog
I've also reduced size of checkboxes (small)
**Fixes** MON-5150
* log in with a user which cannot acknowledge and set downtime on services
* go to events view and check a host in listing
* try to acknowledge or set a downtime using top action buttons
* check that checkbox which apply action on services is not checked and disabled
> fix(ui): disable service checkbox when not allowed

- www/class/config-generate/meta_command.class.php
Change embedded `check_meta_host_alive` command line to use centreon-plugins dummy check.
Current command line might prevent notifications to be sent if plugin is not present and host considered as down.
Fixes: #7728
Refs: MON-5446
* Add a meta service with configuration that can trigger notifications,
* Look at notifications in Engine's logs.
> fix(config): change check_meta_host_alive command line to use dummy check

- www/include/monitoring/status/Common/setHistory.php
Sanitize inputs saved in service grid history
**Fixes** # (MON-5497)
> fix(secu): sanitize service grid history inputs

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Domain/Proxy/Proxy.php
- tests/php/Centreon/Domain/Proxy/ProxyTest.php
Fixed the bad serialization of proxy
When no properties have been defined for the proxy, serialization only returns the protocol instead of returning an empty value.
> fix(proxy): Fix bad serialization of proxy

- src/Centreon/Domain/Acknowledgement/AcknowledgementService.php
- src/Centreon/Domain/Monitoring/Interfaces/MonitoringRepositoryInterface.php
- src/Centreon/Domain/Monitoring/MonitoringService.php
- src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
Fix acknowledgement from events view when "Acknowledge services attached to host" parameter is checked.
Previously only 10 first services linked to the host were acknowledged
**Fixes** MON-5596
* Monitoring a host with 11 non-ok services
* in events view page, acknowledge the host with "Acknowledge services attached to host" parameter
* ==> check all services linked to the host are acknowledged
> fix(api): acknowledge more than 10 first services

- www/include/configuration/configServers/popup/popup.php
In menu Administration > Configuration > Pollers, clicking on the "View gorgone config for this poller " (little eye) button will display an almost empty popup with "Bad Poller ID" in it instead of the configuration.
in admin 
1 Go to Administration > Configuration > Pollers
2 Click on button "View gorgone config for this poller"
3 Popup is displayed, but without the configuration
> fix(security) admin access

- www/class/centreonCustomView.class.php
- www/class/centreonWidget.class.php
- www/include/home/customViews/action.php
- Adding menu/action access to the custom view
- Cleaning code
- _POST variable no longer used in method calls (exept for updateWidgetPreferences that might be done later (might be a dangerous move for now))
- Sanitize and filter vars 
Described in the ticket
> security(CustomView): add access rights to CustomViews actions

- www/class/centreonMedia.class.php
On PPM folder creation : 
- Add missing "0" on rights
- Change rights , to be able to create the imported icon files, as 0644 rights are not enough and still results in failures in the logs :
```
[26-Jun-2020 13:18:46 Europe/Paris] PHP Warning:  
file_put_contents(/usr/share/centreon//www/img/media//ppm//applications-monitoring-centreon-database-centreon-128-2.png): 
failed to open stream:
Permission denied in /usr/share/centreon/www/class/centreonMedia.class.php on line 44
```
**Fixes** # (MON-5686)
> fix(icon): change ppm folder creation rights

- lib/perl/centreon/reporting/CentreonDownTime.pm
When a downtime is currently running, it breaks reporting calculation : 
Use of uninitialized value in numeric gt (>) at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 93.
**Fixes** MON-5551
* put a downtime which end next year
* rebuild reporting (eventReportBuilder)
> fix(reporting): fix reporting calculation when downtime end time is null

- www/class/centreonCustomView.class.php
The class const variables were not used correctly which prevent actions to be done for a User under ACLS
See the ticket.
> fix(centreonCustomView): use class constant correctly

- www/include/monitoring/objectDetails/xml/hostSendCommand.php
- www/include/monitoring/objectDetails/xml/serviceSendCommand.php
Issue found during the validation of "Secure host/service sendCommand" from object detail.
CentreonUtils class was not loaded which lead to a PHP fatal error
Details for the tests are written down in the JIRA ticket
> fix(sendCommand): centreonUtils class was not loaded

- www/include/views/graphTemplates/formGraphTemplate.php
Wrong variable name used in conditition which prevent from editing and save graph Templates...
See the related JIRA ticket for the tests
> fix(formGraphTemplate): bad variable name used

- lib/perl/centreon/reporting/CentreonAck.pm
- lib/perl/centreon/reporting/CentreonDashboard.pm
- lib/perl/centreon/reporting/CentreonDownTime.pm
- lib/perl/centreon/reporting/CentreonHost.pm
- lib/perl/centreon/reporting/CentreonHostStateEvents.pm
- lib/perl/centreon/reporting/CentreonLog.pm
- lib/perl/centreon/reporting/CentreonProcessStateEvents.pm
- lib/perl/centreon/reporting/CentreonService.pm
- lib/perl/centreon/reporting/CentreonServiceStateEvents.pm
- lib/perl/centreon/script/dashboardBuilder.pm
- lib/perl/centreon/script/eventReportBuilder.pm
* Manage reporting calculation when a host or service is renamed
* Improve performance on reporting calculation
(Use ids instead of names in reporting scripts)
**Fixes** MON-5694
* Create a passive host "host-passive"
* Set host status to down
* Wait two hours
* Rename the host to "host-passive-renamed"
* Wait next day
* Check in reporting that first two hours are displayed in the reporting (not undetermined)
* Other reporting calculation should also be tested (downtime period...)
> fix(reporting): manage reporting calcuation on host/service rename

- package-lock.json
- package.json
Upgrade kind-of dependency to latest version (6.0.3)
@kduret , @bdauria Caution, there's still one package reported as highly vulnerable : 
**Fixes** # (dependabot)
> fix(secu): upgrade kind-of dependency

- www/api/class/centreon_realtime_hosts.class.php
This PR fix an inversion between sortType and order, and add some missing fields in sortType
This PR close https://github.com/centreon/centreon/pull/8769
**Fixes** # MON-5668
Do a GET Request like these:
api.domain.tld/centreon/api/index.php?object=centreon_realtime_hosts&action=list&sortType=id&order=desc
You should have as a response a list of hosts sort by ID ordered by descending values
> fix(apiV1): Correct sortType and order for host in realtime

- www/class/centreonLDAP.class.php
Remove these errors in the ldap.log : 
1 :
```
[03-Jul-2020 17:13:13 Europe/Paris] PHP Warning:  ldap_search(): Partial search results returned: Sizelimit exceeded in /usr/share/centreon/www/class/centreonLDAP.class.php on line 600
[03-Jul-2020 17:13:13 Europe/Paris] PHP Stack trace:
[03-Jul-2020 17:13:13 Europe/Paris] PHP   1. {main}() /usr/share/centreon/www/include/configuration/configObject/contact/ldapsearch.php:0
[03-Jul-2020 17:13:13 Europe/Paris] PHP   2. CentreonLDAP->search() /usr/share/centreon/www/include/configuration/configObject/contact/ldapsearch.php:142
[03-Jul-2020 17:13:13 Europe/Paris] PHP   3. ldap_search() /usr/share/centreon/www/class/centreonLDAP.class.php:600
...
``` 
2 : 
```
[06-Nov-2019 15:10:13 Europe/Paris] PHP Warning:  ldap_get_entries() expects parameter 2 …
```
> fix(chore): remove errors and improve LDAP logs message

- www/class/centreonLDAP.class.php
This makes all attribute names lowercase so that they will always match results returned by `ldap_get_entries`.
**Fixes** #8219
Patch fixing an issue (non-breaking change)
20.04.x (master)
Save a LDAP configuration with attributes containing uppercase attribute names.
I don't think that this will break anything but I might be wrong, please let me know if I need to amend the code.
I didn't touch `user_group` because it is used within a filter and not after a call to `ldap_get_entries`:
https://github.com/centreon/centreon/blob/35c17fbf3eaa97e6fdae9c87d218eeb012e4e0f2/www/class/centreonLDAP.class.php#L485-L486
> Convert LDAP attributes names to lowercase, fixes #8219

- lang/fr_FR.UTF-8/LC_MESSAGES/help.po
- www/include/configuration/configServers/formServers.php
- www/include/configuration/configServers/help.php
Improve the message to use Remote Server as proxy
**Fixes** #8835
Go to the "Configuration > Pollers > Pollers" menu
Click on the contextual help of the "Use the Remote Server as a proxy" field
> enh(config): Improve message to use Remote Server as proxy, fix #8835

- src/Centreon/Domain/MonitoringServer/Interfaces/MonitoringServerRepositoryInterface.php
- src/Centreon/Domain/MonitoringServer/MonitoringServerService.php
- src/Centreon/Infrastructure/MonitoringServer/MonitoringServerRepositoryRDB.php
Fixed method to find the local monitoring server.
Creating two distinct methods for finding monitoring servers to make the code more explicit.
When we try to find the local monitoring server, the first one found may not be activated.
> Fix(monitoring_server): Fixed method to find the local monitoring server

- www/class/centreonCustomView.class.php
Do not delete preferences when a user delete a shared view
**Fixes** MON-553
* Create a view
* Add widgets to it
* Configure your widgets with specific parameters
* Share the view with another user
* Connect with the user
* Import the view
* Delete the view
* Import the view again
==> The widgets in the view don’t have any parameters set
> fix(widget): do not delete preferences when a user delete a shared view

- www/Themes/Centreon-2/style.css
- www/include/eventLogs/xml/data.php
This PR intends to display acknowledgements as it is: an event. Before this PR the line related to the ACK appeared with a 'OK' / UP green badge which relates to a service/host status.
- Have some services, hosts in a non-OK status.
- Put an ACK on each of those ressources
- The ACK related lines in the Monitoring  >  Event Logs page should be displayed with a 'ACK' badge
> enh(logs): display correctly ACK events on eventLogs page

- lib/perl/centreon/script/centFillTrapDB.pm
Check the name of MIB in comment before to use it.
> fix(security): check mib name in comment

- doc/API/centreon-api-v2.yaml
- www/front_src/src/Resources/Details/index.test.tsx
- www/front_src/src/Resources/Details/index.tsx
When the refresh of the resource list is done (manual or automatic) and
the details panel is opened, it will be refreshed at the same time.
Refs : MON-5636
> feat(ui): Refresh the panel when the list is refreshed

- www/api/class/centreon_ldap_synchro.class.php
- www/include/options/session/connected_user.php
This PR fix the Logout User URL on Sessions page.
**Fixes** #4542
> fix(security): use user id instead of session id in session page

- www/include/options/session/connected_user.php
This PR fix an issue where sessid was used to disconnect user instead of using userId
**Fixes** MON-4542
> fix(session): use userId instead of sessionId

- cron/centreon-send-stats.php
- www/class/centreonStatistics.class.php
- www/class/centreonStatsModules.class.php
get statistics of a module even if it fails
**Fixes** MON-5624
Throw an error in a module statistics class, and check if it works
> fix(stats): get stats even if a module fails

- www/include/common/javascript/Timeline/src/main/webapp/api/scripts/painters.js
- www/include/reporting/dashboard/xmlInformations/common-Func.php
This PR aims to display correctly the day displayed in the reporting timeline detail popin.
**/!\ IMPORTANT /!\**
Translation has not been handled since it is not handled for the whole timeline...
**Before**
**After**
- Go to `Reporting  >  Dashboard  >  Host Groups` for example (servicegroups and hosts should be checked too)
- Click on a part of the timeline
- The detailed popin should be displayed and the "Day: date" should be human readable
> fix(dashboard): human readable date for reporting timeline detail popin

- www/class/config-generate/broker.class.php
If the "Configuration > Parameters > Centreon UI > Proxy URL" is only an IP address the parse_url function detect IP as PHP_URL_PATH and not PHP_URL_HOST
> fix(broker): Extract correctly IP adress of a proxy configuration

- www/api/class/centreon_performance_service.class.php
Remove hard coded centreon db name in centreon_performance_service internal API class
> fix(api): remove hard coded centreon db name in performance_service

- www/include/configuration/configObject/service_categories/DB-Func.php
- www/include/configuration/configObject/service_categories/serviceCategories.php
This PR sanitize the differents input for service categories
**Fixes** MON-5642
> fix(service categories): Sanitize inputs

- src/CentreonRemote/Application/Clapi/CentreonRemoteServer.php
If the HTTP default port is not the default one or is the Centreon Central sue HTTPS with not 80 redirection. The enableRemote CLAPI command doesn't work
> fix(remote): use URL list instead of IP list to keep scheme and port

- lib/perl/centreon/script/centFillTrapDB.pm
Unable to import MIBs due to MySQL Strict Mode
**Fixes** #8816
Try to import MIB containing SNMP Traps definition
> fix(snmptraps): Unable to import SNMP traps MIBs, fix #8816

- www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
> fix(event-view): Fix acknowledge form empty comment provoking infinite load

- www/front_src/src/Resources/Graph/Performance/index.tsx
- www/front_src/src/Resources/Graph/Performance/timeSeries.ts
This fixes tick times displayed as "invalid date" whenever a time metric is named "time"
Before:
After:
> fix(event-view): Fix time values displayed as invalid

- www/class/centreonWidget.class.php
small typo there that break the poistioning of the widgets
**Fixes** # (MON-5950)
without this patch, 
- go in the custom view menu
- create a view and add a few widgets
- change their position
- refresh the page, the position of the widget are back to their default position and not the one you configured
with this patch
- repeat above procedure
- widgets should now be where you've decided
> fix(widget) can't change position of widgets

- www/front_src/src/Resources/Graph/Performance/Lines.tsx
- www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.test.ts
- www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
- www/front_src/src/Resources/Graph/Performance/index.tsx
This fixes the display the value of base 2 metrics (1024 bytes) displayed in base 10 (1000 bytes) instead.
> fix(event-view): Fix 1024 base metrics value formatting in performance graph

- lib/perl/centreon/script/nagiosPerfTrace.pm
Add quiet option for SSH on the nagiosPerfTrace script in order to avoid to fill its log file with SSH banners.
Add SSH banner on central and pollers.
Look the content of /var/log/centreon/nagiosPerfTrace.log on the central server (separately of the proper functioning of the script). You'll see all your banners in the log file.
Refs MON-5967
> Quiet SSH for nagiosPerfTrace.pm

- www/front_src/src/Resources/Filter/Edit/index.test.tsx
- www/front_src/src/Resources/Filter/api/adapters.ts
This fixes an error when the search input has never been filled out.
> fix(event-view): Send search as empty string instead of undefined when saving a filter

- www/front_src/src/Resources/Details/index.test.tsx
- www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
This fixes some weird behavior while loading Timeline events and using infinite scroll.
- Select a Resource with more than 10 events
- Select the corresponding Timeline tab in the details panel
- Do some guerilla loading / testing
- Check that the behavior is coherent and the result is always properly loaded
> fix(resources-status): Fix Timeline infinite scroll showing incoherent results

- src/Centreon/Domain/Filter/FilterService.php
- tests/php/Centreon/Domain/Filter/FilterServiceTest.php
- www/front_src/src/Resources/Filter/Edit/index.test.tsx
- www/front_src/src/Resources/Filter/Save/index.test.tsx
- www/front_src/src/Resources/Filter/Save/index.tsx
- www/front_src/src/Resources/Filter/api/index.ts
update filter on save with returned data
it allows to remove linked objects which have been deleted from monitoring (hostgroup and servicegroup)
**Fixes** MON-5758
* Link a hostgroup to a host
* create a filter which use hostgroup
* delete hostgroup and restart poller
* update filter search parameter and save it
==> the hostgroup should be deleted from the filter
> fix(filter): update filter on save with returned data

- www/front_src/src/Resources/Filter/index.test.tsx
- www/front_src/src/Resources/Filter/useFilter.ts
initialize filter criterias when given in url
**Fixes** MON-5216
* search in resource status page using search field
* load events view page using filter parameter : `/centreon/monitoring/resources?filter={"criterias":{"resourceTypes":[]}}`
==> search field should be reset to empty
> fix(filter): initialize filter criterias when given in url

- www/front_src/src/Resources/Details/Header.tsx
> enh(resource-tatus): Change Resource link copy icon

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/front_src/src/Resources/Details/tabs/index.tsx
- www/front_src/src/Resources/Details/useDetails.ts
- www/front_src/src/Resources/Filter/index.test.tsx
- www/front_src/src/Resources/translatedLabels.ts
This prevents the page to blow up if URL query parameters are invalid. 
To test: just set an invalid details parameter in the URL (either wrong resource id / parent id / type / parent type or invalid tab). The page shouldn't blow up. In case of wrong tab: the details tab is displayed instead. In case of wrong resource parameter: the panel is closed and an error message is displayed.  
> enh(resource-status): Make details tab URL query parameters interpretation more robust

- www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
This avoids sending 2 API requests when first loading the timeline.
> fix(resource-status/timeline): trigger selectedTypes reload only when timeline is defined

- www/class/centreonACL.class.php
`[24-Jul-2020 06:39:00 Europe/Paris] PHP Notice:  Undefined offset: 0 in /usr/share/centreon/www/class/centreonACL.class.php on line 510
[24-Jul-2020 06:39:00 Europe/Paris] PHP Stack trace:
[24-Jul-2020 06:39:00 Europe/Paris] PHP   1. {main}() /usr/share/centreon/www/include/monitoring/status/Notifications/notifications.php:0
[24-Jul-2020 06:39:00 Europe/Paris] PHP   2. CentreonXMLBGRequest->__construct($dependencyInjector = *uninitialized*, $session_id = *uninitialized*, $dbNeeds = *uninitialized*, $headerType = *uninitialized*, $debug = *uninitialized*, $compress = *uninitialized*, $fullVersion = *uninitialized*) /usr/share/centreon/www/include/monitoring/status/Notifications/notifications.php:49
[24-Jul-2020 06:39:00 Europe/Paris] PHP   3. CentreonACL->__construct($userId = …
> fix(log): skip empty lvl3 on topology acl

- www/install/php/Update-20.10.0-beta.2.php
Fix variable set. Avoid fatal error and freeze while upgrading 
`PHP Fatal error:  Cannot use [] for reading in /usr/share/centreon/www/install/php/Update-20.10.0-beta.2.php on line 44`
> fix(upgrade): correct typo

- www/front_src/src/Resources/Graph/Performance/Lines.tsx
- www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.test.ts
- www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
- www/front_src/src/Resources/Graph/Performance/index.tsx
manage null values in graph :
* does not display metric in tooltip if value is null
* does not format null values (avoid conversion to 0)
**Fixes** MON-5813
> fix(graph): manage null values

- www/front_src/src/Resources/Filter/index.test.tsx
- www/front_src/src/Resources/Filter/storedFilter.ts
The schema has changed since the first 20.04 release and the filter stored might be irrelevant
> fix(resource-status/Filter): change Filter local storage key to avoid schema incoherence

- config/json_validator/latest/Centreon/PlatformTopology/Register.json
- doc/API/centreon-api-v2.yaml
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Application/Controller/PlatformInformationController.php
- src/Centreon/Application/Controller/PlatformTopologyController.php
- src/Centreon/Domain/Engine/EngineConfiguration.php
- src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
- src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
- src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyServiceInterface.php
- src/Centreon/Domain/PlatformTopology/PlatformTopology.php
- src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
- src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
- src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
- tests/api/features/PlatformTopology.feature
- tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
- tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
Manage the hostname in the payload
The refacto and issue fix have been backported from : 
fix(API): fix register a remote on a central and refacto service (#9091)
**Fixes** # (MON-6093)
> enh(API): manage hostname in topology endpoint

- www/include/Administration/parameters/general/form.ihtml
> fix(openid): fix form missing right braces

- package-lock.json
- package.json
- www/front_src/src/Resources/Listing/useLoadResources/index.ts
This avoids resources being loaded twice and fixes an issue while changing the selected details which loads the previous one. 
> fix(resource-status): Avoid double details refresh and prevents auto refresh from loading the wrong details

- src/Centreon/Domain/PlatformInformation/PlatformInformation.php
- src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
- tests/api/features/PlatformTopology.feature
fix(API): Remove entityDescriptor which block the peer_validation retrieval from DB
fix(API): manage disabled peer_validation and send the request to the central using an https scheme
enh(API): manage proxy options
enh(test): improve platform topology integration test
**Fixes** # (none. But related to MON-5795 using https)
> fix(API): manage disabled https peer_validation

- bin/registerServerTopology.php
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- www/include/Administration/parameters/remote/DB-Func.php
- www/include/Administration/parameters/remote/formRemote.php
Set a default value fort the apiPort in remote server form and while executing the script.
**Fixes** # QA-170
> fix(platformstatus): default apiPort value in remote form

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Domain/PlatformInformation/PlatformInformation.php
When the port is not consistent, the error thrown by the entity was not correctly retrieved in the response, as the entityCreator overrided it
Port consistency check has been moved on the getter instead
eg:  using port = 0
**Fixes** # (QA-170)
> fix(API): correct message thrown on inconsistant port value

- bin/registerServerTopology.php
- www/include/Administration/parameters/remote/formRemote.ihtml
- www/include/Administration/parameters/remote/formRemote.php
If no port is specified in the register script, the port should be set to 443 if the specified url contains an https scheme
Same is required in the Remote access' form
**Fixes** # (MON-6166)
> fix(register): set default value on https

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
enhance thrown message on transport exception when a proxy is set
correct thrown message as error code has been removed
before
after
> enh(API): thrown message on transport exception

- www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
- www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
Fragments seem to create important lags on firefox in the Timeline tabs, so they have been replaced by divs. 
> fix(resource-status/Timeline): replace fragments by divs

- www/front_src/src/Resources/Details/tabs/Timeline/index.tsx
This fixes the timeline events being duplicated when the refresh button is clicked. 
- Have a resource with more than 30 timeline events
- open the corresponding timeline tab in the details panel
- trigger a load cycle by scrolling to the bottom
- click on the refresh button
--> the events shouldn't be duplicated.
> fix(resource-status/Timeline): fix duplicated timeline events

- lib/perl/centreon/common/db.pm
In some case (database disconnect and multiple quotes requests), you can have wrong column updates
It's difficult to test.
> MON-6068: Perl lib db query bad looping parameters

- package.json
to be compatible with old versions of nodejs (<10)
> fix(deps): use proper version of stack-utils

- lib/perl/centreon/script/centreontrapd.pm
Fix  #9044
The special variable ```$o``` can be used. You can try to add it in trap output. The trap OID should be displayed.
> MON-6280: Add a special variable for trap OID

- unattended.sh
Enhance unattended.sh script for Centos 8.
The scripts now checks which version of Centos is running and does what has to be done depending on this version.
Also avoid version number redondances in the script in order to simplify later updates.
Make a fresh install on a Centos 8 machine and check everything is installed as expected.
As a non regression test: do the same from a Centos 7 machine, check everything is ok.
> MON-6228 unattended centos8 support

- www/front_src/src/Resources/Details/tabs/Details/DetailsCard/cards.tsx
- www/front_src/src/Resources/Details/tabs/Details/index.tsx
> enh(resource-status): Make FQDN tile bigger

- www/include/monitoring/status/Common/updateContactParam.php
- www/include/monitoring/status/Common/updateContactParamHostGroups.php
- www/include/monitoring/status/Common/updateContactParamServiceGroups.php
Sanitize instance_id, hostgroups and servicegroups parameters
**Fixes** # (MON-4217)
> fix(secu): sanitize filter's XHR parameters

- libinstall/functions
disable http trace option and prevent from click-jacking in http configuration set by default when user use the sources to install his platform
**Fixes** # (MON-4751 & MON-4750)
> fix(secu): enhance default http configuration when using sources

- config/routes/Centreon/administration/parameters.yaml
- config/routes/Centreon/user.yaml
- doc/API/centreon-api-v2.yaml
- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Application/Controller/Administration/ParametersController.php
- src/Centreon/Application/Controller/UserController.php
- src/Centreon/Domain/Option/OptionService.php
- tests/api/Context/UserParametersContext.php
- tests/api/behat.yml
- tests/api/features/UserParameters.feature
This PR intends to add 2 endpoints
- GET /configuration/users/current/parameters - retrieves information regarding the current user
- GET /administration/parameters - retrieves global informations
**Example of results**
```
For global information
{
"monitoring_default_refresh_interval": "15",
"monitoring_default_downtime_duration": "3600"
}
For user information
{
"name": "centreon centreon",
"alias": "admin",
"email": "centreon@localhost",
"timezone": "Europe/Paris",
"locale": "en_US"
}
```
Can be tested by using those endpoints and check the consistency of the values returned.
> enh(api): user and global parameters endpoints

- src/Centreon/Domain/Monitoring/Comment/CommentService.php
- src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
When trying to add comments using the .../resources/... endpoint for hosts it was not working due to huge typo in variable names causing the issue.
The other issue was that when a resource (host type) was in several accessgroups then the comment was sent n-times.
IT was already fixed for services but not for hosts.
Add comments for host/services resources types using the /resources endpoint with a limited user and admin
- [ x] I have followed the **coding style guidelines** provided by Centreon
> fix(api): add resource comments for host issue fixed

- www/include/configuration/configServers/DB-Func.php
This PR ensure that the Central IP isn't override in platform_topology if submitted IP is 127.0.0.1 while updating the Central informations into the Configurations > Pollers Form.
**Fixes** # MON-6467
Update a Central and leave 127.0.0.1 as IP .
The IP shouldn't be override into centreon.platform_topology
> fix(poller configuration): Don't override Central IP in platform_topology.

- www/include/options/media/images/DB-Func.php
This PR fix an issue where we try to potentially scan a non existent directory
**Fixes** # MON-6479
Upload a single image, you shouldn't see any PHP  Warning logs
> fix(media): check if temporary directory exist

- .github/CODEOWNERS
- bootstrap.php
add codeowners file for following teams : 
- centreon-ci
- centreon-php
- centreon-frontend
It allows to assign reviewers automatically when a pull request is opened
> enh(ci): add codeowners file

- src/Centreon/Application/Controller/AcknowledgementController.php
- src/Centreon/Application/Controller/DowntimeController.php
Remove pagination object in meta data of API response
"meta": {
"page": 1,
"limit": 10,
"search": {},
"sort_by": {},
"total": 2
}
doc already without pagination object
GET on centreon/api/beta/monitoring/downtimes
GET on centreon/api/beta/monitoring/hosts/downtimes
GET on centreon/api/beta/monitoring/services/downtimes
GET on centreon/api/beta/monitoring/acknowledgements
GET on centreon/api/beta/monitoring/hosts/acknowledgements
GET on centreon/api/beta/monitoring/services/acknowledgements
> enh(api) remove pagination object in meta data of DT and ACK API 

- www/class/centreonHost.class.php
- www/include/common/common-Func.php
- www/include/common/templates/cloneMacro.ihtml
- www/include/configuration/configObject/host/formHost.ihtml
- www/include/configuration/configObject/host/formHost.php
- www/include/configuration/configObject/host/host.php
- www/include/configuration/configObject/host_template_model/formHostTemplateModel.php
- www/include/configuration/configObject/host_template_model/hostTemplateModel.php
- www/include/configuration/configObject/service/formService.ihtml
- www/include/configuration/configObject/service/formService.php
- www/include/configuration/configObject/service/serviceByHost.php
- www/include/configuration/configObject/service/serviceByHostGroup.php
- www/include/configuration/configObject/service_template_model/formServiceTemplateModel.php
- www/include/configuration/configObject/service_template_model/serviceTemplateModel.php
Remove the display of the password in HTML file in forms of service, service template, host and host template.
The password type input fields of the macros were displayed in plain text in the HTML file.
> fix(password): Remove the display of the password in HTML file in forms of service, service template, host and host template

- Jenkinsfile
use delta to detect coding style errors
cause sometimes, "new" algorithm detects all previous warnings as new and fails job...
note from jenkins warning ng plugin documentation : 
```
New
Selects the total number of new issues in the current build with respect to the reference build.
New issues will be calculated by a sophisticated algorithm, that tries to track issues from build to build,
even if the source code has been modified.
Note that this algorithm sometimes detects outstanding warnings as new,
e.g., if a source file has been refactored heavily.
```
**Fixes** MON-6419
Check CI
> fix(ci): use delta to detect coding style errors

- Jenkinsfile
Those charts are not used and does not give relevant information now that we have plugins to do the checkstyle (with dedicated pages)
Furthermore it saves space on the build page to remove those charts and it is now lighter when loading the build page
> enh(pipeline): remove display of style trend charts

- www/class/centreonWidget.class.php
- www/include/home/customViews/action.php
Injection was fixed on 2.8.x when renaming a widget title.
This PR intends to do the same but when adding a widget.
Follow instructions provided in the JIRA issue
> fix(customViews): avoid injection when adding a widget

- Jenkinsfile
use discoverGitReferenceBuild instead of manually set reference build
this is needed by new warning ng plugin version
Check CI
> chore(ci): use discoverGitReferenceBuild instead of manually set reference build

- .eslintrc.js
- www/front_src/src/Resources/Listing/columns/Url.tsx
This uses the new URL path from the Listing API response as well as the Notes label if delivered. 
- Configure a Resource to add a Notes URL
- Configure another one to add a Notes URL and a Notes label
- Make sure the first one has a clickable anchor with the Notes URL as title
- Make sure the second one has a clickable anchor with the Notes label as title
-
> [20.10.x] fix(Resource-status/Listing): Use the new URL path

- src/Centreon/Application/Controller/MonitoringResourceController.php
fix check command setter name
`setCommandLine` does not exist on host entity
**Fixes** MON-6204
> fix(sec): fix check command setter name

- unattended.sh
Automize wizard install in the unattended script (optional)
You can try it with this vagrant provisioning config:
```
config.vm.provision "shell",
path: "https://raw.githubusercontent.com/centreon/centreon/unattented-with-install-wizard/unattended.sh",
env: {"ENV_CENTREON_OPERATION" => "install", "ENV_CENTREON_REPO" => "unstable,testing", "ENV_SKIP_WIZARD" => "true"}
```
> Wizarded unattented.sh

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
When UI is in french , "Downtime" is not translated by the good words in Timeline => "Planifier une plage de maintenance" instead of "Plage de maintenance"
Set UI in French and add downtime in resources status , check if in timeline event for downtime transaltio is right.
> fix(ui): Modification for the Downtime translation in Timeline

- www/include/monitoring/status/Notifications/notifications.php
Correct undefined variable in `/var/log/httpd/error_log` : 
```
[Wed Apr 28 07:23:17.497905 2021] [:error] [pid 317] [client 172.17.0.1:33300] PHP Notice:  Undefined variable: centreon in /usr/share/centreon/www/include/monitoring/status/Notifications/notifications.php on line 117, referer: http://172.17.0.2/centreon/main.php
[Wed Apr 28 07:23:17.497937 2021] [:error] [pid 317] [client 172.17.0.1:33300] PHP Notice:  Trying to get property of non-object in /usr/share/centreon/www/include/monitoring/status/Notifications/notifications.php on line 117, referer: http://172.17.0.2/centreon/main.php
[Wed Apr 28 07:23:17.497945 2021] [:error] [pid 317] [client 172.17.0.1:33300] PHP Fatal error:  Call to a member function get_id() on a non-object in …
```
> fix(notification): correct undefined variable

- unattended.sh
The `unattended.sh` script must be run by root.
This change adds an immediate and explicit control of this requirement.
> enh(unattended): unattended immediatly check if run by root

- libinstall/functions
avoid 404 redirection on react routes
**Fixes** MON-6528
go directlly to following url : http://<centreon_address>/monitoring/resources
Check in browser console that no 404 error is thrown
> fix(apache): avoid 404 redirection on react routes

- www/front_src/src/Resources/Graph/Performance/index.tsx
- www/front_src/src/Resources/Graph/format.ts
- www/front_src/src/Resources/dateTime.ts
This fixes dates display by parsing them following the user locale
https://www.loom.com/share/4890658634d84e94a76709adec27b78a
- Create a servie with graph data
- Switch the profile language to French (or another language than English)
- Open the service's graph in the panel
- Move your mouse over the graph
- -> The date time are displayed using the correct language
> Fix(UI): Parse graph dates following the locale

- Jenkinsfile
Fixing timeout on qg with sleeping before getting the sonar webhook. Sleep will be removed when sonar will be migrated.
> fix(ci): Sonar quality gate fix

- Jenkinsfile
Remove Sleep120 from CI Quality Gate stage.
> enh(CI): Remove sleep 120 from quality gate stage

- www/front_src/src/Resources/Details/tabs/Services/index.tsx
This fix the service selection on the services list
https://www.loom.com/share/3ac18c043966421295ab830d78f06c8c
- Add a host with some services
- On Resource Status, open the host details panel
- Select the "Services" tab
- Click on a service name
- -> The selected service details panel is displayed without any error
> Fix(UI): Fix service selection on services list

- Jenkinsfile
chore(ci): set manually reference build
> chore(ci): set manually reference build

- www/include/Administration/parameters/DB-Func.php
- www/include/Administration/parameters/general/form.php
This PR hide Keycloak tokens in CentreonUI form for 20.04.x
**Fixes** # MON-10849
> fix(security): hide Keycloak tokens in CentreonUI form

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
This fixes the downtime translation
- Go to the Resources Status page
- Add a downtime on a resource
- -> The modal title ("Downtime") is correctly translated
> Fix(i18n): Fix the "Downtime" translation

- Jenkinsfile
In order to have QA branches containers builded automatically after a centreon web develop or dev-xx.xx.x successfull build
Check from Jenkins GUI if develop branch  of modules have been triggered by web develop branch.
> enh(ci): adding QA branches as scheduled job

- Jenkinsfile
In order to fix the api doc delivery versioning issue, we now deliver api doc for reference job.
> fix(ci): manage api doc delivery for reference build

- unattended.sh
Using Oracle EPEL8 repository alone causes the installation to fail when remi 8 release has to be installed.
This has been changed to standard EPEL8 instead.
As it looks like, no package seems to be brought from Oracle EPEL 8.
> fix(unattended): changed ol8 epel to epel8 for Oracle case

- lib/perl/centreon/script/centreontrapd.pm
on a centreon central server that is receiving a lot of snmp traps, the configuration export will fail most of the time because the /var/lib/centreon/centcore.pm file owner is centreon:centreon with a chmod 644 that doesn't let apache write into this file. 
This situation shouldn't happen because centreontrapd must write in `/var/lib/centreon/centcore/<date>-traps` files. But the removed line overwrite the case where we try to write in those files.
**Fixes**  #4236
- put centreontrapd in info mode instead of error (sed -i 's/error/info/' /etc/sysconf/centreontrapd)
- restart centreontrapd (service centreontrapd restart)
- send a trap to your central server (you must have a working host and with a passive service receiving traps monitored by …
> MON-11758 fix conf export fail because of centreontrapd

- libinstall/functions
This PR intends to add SameSite parameter to apache conf
packaging installation is handle here: https://github.com/centreon/centreon-build/pull/819
**Fixes** # MON-12056
> enh(conf): add SameSite parameter to apache conf

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
fix invalid character in translation file
**Fixes** MON-13160
> fix(translation): fix invalid character in translation file
