centreon/centreon

- doc/en/release_notes/centreon-19.10/centreon-19.10.0-beta.2.rst
- doc/en/release_notes/centreon-19.10/index.rst
- doc/fr/release_notes/centreon-19.10/centreon-19.10.0-beta.2.rst
- doc/fr/release_notes/centreon-19.10/index.rst
- www/install/insertBaseConf.sql
Update version to 19.10.0-beta.2.
Update Centreon Web from 19.10.0-beta.1 or earlier. Everything keeps working as expected.
> Update version to 19.10.0-beta.2.

- doc/en/administration_guide/parameters.rst
- doc/en/api/clapi/objects/hosts.rst
- doc/en/faq/remote_server.rst
- doc/en/installation/common/install_iso.rst
- doc/en/installation/common/web_install.rst
- doc/en/release_notes/centreon-19.10/centreon-19.10.0-beta.2.rst
- doc/en/release_notes/centreon-2.8/centreon-2.8.27.rst
- doc/en/upgrade/from_packages_1810.rst
- doc/en/upgrade/from_packages_1904.rst
- doc/fr/administration_guide/parameters.rst
- doc/fr/api/clapi/objects/hosts.rst
- doc/fr/faq/remote_server.rst
- doc/fr/installation/common/install_iso.rst
- doc/fr/release_notes/centreon-19.04/centreon-19.04.1.rst
- doc/fr/release_notes/centreon-19.10/centreon-19.10.0-beta.2.rst
- doc/fr/release_notes/centreon-2.8/centreon-2.8.27.rst
- doc/fr/upgrade/from_packages_1810.rst
- doc/fr/upgrade/from_packages_1904.rst
* Fix make html errors
* Add beta.2 release note
* Add missing PHP timezone configuration for updates
> fix(doc): 19.10 fix documentation

- src/Centreon/Domain/Entity/Topology.php
> fix(translation): translate properly menu entries

- lib/Centreon/Object/Relation/Host/Template/Host.php
- www/include/configuration/configObject/host/DB-Func.php
Delete services when host template is detached from host
Include DB-Func file and use deleteHostServiceMultiTemplate() to delete related services for host templates.
> Delete services when host template is detached from host

- doc/en/upgrade/from_packages_1810.rst
- doc/en/upgrade/from_packages_1904.rst
- doc/en/upgrade/from_packages_34.rst
- www/class/centreon-clapi/centreonAPI.class.php
- www/include/home/customViews/index.ihtml
> (fix) Fix typo Centreon word (and one variable)

- cron/centAcl.php
- www/class/centreon-partition/partEngine.class.php
- www/install/steps/process/createDbUser.php
Branch specifically created to adapt upgrade PR to the 18.10.x
`https://github.com/centreon/centreon/pull/7760`
`https://github.com/centreon/centreon/pull/7782`
`https://github.com/centreon/centreon/pull/7780`
**All these PR are already reviewed and approved**
**Fixes** # (mysql 8 upgrade process)
- Install a 18.10.0 with a mariaDB database and try to update to the latest version
- Install a 18.10.0 with a deported mysql database and try to update to the latest version
The scripts should not fail at all.
- [ ] I have made sure that **acceptance tests** related to the story are successful (**local …
> Mon 4114 update fix for 18.10.x using mysql8

- doc/en/installation/common/install_packages.rst
- doc/fr/installation/common/install_packages.rst
Replace the 19.04 centreon-release repo with the 19.10
Correct the SQL Strict Mode notice
Minor correction in french
> MON 4122 Update Strict mode doc and repo link

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> Correction on custom view using spanish

- www/Themes/Centreon-2/style.css
Steps to reproduce the issue:
Monitoring > Status Details > Services
Click on a service with multiple metrics
Scroll down
Put you mouse on the graph
Describe the results you received:
Labels are centered, leading to something difficult to read and the display is different than when we display it under "Monitoring > Performances > Graphs"
**Fixes** # (https://github.com/centreon/centreon/issues/5274) …
> enh(UI): labels in graph alignment

- www/include/monitoring/recurrentDowntime/listDowntime.php
Fix a blank page on the reccurrent downtimes page.
> fix(UI): default argument type of the search field

- www/class/centreonGraph.class.php
- www/include/views/graphs/generateGraphs/generateMetricImage.php
Fixing the displayerror method to avoid the blank page / crash of the browser
Enhancing messages displayed
Creating a PNG with the error message instead ot the RRD graph
**Fixes** # (https://github.com/centreon/centreon/pull/7822) requested changes
> fix(BE): better handling PNG export failure

- README.md
> fix(README): remove Edyta Skibinska from Centreon team

- doc/en/release_notes/centreon-18.10/centreon-18.10.8.rst
- doc/en/release_notes/centreon-18.10/index.rst
- doc/fr/release_notes/centreon-18.10/centreon-18.10.8.rst
- doc/fr/release_notes/centreon-18.10/index.rst
- www/install/insertBaseConf.sql
- www/install/sql/centreon/Update-DB-18.10.7_to_18.10.8.sql
Preparing the next release
- [] 19.04.x
> chore(build): prepare next release 18.10.8

- doc/en/release_notes/centreon-19.04/centreon-19.04.5.rst
- doc/en/release_notes/centreon-19.04/index.rst
- doc/fr/release_notes/centreon-19.04/centreon-19.04.5.rst
- doc/fr/release_notes/centreon-19.04/index.rst
- www/install/insertBaseConf.sql
> chore(build): prepare next release 19.04.5

- Jenkinsfile
- build.xml
- ruleset.xml
Resolve: MON-4139
Add rules to the CI to return coding style issues in each PR
> enh(build): improve coding style checks for 18 10

- Jenkinsfile
- build.xml
- ruleset.xml
Resolve: MON-4139
Add rules to the CI to return coding style issues in each PR
> enh(build): improve coding style checks for 19 04

- Jenkinsfile
- build.xml
- ruleset.xml
Resolve: MON-4139
Add rules to the CI to return coding style issues in each PR
> enh(build): improve coding style checks for master

- src/Centreon/Application/DataRepresenter/ContactGroupEntity.php
- src/Centreon/Tests/Application/DataRepresenter/ContactGroupEntityTest.php
Update return type of activate from string to integer for consistency
**Fixes** # BAM-678
> enh(api): update type of returned activate property

- www/api/class/centreon_clapi.class.php
On huge plateforms, the array_walk in the for loop is the same as doing an infinity loop. You can't do a show service through the rest api even if you have a 5 minutes timeout in your php configuration.  Thanks @kduret on this one, nice catch.
- first of all, you need 290 000 services in your configuration (not in your monitoring, just your configuration)
- configure your php.ini file to have a 5 minutes execution time timeout
- vim /etc/opt/rh/rh-php71/php.ini and change the max_execution_time to be at 300
- restart php-fpm, service rh-php71-php-fpm restart 
- authenticate yourself on the REST API
curl -k -d 'username=xxxxxx&password=xxxxxxx' 'http://127.0.0.1/centreon/api/index.php?action=authenticate'
- show all your service thanks to …
> enh(api): improve performance of clapi call through REST API

- features/ContactGroupsApi.feature
fix acceptance test for #7851 BAM-438
> fix(test): acceptance test related with API

- src/CentreonRemote/Application/Clapi/CentreonWorker.php
Enhances CentreonWorker logging.
Nothing particular, just launch an export/import process.
> enh(remote-server): improve centreonworker logging

- unattended.sh
This PR adds a new script that aims at automating all manual steps that are required when installing Centreon from packages.
Note : installation is currently made with the 19.04 version of Centreon as it is the latest stable release available now.
If the environment is supported, the script should execute without error and left you with a working Centreon server (but the web install still have to be executed).
If the environment is not supported the script should fail with an explicit error message.
`curl -L https://github.com/centreon/centreon/raw/MON-4142-simple-install/unattended.sh | sh`
> Add unattended install script.

- package-lock.json
- package.json
> package lock updated with 19.10 npm repo

- www/class/centreonUtils.class.php
- www/include/Administration/myAccount/DB-Func.php
- www/include/Administration/myAccount/formMyAccount.php
- www/include/configuration/configObject/contact/DB-Func.php
- www/include/configuration/configObject/contact/listContact.php
Exclude XSS injection from myAccount alias and name fields.
Fixes MON-4129 MON-4147
> fix(secu): escape persistent and reflected XSS in my account - for 18.10.x

- www/class/centreonUtils.class.php
- www/include/Administration/myAccount/DB-Func.php
- www/include/Administration/myAccount/formMyAccount.php
- www/include/configuration/configNagios/formNagios.php
- www/include/configuration/configObject/contact/DB-Func.php
- www/include/configuration/configObject/contact/listContact.php
Exclude XSS injection from myAccount alias and name fields.
Fixes MON-4129 MON-4147
> fix(secu): escape persistent and reflected XSS in my account - for 2.8.x

- www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
- www/include/monitoring/status/Services/xml/makeXMLForOneService.php
Sanitize host_id and service_id
> fix(security): sanitize host_id and service_id

- src/Centreon/ServiceProvider.php
Improve the centreon user service definition
> fix(core): update ServiceProvider

- README.md
- www/include/Administration/about/about.php
> fix(README): remove developers from the Team

- www/class/centreonSession.class.php
- www/include/core/login/login.php
- www/include/core/login/processLogin.php
- www/include/views/graphs/generateGraphs/generateImage.php
- www/index.php
- Securing the PHPSESSID cookie from hijack or modifications using the session.strict_mode in the php.ini (these modifications have been removed from current PR; and already merged on centreon-build to be deployed with the next RPMs).
- Regenerating the session_id() value after the login and after the logout
- Minor typo and variable naming corrections
-> Please contact me
> Mon 3204 enable session cookie strict mode

- doc/en/administration_guide/parameters.rst
- doc/fr/administration_guide/parameters.rst
- www/include/Administration/parameters/ldap/javascript/ldapJs.php
* Add Okta template in list of LDAP templates 
1. Create a new LDAP entry
2. Select Okta template
> Mon 4134 ldap add okta template

- www/install/step_upgrade/step4.php
- www/install/steps/templates/step7.tpl
> fix(typo): update wording about cache in install/upgrade process

- www/install/step_upgrade/step5.php
Fix step5 of upgrade process.
There is an error 500 which block access to next step
**Fixes** MON-4154
> fix(upgrade): fix syntax error in step5 of upgrade process

- doc/en/installation/from_sources.rst
- doc/fr/installation/from_sources.rst
Adding mandatory parameters information in the french and english doc.
Generate the doc
> doc(secu): add php mandatory params info in source installation - latest doc 

- doc/en/installation/from_sources.rst
- doc/fr/installation/from_sources.rst
Adding mandatory parameters information in the french and english doc.
Generate the doc
> doc(secu): add php mandatory param info for source installation - 19.04

- www/class/centreonUtils.class.php
Escape script and input tags in all listings
> fix(security): Escape script and input tags by default

- composer.json
- composer.lock
- features/bootstrap/DisableFieldsOnBlockedObjectsContext.php
fix acceptance test of locked elements
Run the CI
> fix(test): fix acceptance test of locked elements

- doc/en/migration/nagiostocentreon.rst
- doc/fr/migration/nagiostocentreon.rst
> Doc correct migration using nagios reader

- src/CentreonLegacy/Core/Module/Upgrader.php
It is useless to have these files, they can be removed.
Module upgrade should work as usual.
> Do not require conf.php files to exist in module upgrade directories

- package-lock.json
- package.json
- www/front_src/src/helpers/dynamicImport.js
- www/front_src/src/helpers/extras/global.js
IE11 was not able to load external modules which was compiled using umd format
**Fixes** MON-4192
> fix(ui): fix compatibility with IE11 (external modules)

- lang/es_ES.UTF-8/LC_MESSAGES/help.po
- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/help.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/help.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/help.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/include/Administration/parameters/DB-Func.php
- www/include/Administration/parameters/general/form.php
- www/include/Administration/parameters/general/help.php
- www/install/php/Update-19.10.0-rc.1.php
- www/install/php/Update-19.10.0-rc.2.php
Add a rule in the administration form to require a session value lesser or equal to 120min.
Update the user's saved session value in the DB if greater to 120min
**Fixes** # (secu)
> enh(secu): add rule for max session duration - for master

- lang/es_ES.UTF-8/LC_MESSAGES/help.po
- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/help.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/help.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/help.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/include/Administration/parameters/DB-Func.php
- www/include/Administration/parameters/general/form.php
- www/include/Administration/parameters/general/help.php
- www/install/php/Update-19.04.5.php
Add a rule in the administration form to require a session value lesser or equal to 120min.
Update the user's saved session value in the DB if greater to 120min
**Fixes** # (secu)
> enh(secu): add rule for max session duration for 19 04

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/include/configuration/configObject/contact_template_model/formContactTemplateModel.php
renaming the user template actions and titles properly
> fix(ui): rename contact template titles properly

- www/class/centreonUtils.class.php
fix the returned contact names in the list when the escapeSecure method is called
> fix(UI): contact list using escapeSecure method

- behat.yml
- composer.lock
- features/APIv2/Monitoring/HostApi.feature
- features/APIv2/Monitoring/ServiceApi.feature
- features/bootstrap/APIv2Context.php
add new acceptance tests to cover Monitoring Host and Services RestAPIs
**Fixes** Mon-4185
> Add acceptance tests for Monitoring Host and Services APIs

- lib/perl/centreon/script/centcore.pm
Hi,
This PR corrects a typo @lpinsivy did in #7849.
Thank you for merging this 👍
Edit : issue still present in 19.10.0-rc.1.
> fix(scp) Correct typo in #7849

- Jenkinsfile
- features/APIv2/Monitoring/HostApi.feature
- features/APIv2/Monitoring/ServiceApi.feature
extend the Jenkins file to find all features in sub-directories too
**Fixes** MON-4185
> Improve the Jenkinsfile to search for feature files in sub-directories

- cron/centreon-send-stats.php
- doc/en/ceip.rst
- doc/fr/ceip.rst
- www/install/step_upgrade/step5.php
- www/install/step_upgrade/templates/content.tpl
- www/install/steps/templates/content.tpl
- www/install/steps/templates/step9.tpl
Improve CEIP program for Centreon
> Telemetry ceip improvements

- www/class/config-generate/abstract/host.class.php
- www/class/config-generate/abstract/service.class.php
> fix(generate) fix query result condition

- doc/en/installation/common/install_packages.rst
- doc/en/installation/common/sql_strict_mode.rst
- doc/en/release_notes/centreon-19.10/centreon-19.10.0-beta.1.rst
- doc/fr/installation/common/install_packages.rst
- doc/fr/installation/common/sql_strict_mode.rst
- doc/fr/release_notes/centreon-19.10/centreon-19.10.0-beta.1.rst
Explain how to disable SQL strict mode
> fix(doc): Disable SQL strict mode

- www/class/config-generate/abstract/host.class.php
- www/class/config-generate/abstract/service.class.php
> fix(notification) fix enable inheritance

- www/class/config-generate/abstract/host.class.php
> fix(inheritance) fix vertical notification inheritance

- www/class/config-generate/abstract/service.class.php
> fix(inheritance) fix service close inheritance by host

- src/Centreon/Infrastructure/Acknowledgement/AcknowledgmentRepositoryRDB.php
- src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
When a contact is an admin we checked these access group when it is not necessary.
> fix (api): Fix bad verification when an admin has access group

- src/Centreon/Infrastructure/Acknowledgement/AcknowledgmentRepositoryRDB.php
Fix author_id at null when listing acknowledgement
> fix(api): Fix author_id at null when listing acknowledgement

- src/Centreon/Application/Controller/AcknowledgementController.php
- src/Centreon/Domain/Contact/Contact.php
- src/Centreon/Domain/Contact/Interfaces/ContactRepositoryInterface.php
- src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
Taking into account of action restrictions for acknowledgements.
Add actions access (acknowledgement/disaknowledgement) on contact to test add/remove acknowledgement.
> fix(api): Add the acknowledgement rules in contact

- src/Centreon/Infrastructure/Contact/ContactRepositoryRDB.php
> fix(api): Fix select on contact rules

- doc/en/installation/index.rst
- doc/fr/installation/index.rst
Juste explain how to quickly install Centreon for tests
> enh(doc): add how to quickly test centreon

- doc/en/index.rst
- doc/en/release_notes/index.rst
- doc/fr/index.rst
- doc/fr/release_notes/index.rst
Remove warning message of beta version for 19.10
> enh(doc) remove Centreon 19.10 beta warning

- doc/en/release_notes/centreon-19.10/centreon-19.10.0.rst
- doc/fr/release_notes/centreon-19.10/centreon-19.10.0.rst
Fix bullet list in Centreon release note
> fix(doc): correct bullet list in release note

- cron/centAcl.php
bound value typo correction in centACL.php
> fix(cron): renaming bound variable name

- src/CentreonLegacy/Core/Install/Step/Step1.php
- www/install/step_upgrade/step1.php
> Fix(install) check PHP version

- www/install/step_upgrade/process/process_step5.php
- www/install/steps/process/process_step9.php
Replace rename PHP function by copy + delete to allow to move install directory from a device (partition) to another one
> fix(install/update): replace remane by copy + delete

- project/new_version.sh
The new bugfix version creation script is updated.
Run ./project/new_version.sh. All necessary changes for a new bugfix should be included.
> Improve new bugfix version creation script.

- www/class/centreonSession.class.php
- www/include/core/header/header.php
The method checkSession declared as static is improperly called
> fix(BE): correct the call of checkSession static method

- www/include/monitoring/status/Hosts/xml/hostXML.php
remove unused http parameters in hostXML.php file.
cleaning file
replace https://github.com/centreon/centreon/pull/8011 to avoid odd behavior in Jira (the branch was wrongly named)
> fix(secu): remove unused http parameters in hostXML.php file for PHP5

- www/class/centreonSession.class.php
- www/class/centreonUtils.class.php
- www/class/centreonXMLBGRequest.class.php
- www/include/monitoring/status/Hosts/host.php
- www/include/monitoring/status/Hosts/xml/hostXML.php
An authenticated attacker can perform an SQL injection on this page parameters
**Fixes** # (**CVE-2019-17647**)
> fix(secu): protect from SQL injections hostXML.php for 2.8

- www/include/monitoring/status/Hosts/xml/hostXML.php
An authenticated attacker can perform an SQL injection on this page parameters
**Fixes** # (CVE-2019-??)
> fix(secu): protect from SQL injections hostXML.php for 18 10

- www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
Security fix which remove unused http parameters (eg: $_GET) or sanitize them in hostgroups page
> fix(secu) remove unused params or sanitize them in hostgroups page

- www/include/monitoring/status/Services/xml/serviceGridXML.php
Avoid SQL injection on this page parameters
> fix(secu): protect from SQL injections serviceGridXML.php for 2.8

- www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
Avoid SQL injection on this page parameters
> fix(secu): protect from SQL injections hostgroupXML.php for 2.8

- www/include/monitoring/status/Services/xml/serviceSummaryXML.php
Avoid SQL injection on this page parameters
> fix(secu): protect from SQL injections serviceSummaryXML.php for 2.8

- www/include/monitoring/status/ServicesServiceGroups/xml/serviceGridBySGXML.php
- www/include/monitoring/status/ServicesServiceGroups/xml/serviceSummaryBySGXML.php
Avoid SQL injection on this page parameters
> fix(secu): protect from SQL injections in service by serviceGroups XML files for 2.8

- www/include/configuration/configObject/traps-mibs/formMibs.php
Manufacturer id is not protected in MIB import form
**Fixes** MON-4095
> fix(security): fix RCE on mib import from manufacturer input

- cron/centAcl-Func.php
- cron/centAcl.php
The LDAP contactgroup synchronization was made every minute.
Replace this value to 60minutes instead
> enh(perf): set LDAP contactgroup synchronization every hour

- www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
- www/include/monitoring/status/Services/xml/makeXMLForOneService.php
- www/include/monitoring/status/Services/xml/serviceGridXML.php
- www/include/monitoring/status/Services/xml/serviceSummaryXML.php
- www/include/monitoring/status/Services/xml/serviceXML.php
> fix(secu): remove unused http parameters in services files

- www/include/monitoring/status/Hosts/xml/hostXML.php
> fix(secu): remove unused http parameters in hostXML file

- www/class/centreonGraphService.class.php
To fix STUDIO-2315, we need to add additional information
Solution is to add a new field to the response, which will always be the name of the associated metric, so we have no possible regressions.
> fix(api) return curve metric name for map

- doc/en/api/clapi/objects/service_templates.rst
- doc/fr/api/clapi/objects/service_templates.rst
- www/class/centreon-clapi/centreonServiceTemplate.class.php
> fix(clapi) add macro password option for service template

- www/include/monitoring/status/Hosts/xml/hostXML.php
- avoid SQL injection in monitoring host page
- clean code
> fix(secu): prevent from sql injections in host page

- www/include/monitoring/status/Services/xml/makeXMLForOneHost.php
- www/include/monitoring/status/Services/xml/makeXMLForOneService.php
- www/include/monitoring/status/Services/xml/serviceGridXML.php
- www/include/monitoring/status/Services/xml/serviceSummaryXML.php
- www/include/monitoring/status/Services/xml/serviceXML.php
- avoid SQL injection in monitoring services page
- clean code
> fix(secu): prevent from sql injections in services pages

- www/include/monitoring/status/HostGroups/xml/hostGroupXML.php
- avoid SQL injection in monitoring hostgroup page
- correct order witch wasn't taken in account 
- clean code
> fix(secu): prevent from sql injections in hostgroupXML file

- tests/clapi_export/clapi-configuration.txt
Quickfix for build.
Build will be green.
> fix(tests): update clapi export config file

- tests/clapi_export/clapi-configuration.txt
quickfix of acceptance tests: REF: https://github.com/centreon/centreon/pull/8102
19.10.x build will be green
> fix(tests): update clapi export config file (#8102)

- www/class/centreon-clapi/centreonHost.class.php
**Fixes**
Resolve #8076 
Everything is in the issue.
> fix(api): Unable to set host notification to None through the API

- www/include/configuration/configServers/DB-Func.php
> fix(sql) prepare query before bind params

- doc/en/api/clapi/objects/broker_cfg.rst
- doc/fr/api/clapi/objects/broker_cfg.rst
- tests/clapi_export/clapi-configuration.txt
- tests/rest_api/rest_api.postman_collection.json
- tests/rest_api/rest_api.postman_environment.json
Some references to correlation remains...
**Fixes** MON-4071
> fix(broker): definitely remove correlation

- doc/en/release_notes/centreon-2.8/centreon-2.8.30.rst
- doc/fr/release_notes/centreon-2.8/centreon-2.8.30.rst
> 2.8.30 release notes

- www/install/sql/centreon/Update-DB-18.10.7_to_18.10.8.sql
Edit and save engine configuration
> fix(sql) add missing column for engine configuration

- www/class/config-generate-remote/Relations/TrapsVendor.php
> fix(traps) accept null value for description

- lib/perl/centreon/trapd/lib.pm
Fix issue when there are multiple traps definitions with the same OID.
You need to create multiple traps definitions with the same OID. Link one trap with a service and send a trap. If you have 4 traps (for example), you have 25% change of success.
> Fix traps regression with same oid

- www/include/configuration/configObject/host/listHost.ihtml
From page 'Configuration > Hosts', set a string in "Name" field.
Then click on "Search".
List is displayed according to filter, but "Name" field is emptied out.
If you go to another page and back, filter is still empty but list is filtered.
You need to click on "Search" to reset the listing.
> fix(filter) fix host name filter history

- www/Themes/Centreon-2/style.css
- www/include/home/customViews/index.ihtml
> fix(UI): correctly toggle edit load and header of widgets

- www/install/php/Update-19.10.2.php
- www/install/php/Update-19.10.3.php
The PR https://github.com/centreon/centreon/pull/8122, was merged on the master when the last 19.10.2 minor was released. Resulting in an unconsistent upgrade script name
This PR is meant to move the upgrade script in a coherent script version to avoid missing upgrade steps.
ie : upgrade from a 19.10.2 to a 20.04.0
Upgrade a centreon from a 19.10.2 to a 20.04.0 and check that everything work fine (related to the ldap contact DNs saved in the DB)
> fix(upgrade): move update script to next minor

- cron/centAcl-Func.php
- cron/centAcl.php
ACLs on service were not calculated (only on 19.04.5), so non-admin users could not see any services.
Refs: MON-4530
> fix(acl): fix calculation of acls on services

- doc/en/release_notes/centreon-19.04/centreon-19.04.6.rst
- doc/fr/release_notes/centreon-19.04/centreon-19.04.6.rst
- www/install/php/Update-19.04.5.php
- www/install/php/Update-19.04.6.php
moving the upgrade script correcting inconsistent data saved in the DB, to the next minor
> fix(upgrade): move LDAP fix upgrade script to next minor

- www/include/home/customViews/layouts/column_0.ihtml
- www/include/home/customViews/views.php
define a new template file in directory /layouts in case of viewId is not TRUE.
> fix(js) define new error file template

- www/class/config-generate/abstract/host.class.php
- www/class/config-generate/abstract/object.class.php
- www/class/config-generate/abstract/service.class.php
- www/class/config-generate/contact.class.php
- www/class/config-generate/contactgroup.class.php
- www/class/config-generate/host.class.php
- www/class/config-generate/hosttemplate.class.php
- www/class/config-generate/service.class.php
- www/class/config-generate/servicetemplate.class.php
- www/include/monitoring/common-Func.php
Fix performance regression from 19.10.x notification system
Need many hosts/services and templates. Otherwise you won't see the generation time diff.
> enh(config): fix performance regression from 19.10.x notification system

- www/class/centreonCustomView.class.php
- www/class/centreonWidget.class.php
> fix(widget): fix user with no widget preferences

- tests/php/CentreonLegacy/Core/Widget/RemoverTest.php
> fix(test): fix remove widget unit test

- composer.lock
> chore(build): update composer.lock.

- www/include/common/javascript/centreon/brokerConfig.js
fix the check of broker input form who need a number
> fix(js): fix check type of broker connections count

- www/include/home/customViews/layouts/column_1.ihtml
- www/include/home/customViews/layouts/column_2.ihtml
- www/include/home/customViews/layouts/column_3.ihtml
- www/include/home/customViews/layouts/widgetScript.js
- www/include/home/customViews/views.php
> fix(security) dont return js 

- doc/en/upgrade/from_packages_1904.rst
- doc/fr/upgrade/from_packages_1904.rst
Merging of #7993 and #7994 pull requests in one
> Update doc add warning php conf

- www/include/configuration/configServers/DB-Func.php
the request has duplicated assertion that need to be removed to be able to save the form properly
**Fixes** # (VF MON-4509)
> fix(core): remove duplicate code

- www/include/configuration/configNagios/DB-Func.php
Excess code was applied on 18.10.x branch with cherry-pick of PR #7591 
**Fixes** #8196
Edit the Centreon Engine configuration through "Configuration > Pollers > Centreon Engine" menu
You lose Broker Module Option value and this generate error in /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log file:
```
[03-Apr-2019 14:24:05 Europe/London] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/centreon/www/include/configuration/configNagios/DB-Func.php on line 239
[03-Apr-2019 14:24:05 Europe/London] PHP Warning:  array_map(): Argument #2 should be an array in /usr/share/centreon/www/include/configuration/configNagios/DB-Func.php on line 2160
[03-Apr-2019 14:24:05 Europe/London] PHP Warning:  join(): Invalid arguments …
```
> fix(engine): Deletion of excess code from PR #7591 (#8196)

- www/api/class/centreon_configuration_service.class.php
Remove PHP warning:
```
[24-Dec-2019 11:27:15 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 297
[24-Dec-2019 11:27:15 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 297
[24-Dec-2019 11:27:15 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 297
[24-Dec-2019 11:27:15 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 297
[24-Dec-2019 11:27:15 Europe/Paris] PHP Notice:  Undefined index: service_activate …
```
> fix(bug): remove PHP warning in centreon_configuration_service class

- doc/en/developer/writemodule.rst
- doc/fr/developper/writemodule.rst
Update links to the example module. Original PR #6170 by @kozfelipe .
Check the developer documentation about writing modules. URL should be good.
> Update links to the dummy module.

- package-lock.json
- package.json
Fix security issues in javascript dependencies
Highest issue is from handlebars
Check acceptance tests are green on CI
> fix(sec): upgrade javascript dependencies (handlebars)

- .gitattributes
Downloading Centreon sources from https://github.com/centreon/centreon/releases doesn't allow to proceed to Centreon installation
**Fixes** #8222
Download sources from https://github.com/centreon/centreon/releases
Perform Centreon web installation from sources
> fix(composer): add missing files in sources - #8222

- www/class/centreonGraph.class.php
foreach value $dsVal is not replaced in loop.
**Fixes** #8194
> fix(variable) Use camelCase in loop.

- doc/en/api/api_rest/index.rst
- doc/fr/api/api_rest/index.rst
- www/class/centreon-clapi/centreonHost.class.php
* If all filters are valide, export the correct number of values
* If their is duplicated filters, keep only one
* Add geo_coords in list of filter
**Fixes** #7836, #7894, #6598
> fix(clapi): improve getparam for host 

- src/CentreonRemote/Infrastructure/Export/ExportManifest.php
- src/CentreonRemote/Tests/Infrastructure/Service/ExportServiceTest.php
improvements in the unit test ExportServiceTest::testImport as a continuation of the following discussion https://github.com/centreon/centreon/pull/8107#discussion_r355353398
with the following command `vendor/bin/phpunit --no-coverage src/CentreonRemote/Tests/Infrastructure/Service/ExportServiceTest.php`
> fix(test): improve the unit test ExportServiceTest::testImport

- libinstall/CentWeb.sh
- libinstall/functions
The file api/index.php was not installed using sources
Install Centreon using sources
You can use API v2
> fix(install): install api/index.php file

- package-lock.json
This PR fixes submenu toggle icon that was not visible by updating centreon-ui in package-lock.json
Build the project and make sure that topcounters's submenu toggle icon is visible.
> fix(ui): Submenu toggle icon is not visible

- www/include/core/login/processLogin.php
**Fixes** #6631
copy autologin link, past in browser,  this same page.
.
> fix(autologin) keep uri parameters.

- www/install/php/Update-20.04.0-beta.1.php
change origin and destination of template and configuration files
**Fixes** # (gorgone)
> enh(core): adapt upgrade script to latest modifications

- www/install/var/gorgone/gorgoneCoreTemplate.yaml
Update keys pathes since https://github.com/centreon/centreon-gorgone/commit/61d665bc979ac300f134571e7d0db7d51279282b
> enh(install): fix default keys pathes

- www/install/insertTopology.sql
- www/install/sql/centreon/Update-DB-20.04.0-beta.1.sql
Create menu entry to access to unified view
menu entry is : Monitoring > Resources (beta)
**Fixes** BAM-889
Check that menu entry is displayed
> chore(topology): insert unified view in topology

- webpack.config.js
> fix(ui): Fix fonticons not loading (19.04.x)

- CONTRIBUTING.md
Better manage the contributors PR and integrate it to our workflow
Enhance the github documentation on how to contribute.
Add specific tags -> 
**Fixes** # (external PR integration)
> enh(doc): external PR documentation

- SECURITY.md
> sec(doc): add SECURITY.md template

- package.json
correct the version of centreon in the package.json
**Fixes** # (source installation)
> enh(core): update centreon version in the package.json 

- doc/en/exploitation_guide/Real_time_action.rst
Hi,
This PR solves a small doc typo.
Thx 👍
> fix(doc): simple typo

- www/include/monitoring/status/Services/xml/serviceSummaryXML.php
Fix query sent to the back end. This fix has already been applied to the other release.
> fix(query): remove pdo error in status filters

- doc/en/installation/from_sources.rst
- doc/fr/installation/from_sources.rst
Typo correction in the source installation documentation from previous merge
> enh(doc): correct typo

- www/include/monitoring/comments/AddComment.php
- www/include/monitoring/comments/AddHostComment.php
- www/include/monitoring/comments/AddSvcComment.php
- www/include/monitoring/comments/commentHost.php
- www/include/monitoring/comments/comments.php
- www/include/monitoring/comments/common-Func.php
- www/include/monitoring/comments/listComment.php
update licenses in modified files
> enh(core): update licenses

- Jenkinsfile
Stash git sources for Sonar analysis instead of manually storing them on the internal repository.
This will only affect the master branch.
> Stash git sources for Sonar analysis

- www/front_src/src/components/Hook/index.tsx
- www/front_src/src/components/header/index.js
- www/front_src/src/helpers/dynamicImport.js
> fix(lint): Fix ESLint warnings (frontend)

- www/class/centreonLDAP.class.php
* Use define member_attribute settings
**Fixes** #7142, #7964
> fix(ldap): use define user member_attribute var

- www/class/config-generate/service.class.php
Some change on class for new module
-
> enh(config): prepare anomalydetection module

- doc/API/centreon-api-v2.yaml
Update API contract for graph endpoints
> doc(api): add graph endpoints to resource endpoint

- src/Centreon/Domain/Monitoring/Resource.php
fix the wrong check in Resource model that is the reason for throwing an exception with code 500
> fix(api): adjust the wrong check in Resource model

- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
improve the check for service criteria in Resource list API, if contains host criteria too will skip the check
**Fixes** MON-5026
> fix(api): Combining type & search bar doesn't work

- doc/API/centreon-api-v2.yaml
- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
- www/front_src/src/Resources/SearchHelpTooltip.tsx
- www/front_src/src/Resources/api/endpoint.ts
- www/front_src/src/Resources/index.test.tsx
Replace host.*\service.* search properties with h.*\s.* in Resource list API
**Fixes** MON-5033
> feat(api): Shorter syntax for search request on resources

- package-lock.json
- package.json
- webpack.config.dev.js
- webpack.config.js
> fix(npm): Fix centreon-ui dependency

- .github/PULL_REQUEST_TEMPLATE.md
Update the PULL_REQUEST_TEMPLATE.md content regarding recent modifications of the developers workflow.
> enh(PULL_REQUEST_TEMPLATE): update content

- README.md
Update the Centreon ressources. Adding:
- Tom Darneix (_Front_)
- Bruno D'Auria (_Front_)
- Thomas Untoja (_Quality Assurance_)
- Colin Gagnaire (_Product Owner_)
Display the README
> enh(README): add Thebarda, bdauria and tuntoja to the team

- doc/API/centreon-api-v2.yaml
Explain 404 response which can happen in metrics endpoints when a host or service is not found
**Fixes** MON-4792
Check API documentation
> doc(api): explain 404 http code of metrics endpoints

- features/bootstrap/URIContext.php
Increase URI test timeouts.
URI acceptance tests should not fail anymore on the CI platform.
> Increase URI test timeouts

- src/Centreon/Application/Controller/CheckController.php
fix scheduling of host and service checks using API
**Fixes** MON-4105
Try to schedule check on host and service using api documentation
> fix(api): fix schedule checks using api

- src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
- www/class/centreon-clapi/centreonInstance.class.php
- www/include/configuration/configServers/DB-Func.php
- www/include/configuration/configServers/formServers.php
Check the validity of poller IP address
> Mon 4940 check poller ip address validity master

- config/packages/serializer/Centreon/Acknowledgement.Acknowledgement.yml
- config/packages/serializer/Centreon/Downtime.Downtime.yml
- doc/API/centreon-api-v2.yaml
- src/Centreon/Domain/Acknowledgement/Acknowledgement.php
- src/Centreon/Domain/Downtime/Downtime.php
extend Downtime and Acknowledgement APIs related to monitoring with the property author_name
**Fixes** MON-5015
> feat(api): Author name is missing in Ack & Downtime

- doc/API/centreon-api-v2.yaml
- src/Centreon/Infrastructure/Monitoring/TimelineRepositoryRDB.php
Fixes QA Validation Failed on timelines
**Fixes** # MON-4866
Revisit test case of ticket and assure changes are proper.
> Mon 4866 fix timelines validation failed

- www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
correct the condition and remove undefined notice
> fix(popup): correct assertion in popup

- www/include/common/javascript/datepicker/localizedDatepicker.js
initiate the variable with a default value and remove the else case
> enh: style in localized datepicker file

- config/Modules/Centreon.yaml
- config/packages/serializer/Application/Request.AckRequest.yml
- config/packages/serializer/Application/Request.DowntimeRequest.yml
- config/packages/serializer/Centreon/Downtime.Downtime.yml
- config/packages/validator/validation.yaml
- config/routes/Centreon/acknowledgement.yaml
- config/routes/Centreon/downtime.yaml
- doc/API/centreon-api-v2.yaml
- src/Centreon/Application/Controller/AcknowledgementController.php
- src/Centreon/Application/Controller/DowntimeController.php
- src/Centreon/Application/Request/AckRequest.php
- src/Centreon/Application/Request/DowntimeRequest.php
- src/Centreon/Domain/Acknowledgement/Acknowledgement.php
- src/Centreon/Domain/Acknowledgement/AcknowledgementException.php
- src/Centreon/Domain/Acknowledgement/AcknowledgementService.php
- src/Centreon/Domain/Acknowledgement/Interfaces/AcknowledgementRepositoryInterface.php
- src/Centreon/Domain/Acknowledgement/Interfaces/AcknowledgementServiceInterface.php
- src/Centreon/Domain/Downtime/Downtime.php
- src/Centreon/Domain/Downtime/DowntimeException.php
- src/Centreon/Domain/Downtime/DowntimeService.php
- src/Centreon/Domain/Downtime/Interfaces/DowntimeRepositoryInterface.php
- src/Centreon/Domain/Downtime/Interfaces/DowntimeServiceInterface.php
- src/Centreon/Domain/Engine/EngineException.php
- src/Centreon/Domain/Engine/EngineService.php
- src/Centreon/Domain/Engine/Interfaces/EngineRepositoryInterface.php
- src/Centreon/Domain/Monitoring/Entity/AckEventObject.php
- src/Centreon/Domain/Monitoring/ResourceService.php
Add / Adapt bulk actions for set downtime and apply aknowledgement to resources
**Fixes** # MON-4791
Check documentation and make calls to apply acknowledgement and downtime to mulitple resources.
> Mon 4791 bulk actions ack downtime

- www/front_src/src/Resources/SearchHelpTooltip.tsx
- www/front_src/src/Resources/translatedLabels.ts
Improve description in search tooltip
_Current translation mechanism does not allow to use argument. So I needed to split some translations, even if it's ugly..._
**Fixes** MON-5042
Check search tooltip
> enh(ui): improve events view search tooltip

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- [] Patch fixing an issue (non-breaking change)
- [] 19.10.x
> fix(typo): Update messages.po (FR/ES)

- config/packages/validator/validation.yaml
- src/Centreon/Application/Controller/AcknowledgementController.php
- src/Centreon/Domain/Monitoring/Resource.php
- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
update incorrect id type
**Fixes** # MON-4986
Try to disacknowledge multiple resources
> update(api): fix id type of resource

- lang/es_ES.UTF-8/LC_MESSAGES/help.po
some not translated sentences are emptied when an english sentence should be displayed
> enh(ui): fix translations

- www/api/class/centreon_performance_service.class.php
Add possibility to exclude Centreon Anomaly Detection Service from list of services
> Mon 4703 improve performance service internal api

- composer.json
- composer.lock
Update symfony http and security dependencies version 
> enh(secu): update composer dependencies

- www/include/views/graphs/generateGraphs/generateImage.php
Resolves: MON-5129
ref: https://github.com/centreon/centreon/pull/8521
> fix(graph): fix missing session

- config/packages/serializer/Centreon/Monitoring.Resource.yml
- src/Centreon/Application/Controller/MonitoringResourceController.php
- src/Centreon/Domain/Monitoring/Resource.php
- src/Centreon/Domain/Monitoring/ResourceService.php
- src/Centreon/Infrastructure/Monitoring/ResourceRepositoryRDB.php
- tests/php/Centreon/Domain/Monitoring/ResourceServiceTest.php
* feat(api): add details endpoint property to Resource list API and remove detailsUrl (#8451)
* feat(api): add details endpoint property to Resource list API and remove detailsUrl
Resolve MON-5070
* fix(api): move loading of endpoints of resource from service to the controller in Resource list API
Resolve MON-5070
* fix(api): update routes of details endpoints of Resource list API
Resolve MON-5070
* fix(test): improve unit tests
Resolve MON-5070
> feat(api): Add details_endpoint property to resource list endpoint

- www/include/configuration/configServers/popup/remote.yaml
- www/install/insertBaseConf.sql
- www/install/sql/centreon/Update-DB-20.04.0-beta.1.sql
- www/install/var/gorgone/gorgoneCoreTemplate.yaml
- www/install/var/gorgone/gorgoneRemoteTemplate.yaml
Add some default values in options table.
Add cmd_dir directive in Gorgone config file.
> fix(install/upgrade): add missing default values in file or database for Gorgone

- www/include/configuration/configServers/popup/remote.yaml
Add cron module to Remote Server template to handle stats collections.
> fix(config): add cron module in remote template

- www/install/sql/centreon/Update-DB-20.04.0-beta.1.sql
> fix(upgrade): fix missing semi-colon

- www/front_src/src/Resources/Actions/Resource/Acknowledge/index.tsx
- www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
- www/front_src/src/Resources/api/endpoint.ts
- www/front_src/src/Resources/api/index.ts
- www/front_src/src/Resources/index.test.tsx
Dowtime and Acknwoledge actions work as before. 
> enh(endpoint): Adapt Downtime and Acknowledgement to new endpoints

- www/front_src/src/Resources/columns/index.tsx
- www/front_src/src/Resources/index.test.tsx
> enh(ui): Fix column widths and display first part of information column only

- www/front_src/src/Resources/columns/HoverChip.tsx
- www/front_src/src/Resources/columns/index.tsx
- www/front_src/src/Resources/index.tsx
> fix(ui): Prevent details panel display when clicking on Tooltip / Prevent graph tab display when Resource has no Graph

- unattended.sh
Make unattended.sh install Centreon 20.04.
Run unattended.sh. It should install 20.04 repository. It will likely fail, because no version is stable yet.
> Update unattended installation script for 20.04.

- src/Centreon/Domain/Proxy/Proxy.php
Serialization available:
\<procotol>://\<user>:\<password>@\<url>:\<port>
\<procotol>://\<user>:\<password>@\<url>
\<procotol>://\<url>:\<port>
\<procotol>://\<url>
> enh(proxy): Update Proxy serialization

- www/front_src/src/Resources/Details/index.tsx
**Fixes** MON-5188
Open the panel and check the shadow (elevation)
> enh(ui): add shadow on events view right panel

- src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
- src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationRepositoryInterface.php
- src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
- src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
Added new methods to manage the host configuration.
> enh(host configuration): Added new methods to manage the host configuration

- www/front_src/src/Resources/Details/Body/tabs/Graph/index.tsx
- www/front_src/src/Resources/Details/Body/tabs/Graph/models.ts
- www/front_src/src/Resources/Details/Header.tsx
- www/front_src/src/Resources/Details/models.ts
- www/front_src/src/Resources/Graph/Performance/index.tsx
- www/front_src/src/Resources/Graph/Status/index.tsx
- www/front_src/src/Resources/Graph/Status/timeSeries.ts
- www/front_src/src/Resources/Graph/format.ts
- www/front_src/src/Resources/columns/index.tsx
This addresses some graph enhancements in terms of display:
- Reduce the padding inside the graph tab
- Reduce the X axes to make more space for the graph
- Format the X axis differently depending on the selected period (Last 24h -> HH:mm, Last 7 days: MM/dd HH:mm, Last 31 days: MM/dd)
- Format the tooltip time value using the corresponding selected period format (as last bullet point)
- Reduce the axes (Y and X) font sizes
It also adjusts the listing by reducing the padding before the resource name
Any **relevant details** of the configuration to perform the test should be …
> enh(ui): Enhance Performance graph display and fix Status graph gradient

- doc/API/centreon-api-v2.yaml
Update API contract to add details_endpoint properties to resources endpoint
> doc(api): update api contract (resource details_endpoint)

- doc/API/README.MD
> doc(api): remove duplicate readme file

- config/services.yaml
- src/Centreon/Application/Controller/Router.php
Manage custom uri in api generated endpoints
**Fixes** MON-4844
- add custom uri in apache configuration
- open details panel in events view
> fix(api): manage custom uri in api generated endpoints

- www/.htaccess
Remove htaccess file which break custom uri configuration
**Fixes** MON-4844
Upgrade to 20.04 with custom uri and try to access to events view page
> fix(web): remove .htaccess file

- www/install/sql/centreon/Update-DB-20.04.0-beta.1.sql
> fix(sql): make sql upgrade compatible with MariaDB 10.3

- www/front_src/src/Resources/Details/Body/index.tsx
- www/front_src/src/Resources/Details/Body/tabs/Details/DetailsCard/cards.tsx
- www/front_src/src/Resources/Details/Body/tabs/Details/clipboard.ts
- www/front_src/src/Resources/Details/Body/tabs/Details/index.tsx
- www/front_src/src/Resources/Details/Body/tabs/Graph/index.tsx
- www/front_src/src/Resources/Details/Header.tsx
- www/front_src/src/Resources/Details/index.test.tsx
- www/front_src/src/Resources/Details/index.tsx
- www/front_src/src/Resources/Details/models.ts
- www/front_src/src/Resources/Filter/index.tsx
- www/front_src/src/Resources/Graph/Performance/index.tsx
- www/front_src/src/Resources/index.tsx
- Always be able to search, even if current search is equal to next search
- Reduce graph padding
- Fix graph not showing negative values
- disable graph animation
- Fix active checks marks not showing for service details
- Increase graph Y Axis margin width
- Fix command line copy
> enh(ui): Fixes to Events view Listing / Details / Graph

- www/front_src/src/Resources/columns/HoverChip.tsx
- www/front_src/src/Resources/columns/State/DetailsTable/index.tsx
- www/front_src/src/Resources/index.test.tsx
> enh(ui): Add delay to HoverChip tooltips and allow display of all results in DetailsTable

- www/include/core/login/processLogin.php
the user has to modify the default page to be the React page as Event views and after that to logout and login again this case is not covered in the PR https://github.com/centreon/centreon/pull/8547
**Fixes** MON-5149
> fix(base): improve the way of redirection in login workflow for predefined default page

- config/packages/serializer/Centreon/Monitoring.Service.yml
- src/Centreon/Domain/Monitoring/Service.php
Add new property for service.
**Fixes** # MON-5218
Request Resource Service details endpoint and check for the new 'flapping' property.
> enh(api): add flapping service property

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/front_src/src/Resources/index.tsx
- www/front_src/src/Resources/translatedLabels.ts
> feat(i18n): Translate Events view page labels

- www/class/config-generate-remote/Broker.php
- www/class/config-generate-remote/Engine.php
- www/class/config-generate-remote/Generate.php
- www/class/config-generate-remote/Relations/BrokerInfo.php
https://github.com/centreon/centreon/issues/8488
> MON-5286 broker stats working on remote server

- package-lock.json
- www/front_src/src/Resources/Details/Body/tabs/Graph/index.tsx
- www/front_src/src/Resources/Graph/Performance/LoadingSkeleton.tsx
- www/front_src/src/Resources/Graph/Performance/index.tsx
- www/front_src/src/Resources/columns/Graph/index.tsx
This PR applies the following fixes:
- Remove the unit from the ticks displayed in the Y Axes
- Always format the time using MM/dd HH:mm in the graph tooltip
- Format using filesize even if the metric doesn't have any unit
- fix the height of the graph to prevent any blinking when the tooltip is triggered in the listing
> enh(ui): Improve Event views Performance graph legend and tooltip

- src/CentreonLegacy/Core/Module/Installer.php
- src/CentreonLegacy/Core/Module/Remover.php
Handle .pre.php install/uninstall module scripts. This will allow modules to better control their install/uninstall process.
This is a technical improvement that will be tested through specific module install/uninstall (Plugin Pack Manager notably).
> Handle .pre.php install and uninstall module scripts.

- www/class/centreonHost.class.php
- www/class/centreonHosttemplates.class.php
> enh(tpl): correct failing TA

- src/Centreon/Application/Controller/MonitoringResourceController.php
add a filter to downtime endpoints in the Resource list
**Fixes** MON-5288
> fix(api): add filters to downtime endpoints in Resource list API

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Domain/Engine/EngineService.php
Add extra translations to exception errors in api v2.
**Fixes** # MON-5270
Test translations.
> enh(lang): add translations

- www/class/centreonHost.class.php
> fix: tpl condition

- package-lock.json
This updates centreon-ui, to include this fix: https://github.com/centreon/centreon-ui/pull/225
> chore(npm): Update centreon-ui

- www/class/centreonLog.class.php
Log file used for PPM errors
**Fixes** # (MON-5299)
PR required by https://github.com/centreon/centreon-pp-manager/pull/98
> enh: add a new log file for PPM

- src/Centreon/Infrastructure/Gorgone/CommandRepositoryAPI.php
Improved error message in case of communication problem with the Gorgone server
> enh(gorgone): Improved error message in case of communication problem with the Gorgone server

- www/install/php/Update-19.04.1.php
Fix missing $
https://centreon.atlassian.net/browse/QA-71
- [x ] 20.04.x (master)
> fix(upgrage): fix syntax error in upgrade script to 19.04.1

- src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
Prevent adding new host with an empty name.
> fix(host): Prevent adding new host with an empty name

- www/install/sql/centreon/Update-DB-20.04.0-beta.1.sql
correct query 
```
[root@localhost yum.repos.d]# tail -f /var/log/centreon/sql-error.log
2020-04-20 19:07|0|0| QUERY : ALTER TABLE ods_view_detailsADD KEY index_id (index_id);
```
> fix upgrade script

- www/include/configuration/configObject/host/DB-Func.php
Fix 16 legacy style problems, corrections requested by the CI in past builds...
There should be no impact on nothing... but If you found something, please tell me ;)
> fix: style correction from CI

- www/include/common/common-Func.php
- www/include/core/header/header.php
Fix default user page when user is already logged in (access to http://<ip_address>/centreon)
**Fixes** MON-5369
- Modify user default page
- Log out & Log in
- Go to root page : http://<ip_address>/centreon
This test needs to be done with admin and non admin users
> fix(ui): fix user default page redirection

- www/include/views/graphs/generateGraphs/generateImage.php
Fix graph image generation when mysql strict mode is enabled
**Fixes** MON-5129 MON-5181
> fix(graph): fix graph image generation with mysql strict mode

- config/packages/validator/validation.yaml
- src/Centreon/Domain/Acknowledgement/AcknowledgementService.php
Fix acknowledgements POST endpoint
https://docs.centreon.com/api/centreon-web/#tag/Acknowledgement/paths/~1monitoring~1hosts~1{host_id}~1acknowledgements/post
https://docs.centreon.com/api/centreon-web/#tag/Acknowledgement/paths/~1monitoring~1hosts~1{host_id}~1services~1{service_id}~1acknowledgements/post
**Fixes** MON-5359
Add acknowledgement on host & service using API
> fix(api): fix acknowledgements endpoint on hosts and services

- www/include/monitoring/acknowlegement/xml/broker/makeXMLForAck.php
- www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
avoid injection on status popup
**Fixes** # (secu)
> fix(secu): avoid injection on status popup

- webpack.config.js
Move webpack plugins order
**Fixes** MON-5439
Check resource downtime icon is displayed in events view page
> fix(build): fix buildof svg components

- src/CentreonRemote/Application/Webservice/CentreonConfigurationRemote.php
- www/class/centreon-clapi/centreonInstance.class.php
- www/include/configuration/configServers/DB-Func.php
Check if FILTER_VALIDATE_DOMAIN is a valid FILTER_FLAG_HOSTNAME
**Fixes** #8404
> fix(security): correct PR #8404

- www/class/centreon-knowledge/wikiApi.class.php
Fix https://github.com/centreon/centreon/pull/8124
Fix https://github.com/centreon/centreon/issues/7790
Set wrong knowledge base information. You get cookies in /tmp each 5 minutes.
> fix(kb): store kb cookie  in memory and manage new version

- www/include/monitoring/acknowlegement/xml/broker/makeXMLForAck.php
- www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php
FIX DT and ACK details popin
This PR is not intended for 19.10 or 19.04 without strict mode enabled. Check this PR instead https://github.com/centreon/centreon/pull/8708
**Fixes** # (MON-5399)
> fix(BE): remove popup errors in logs when altering http request

- src/Centreon/Infrastructure/Webservice/WebserviceAutorizeRestApiInterface.php
- www/api/class/webService.class.php
Check webservice athorization by running authorize method
Catch error in authorize method to allow to throw specific exception (eg: invalid license)
**Fixes** BAM-1005
Check APIv1
> fix(APIv1): fix authorize check on webservices added directly in container

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Domain/HostConfiguration/HostConfigurationService.php
- src/Centreon/Domain/HostConfiguration/HostMacro.php
- src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationRepositoryInterface.php
- src/Centreon/Domain/HostConfiguration/Interfaces/HostConfigurationServiceInterface.php
- src/Centreon/Domain/Monitoring/MonitoringService.php
- src/Centreon/Domain/ServiceConfiguration/Interfaces/ServiceConfigurationRepositoryInterface.php
- src/Centreon/Domain/ServiceConfiguration/Interfaces/ServiceConfigurationServiceInterface.php
- src/Centreon/Domain/ServiceConfiguration/ServiceConfigurationService.php
- src/Centreon/Domain/ServiceConfiguration/ServiceMacro.php
- src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
- src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
Add recursivity to find host and service macros.
> fix(api): Add recursivity to find host and service macros.

- www/install/insertBaseConf.sql
> chore(install): upgrade version to 20.04.3

- features/bootstrap/LanguageSelectionContext.php
Replace the spin timeout from 5sec to 60sec (used for CI jobs only)
> enh(TA): increase timeout to 60 sec

- lib/perl/centreon/script/centcore.pm
- www/class/centreon-clapi/centreonInstance.class.php
Add missing commit for centcore
> fix(security): add missing commit from PR #8456

- www/install/insertBaseConf.sql
- www/install/php/Update-19.10.13.php
> enh(install): upgrade to 19.10.13

- doc/en/release_notes/centreon-19.04/centreon-19.04.16.rst
- doc/fr/release_notes/centreon-19.04/centreon-19.04.16.rst
- www/install/insertBaseConf.sql
- www/install/php/Update-19.04.16.php
> enh(install): upgrade to 19.04.16

- www/include/configuration/configServers/listServers.ihtml
fix display condition for #8686 
> fix(gorgone) fix display button for central

- Jenkinsfile
Start to integrate CentOS 8 in build.
Try to install Centreon on CentOS 8. It should work.
> Run unit tests, packaging and bundle on CentOS 8

- .github/PULL_REQUEST_TEMPLATE.md
- Drop support of 2.8.x and 18.10.x
> enh(README): add new version to target serie

- config/packages/validator/validation.yaml
- src/Centreon/Application/Controller/AcknowledgementController.php
- src/Centreon/Application/Controller/DowntimeController.php
- src/Centreon/Domain/Monitoring/Resource.php
Several ACLs fixes :
* Check allowed actions on services when dt/ack is done via host (withServices option)
* Check Disack acl instead of ack acl on acknowledgement
**Fixes** MON-5150
> fix(acl): fix acl on ack and downtime using APIv2

- config/packages/serializer/Centreon/MonitoringServer.MonitoringServer.yml
Adding a short serialization of the monitoring server object.
> enh(monitoring server): Updating the serialization file of monitoring server

- lib/perl/centreon/reporting/CentreonLog.pm
- www/include/eventLogs/xml/data.php
Manage 0 values inserted by broker in logs table
**Fixes** MON-5569
> fix(reporting): fix host availability related to broker changes

- lib/perl/centreon/reporting/CentreonDownTime.pm
Use actual_end_time instead of end_time to manage : 
- downtime cancellation
- floating downtime
**Fixes** MON-5551
> fix(reporting): fix reporting issues related to downtime cancellation

- config/packages/validator/validation.yaml
- src/Centreon/Application/Controller/AcknowledgementController.php
- src/Centreon/Domain/Monitoring/Resource.php
Aknowledgement did not work cause of a typo issue of the validation group constant
**Fixes** MON-5150
Try to acknowledge using events view page
> fix(api): fix acknowledgement validation group

- www/include/configuration/configServers/popup/popup.php
secure the access to the gorgone configuration popup
> fix(security) gorgone popup check session and id

- www/include/views/graphTemplates/DB-Func.php
- www/include/views/graphTemplates/formGraphTemplate.php
- www/include/views/graphTemplates/graphTemplates.php
This PR addresses security issues found of the graph template page.
- bind values for the requests
- sanitize imputs
- remove dead code (enable/disable feature)
See the JIRA ticket for a description
> fix(secu): secure graph template page

- www/include/home/customViews/triggers/loadServiceFromHost.php
> fix(security) fix sql injection on loadServiceFromHost

- config/Modules/Centreon.yaml
- config/packages/serializer/Centreon/Configuration.Icon.Icon.yml
- config/packages/serializer/Centreon/Configuration.Icon.yml
- config/routes/Centreon/configuration/icon.yaml
- doc/API/centreon-api-v2.yaml
- src/Centreon/Application/Controller/Configuration/IconController.php
- src/Centreon/Application/Normalizer/IconUrlNormalizer.php
- src/Centreon/Domain/Configuration/Icon/Icon.php
- src/Centreon/Domain/Configuration/Icon/IconService.php
- src/Centreon/Domain/Configuration/Icon/Interfaces/IconRepositoryInterface.php
- src/Centreon/Domain/Configuration/Icon/Interfaces/IconServiceInterface.php
- src/Centreon/Infrastructure/Icon/IconRepositoryRDB.php
Add following endpoint : /configuration/icons
**Fixes** BAM-1017
Check api documentation to validate endpoint
> feat(api): add endpoint to list configuration icons

- www/include/views/graphs/exportData/ExportCSVServiceData.php
Due to security fixes, an error has been introduced which broke the csv exportdata process.
My mistake, found by the QA :)
> fix(ExportCSVServiceData): wrong variable name used during export

- www/class/centreonHost.class.php
- www/class/centreonService.class.php
- www/include/monitoring/objectDetails/xml/hostSendCommand.php
- www/include/monitoring/objectDetails/xml/serviceSendCommand.php
- Sanitize and filter inputs
- Fix control access for users under ACL
See related JIRA ticket
> fix(secu): secure host and service sendCommand actions

- .gitignore
update gitignore file to ignore .sonar-scanner files
moving .vscode in the right block
> enh(chore): update gitignore

- www/include/common/common-Func.php
- www/include/common/javascript/color_picker.html
- www/include/common/javascript/color_picker.php
- www/include/common/javascript/color_picker_mb.js
- www/include/common/javascript/colpick.html
- www/include/common/javascript/functions.js
> fix(chore): correct wrong encoding on UTF-8 characters

- www/class/centreonMedia.class.php
Manage the modification of previously created folder with wrong rights.
**Fixes** # (MON-5686)
> fix(chore): correct rights of already created icon folder

- www/include/configuration/configKnowledge/display-hostTemplates.php
- www/include/configuration/configKnowledge/display-hosts.php
- www/include/configuration/configKnowledge/display-serviceTemplates.php
- www/include/configuration/configKnowledge/display-services.php
- www/include/configuration/configKnowledge/search.php
This PR attend to fix some vulnerabilities into the differents Knowledge Base pages.
**Fixes** # 
MON-5521
MON-5522
MON-5523
MON-5524
> fix(secu): correct vulnerabilities in Knowledge Base pages

- lib/perl/centreon/script/centcore.pm
- www/include/configuration/configGenerate/xml/postcommand.php
Post-generation commands are executed by apache user, they must be executed by centreon user
> fix(security) post cmd execute by centcore

- www/include/configuration/configGenerate/xml/postcommand.php
Post-generation commands are executed by apache user, they must be executed by centreon user
#8800
> fix(security) post cmd execute by gorgone

- www/include/configuration/configGenerate/xml/postcommand.php
> fix(cmd) execute post cmd on central

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/class/centreonCustomView.class.php
- www/class/centreonTraps.class.php
- www/include/configuration/configObject/traps/formTraps.php
This PR fixes some SQL injection vulnerabilities inside the SNMPTrap formulary and correctly handle errors with bad OID
**Fixes** # 5525
> fix(security): fix sql injection vulnerabilities in traps

- package-lock.json
- package.json
Upgrade kind-of dependency to latest version (6.0.3)
**Fixes** # (dependabot)
> fix(secu): upgrade kind-of dependency

- config/packages/prod/Centreon.yaml
- config/packages/serializer/Centreon/Filter.Filter.yml
- doc/API/centreon-api-v2.yaml
- src/Centreon/Application/Controller/FilterController.php
- src/Centreon/Domain/Filter/FilterService.php
- src/Centreon/Domain/Filter/Interfaces/FilterRepositoryInterface.php
- src/Centreon/Domain/Filter/Interfaces/FilterServiceInterface.php
- src/Centreon/Infrastructure/Filter/FilterRepositoryRDB.php
- tests/php/Centreon/Application/Controller/FilterControllerTest.php
- fix dependency injection in user filter repository
- return created filter in response
- add criterias property in filter listing
- fix filter creation in api documentation
**Fixes** MON-4889
Check API documentation to test endpoints
> fix(di): fix dependency injection in user filter repository

- www/include/Administration/performance/viewData.ihtml
- www/include/Administration/performance/viewData.php
- www/include/Administration/performance/viewMetrics.php
fix sql injection from Administration > Parameters > Data
fix/replace with select2 poller filter
> Mon 5519 sql injection

- www/class/centreon-clapi/centreonHost.class.php
- www/class/centreon-clapi/centreonService.class.php
add missing break in case to add geo_coords
> fix(clapi) fix geo_coords

- www/install/insertBaseConf.sql
Simple upgrade of the centreon-web module for release.
> chore(install): update version to 20.04.5.

- www/include/Administration/brokerPerformance/brokerPerformance.php
> fix(security): fix vulnerability for file loading (#7227)

- www/install/insertBaseConf.sql
> chore(install): update version to 19.10.15

- sonar-project.properties
> enh(chore): optimize sonarqube conf file

- sonar-project.properties
Fix the build. As sonarqube is unable to find two folders.
> fix(chore): remove folders in sonar conf

- doc/en/release_notes/centreon-19.04/centreon-19.04.18.rst
- doc/fr/release_notes/centreon-19.04/centreon-19.04.18.rst
- www/install/insertBaseConf.sql
> chore(install): update version to 19.04.18

- www/api/class/centreon_wiki.class.php
This PR fix a security breach into knowledge base form.
**Fixes** #4549 #4550
> fix(wiki): sanitize db test connection

- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
Prepare release notes
**Fixes** MON-5553
> doc(release): prepare 19.10.16 release notes

- doc/en/release_notes/centreon-19.04.rst
- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.04.rst
- doc/fr/release_notes/centreon-19.10.rst
> Add missing releases notes 19.10.x

- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
Centreon Web 19.10.16 release note
> enh(doc): add Centreon Web 19.10.16 release notes

- www/include/configuration/configObject/contact/formContactLight.ihtml
Add email field in contact form for Remote Server.
Refs: MON-5563
* Install a Remote Server,
* Create or edit a contact,
* Set an email address in dedicated field.
> enh(configuration): add contact email in form template for remote server

- www/include/configuration/configObject/host_categories/DB-Func.php
Fix 19.04.x Acceptance Test
**Fixes** #MON-5907
> fix(chore): correct hostCategory query

- www/include/configuration/configObject/service_categories/DB-Func.php
Fix Acceptance Test for 19.04.x
> fix(chore): correct Service Category Query

- www/api/class/centreon_configuration_service.class.php
Add possibility to see anomaly detection services in "Monitoring > Event Logs" menu
> enh(api): add possibility to see anomaly detection services

- www/install/php/Update-20.10.0.post.php
Correct post upgrade query concatenation
**Fixes** # (MON-5697)
> fix(upgrade): correct query

- www/front_src/src/Resources/Actions/Resource/Disacknowledge/api/index.ts
- www/front_src/src/Resources/Actions/index.test.tsx
This fixes the call to disacknowledge (delete instead of post).
> fix(resource-status): Fix disacknowledge call

- bin/registerServerTopology-Func.php
- bin/registerServerTopology.php
> fix(platformstatus): correct requirement

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
- www/include/Administration/parameters/general/form.php
Rename "Test Proxy Configuration" by "Test Internet Connection"
> enh(proxy): rename test proxy button

- package-lock.json
- www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
- www/front_src/src/Resources/Listing/columns/index.tsx
- www/front_src/src/Resources/truncate.ts
> enh(resource-status/Listing): Limit information character count to 180 characters

- www/front_src/src/Resources/Actions/Resource/Downtime/index.tsx
translate snackbar when adding downtime
**Fixes** MON-6079
> fix(lang): translate snackbar when adding downtime

- www/front_src/src/Resources/Details/tabs/Shortcuts/Shortcuts.tsx
- www/front_src/src/Resources/Listing/columns/State/index.tsx
- www/front_src/src/Resources/Listing/index.test.tsx
- www/front_src/src/Resources/models.ts
fix ack & downtime tooltips on hover
**Fixes** MON-6080
check downtime and acknowledgement tooltips
> fix(ui): fix ack & downtime tooltips on hover

- www/include/Administration/parameters/remote/formRemote.ihtml
- www/include/Administration/parameters/remote/formRemote.php
visibility of apiPeerValidation
> fix(form) visibility of apiPeerValidation

- www/front_src/src/Resources/Graph/Performance/formatMetricValue/index.ts
> fix(resource-status/Graph): convert base to Number before formatting

- www/install/php/Update-20.10.0-beta.2.php
- www/install/php/Update-20.10.0-beta.2.post.php
- www/install/sql/centreon/Update-DB-20.10.0-beta.2.sql
correct parent_id computation
fix notice
> fix(upgrade): correct beta2 script

- src/Centreon/Domain/Repository/InformationsRepository.php
manage iscentral according to isremote
> fix(db) manage iscentral according to isremote

- unattended.sh
Update unattended.sh to install 20.10.
Run unattended.sh. Centreon 20.10 should be installed.
> Update unattended.sh for 20.10.

- www/front_src/src/Resources/Graph/Performance/timeSeries.ts
> fix(resource-status/Graph): Fix invalid date with null lower limit

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Application/Controller/PlatformInformationController.php
- src/Centreon/Application/Controller/PlatformTopologyController.php
- src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
- src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyServiceInterface.php
- src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
- src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
- tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
- tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
Fix the issue on central when adding a remote type platform
Refacto the controller and the service
**Fixes** # (MON-6107)
> fix(API): fix register a remote on a central and refacto service

- package-lock.json
Fixed in centreon-ui, this only updates the package-lock file.
> fix(resource-status/Filter): Fix error when typing a special character in the search bar 

- lang/fr_FR.UTF-8/LC_MESSAGES/help.po
- www/class/centreonAuth.SSO.class.php
- www/include/Administration/parameters/DB-Func.php
- www/include/Administration/parameters/general/form.ihtml
- www/include/Administration/parameters/general/form.php
- www/include/Administration/parameters/general/help.php
* Add refresh token method
* Add logout method is session is over
* Save correctly openid connect mode
**Fixes** #9025
> fix(openId): improve authentication

- www/class/config-generate-remote/PlatformTopology.php
fix remote parent id to null in export
> fix(export) remote parent id null

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Domain/Engine/EngineConfiguration.php
- src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
- src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
- tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
- www/include/Administration/parameters/DB-Func.php
Allow spaces on host
More accurate check for RFC compliant check
**Fixes** # (MON-6093)
> fix(API): enhance hostname and name check

- bin/registerServerTopology-Func.php
- bin/registerServerTopology.php
Now API don't send back the status code in the response body. Now we don't take it in account 
> fix(platformstatus): correct script response message

- www/front_src/src/Provider/index.tsx
detect browser locale when not given by backend
**Fixes** MON-6133
> fix(lang): detect browser locale when needed

- package-lock.json
- www/front_src/src/Resources/Filter/useFilter.ts
- www/front_src/src/components/header/getResourcesUrl.ts
- www/front_src/src/components/header/hostMenu/index.test.tsx
- www/front_src/src/components/header/serviceStatusMenu/index.test.tsx
The result isn't pretty, but we'll introduce a new (flat) format for the next minor or major.
> fix(resource-status/URLqueryParameters): encode URL parameters and override search when redirecting from top counter

- src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
Remove not used import in platform topology repository interface
> enh(API): remove useless import in interface

- src/CentreonRemote/Application/Validator/WizardConfigurationRequestValidator.php
Fix thrown message using a variable which has not been set
> fix(wizard): initialize message thrown variable

- bin/registerServerTopology.php
> fix(register) fix port location

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> fix(i18n): Fix warning translation

- www/front_src/src/Resources/Details/index.test.tsx
- www/front_src/src/Resources/Details/tabs/Timeline/Event.tsx
- www/front_src/src/Resources/Details/tabs/Timeline/Events/index.tsx
> fix(resource-status/Timeline): Do not display downtime end date if not available

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> fix(i18n): Add pending translation

- bin/registerServerTopology.php
**Do not merge until the 20.10.0 is released**
Add spaces after each script's queries
before : 
```
Are you using a proxy ? (y/n)n
...
Which IP do you want to use as CURRENT NODE IP ?1
```
after
```
Are you using a proxy ? (y/n) n
...
Which IP do you want to use as CURRENT NODE IP ? 1
```
> enh(script): add missing spaces

- www/front_src/src/Resources/Details/tabs/Services/index.tsx
This fixes a few inconsistencies in the Services tab display:
- Switch to details tab when a Service is clicked
- Display a message when no Services are found
- Avoid displaying previous services when a Service is clicked
> fix(resource-status/Services): Fix services tab inconsistencies

- package-lock.json
- www/front_src/src/Resources/Filter/index.test.tsx
This encode listing parameters before sending them to the API. 
- Search something containing a '+' character
- Make sure the request sent to the API is properly encoded.
> fix(resource-status/filter/search): encode listing parameters

- www/install/insertBaseConf.sql
set version to 20.10.0 in insertBaseConf.sql
> fix(install): set version to 20.10.0

- www/install/insertBaseConf.sql
> fix(install): set version to 20.10.0 (#9166)

- doc/en/release_notes/centreon-19.04/centreon-19.04.20.rst
- doc/fr/release_notes/centreon-19.04/centreon-19.04.20.rst
> enh(doc): add Centreon 19.04.20 RN

- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
Add Centreon Web 19.10.17 release notes
> enh(doc): Add Centreon Web 19.10.17 RN

- www/include/configuration/configObject/contactgroup/DB-Func.php
Available Cross-site Scripting (XSS) Stored/Persistent in "Configuration > Users > ContactGroups" form
Sanitize ContactGroups form
see MON-5916
> fix(security) sanitize contact groups

- www/include/monitoring/status/Common/updateContactParam.php
- www/include/monitoring/status/Common/updateContactParamHostGroups.php
- www/include/monitoring/status/Common/updateContactParamServiceGroups.php
Sanitize instance_id, hostgroups and servicegroups parameters
**Fixes** # (MON-4217)
> fix(secu): sanitize filter's XHR parameters

- tests/end_to_end/.gitignore
- tests/end_to_end/cypress.json
- tests/end_to_end/cypress/.eslintrc.json
- tests/end_to_end/cypress/README.md
- tests/end_to_end/cypress/build-docker-compose.js
- tests/end_to_end/cypress/fixtures/users/admin.json
- tests/end_to_end/cypress/integration/Login.feature
- tests/end_to_end/cypress/integration/Login/login.ts
- tests/end_to_end/cypress/plugins/index.ts
- tests/end_to_end/cypress/start-env.sh
- tests/end_to_end/cypress/stop-env.sh
- tests/end_to_end/cypress/support/commands.ts
- tests/end_to_end/cypress/support/index.ts
- tests/end_to_end/cypress/tsconfig.json
- tests/end_to_end/cypress/webpack.config.js
- tests/end_to_end/package-lock.json
- tests/end_to_end/package.json
For a necessity of test automation on the UX/UI Front-End side, the "End To End" part is initiated with the Cypress.io framework.
Refs: MON-6329
> feat(test): Add 1ft impl. E2E tests (cypress.io)

- tests/end_to_end/package-lock.json
- tests/end_to_end/package.json
> feat(cypress): upgrade to 6.0.0

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.8.php
Set version to 20.04.8 in files
> chore(install): update to version 20.04.8

- www/install/insertBaseConf.sql
- www/install/php/Update-19.10.18.php
> chore(install): update to version 19.10.18.

- www/api/class/centreon_administration_aclgroup.class.php
- www/api/class/centreon_administration_widget.class.php
- www/api/class/centreon_configuration_command.class.php
- www/api/class/centreon_configuration_contact.class.php
- www/api/class/centreon_configuration_contactgroup.class.php
- www/api/class/centreon_configuration_graphcurve.class.php
- www/api/class/centreon_configuration_graphtemplate.class.php
- www/api/class/centreon_configuration_host.class.php
- www/api/class/centreon_configuration_hostcategory.class.php
- www/api/class/centreon_configuration_hostgroup.class.php
- www/api/class/centreon_configuration_hosttemplate.class.php
- www/api/class/centreon_configuration_manufacturer.class.php
- www/api/class/centreon_configuration_meta.class.php
- www/api/class/centreon_configuration_poller.class.php
- www/api/class/centreon_configuration_service.class.php
- www/api/class/centreon_configuration_service_severity.class.php
- www/api/class/centreon_configuration_servicecategory.class.php
- www/api/class/centreon_configuration_servicegroup.class.php
- www/api/class/centreon_configuration_servicetemplate.class.php
- www/api/class/centreon_configuration_timeperiod.class.php
- www/api/class/centreon_configuration_timezone.class.php
- www/api/class/centreon_configuration_trap.class.php
- www/api/class/centreon_metric.class.php
- www/api/class/centreon_monitoring_poller.class.php
- www/api/class/centreon_performance_service.class.php
Check page_limit consitency to avoid to throw platform technical data when query is failing
**Fixes** # (MON-5531)
> fix(secu): check page_limit consistency on XHR

- www/include/options/accessLists/actionsACL/listsActionsAccess.php
- www/include/options/accessLists/groupsACL/listGroupConfig.php
- www/include/options/accessLists/resourcesACL/listsResourcesAccess.php
This PR fix an issue where ACL search parameters was vulnerable to injections.
**Fixes** # MON-5925 MON-5926 MON-5927
> fix(ACL): sanitize ACL search parameters

- Jenkinsfile
Remove Centos6 from JenkinsFILE
> remove centos6 from Jenkinsfile

- www/include/options/accessLists/actionsACL/listsActionsAccess.php
- www/include/options/accessLists/groupsACL/listGroupConfig.php
- www/include/options/accessLists/resourcesACL/listsResourcesAccess.php
This PR fix an issue where ACL search parameters was vulnerable to injections.
**Fixes** # MON-5925 MON-5926 MON-5927
> fix(ACL): sanitize ACL search parameters 

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Domain/Common/Assertion/Assertion.php
- src/Centreon/Domain/Common/Assertion/AssertionException.php
- tests/php/Centreon/Domain/Common/AssertionTest.php
- tests/php/Centreon/Domain/Common/TestAssertion.php
Add new asserts (notEmpty and notNull).
> enh(assert): Add new asserts

- config/routes/Centreon/platform.yaml
- doc/API/centreon-api-v2.yaml
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Application/Controller/PlatformTopologyController.php
- src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyRepositoryInterface.php
- src/Centreon/Domain/PlatformTopology/Interfaces/PlatformTopologyServiceInterface.php
- src/Centreon/Domain/PlatformTopology/PlatformTopologyService.php
- src/Centreon/Infrastructure/PlatformTopology/PlatformTopologyRepositoryRDB.php
- tests/api/features/PlatformTopology.feature
- tests/php/Centreon/Application/Controller/PlatformTopologyControllerTest.php
- tests/php/Centreon/Domain/PlatformTopology/PlatformTopologyServiceTest.php
Provide a DELETE /platform/topology/id endpoint.
**Fixes** #MON-6448
> feat(API): Delete a platform from topology

- .github/CODEOWNERS
split lines in codeowners file
> fix(ci): split lines in codeowners file

- www/include/reporting/dashboard/template/viewHostGroupLog.ihtml
- www/include/reporting/dashboard/template/viewHostLog.ihtml
- www/include/reporting/dashboard/template/viewServicesGroupLog.ihtml
- www/include/reporting/dashboard/template/viewServicesLog.ihtml
- www/include/reporting/dashboard/viewHostGroupLog.php
- www/include/reporting/dashboard/viewHostLog.php
- www/include/reporting/dashboard/viewServicesGroupLog.php
- www/include/reporting/dashboard/viewServicesLog.php
This PR fix an issue where centreon_token wasn't evaluate in Dashboard pages
**Fixes** # MON-3201
> fix(security): Correctly evaluate centreon_token 

- doc/en/release_notes/centreon-2.8/centreon-2.8.34.rst
- doc/fr/release_notes/centreon-2.8/centreon-2.8.34.rst
added missing xss, media upload and clear text password fixes to the RN
> Update RN 2.8.34 with missing fixes

- Jenkinsfile
separate analyse of checkstyle results for phpcs & phpstan
**Fixes** MON-6419
Check results in CI
> enh(ci): separate analyse of checkstyle results

- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
Add release notes for 19.10.18
> enh(doc): Add Centreon Web 19.10.18 RN

- www/api/class/centreon_monitoring_externalcmd.class.php
- www/class/centreonExternalCommand.class.php
This PR aims to control what the user can send in centcore pipe using the API. It will check that user can (_or not_) submit a specific command regarding its ACLs
Procedure is described in the JIRA ticket.
> fix(secu): check ACL rights when sending externalcommands

- www/api/class/centreon_metric.class.php
Correct style (PSR2 instead of PSR12)
Set the "for" limit before the loop to avoid to calculate it at each occurence
**Fixes** # (build)
> fix(chore): fix CI job

- www/install/insertBaseConf.sql
> chore(install): update to version 20.04.9

- doc/en/release_notes/centreon-2.8/centreon-2.8.35.rst
- doc/en/release_notes/centreon-2.8/index.rst
- doc/fr/release_notes/centreon-2.8/centreon-2.8.35.rst
- www/install/insertBaseConf.sql
- www/install/sql/centreon/Update-DB-2.8.34_to_2.8.35.sql
Update version number in files to 2.8.35
> chore(install): update to version 2.8.35

- www/install/insertBaseConf.sql
> chore(install): update to version 20.10.3

- www/install/insertBaseConf.sql
> chore(install): update version to 19.10.19

- www/include/configuration/configServers/DB-Func.php
- www/include/configuration/configServers/listServers.php
> enh(perf): improve poller performance list for 20.04.x

- SECURITY.md
Update the table according the new key (eg. new expiration date).
> Update the table according the new key

- www/include/reporting/dashboard/common-Func.php
Backport of https://github.com/centreon/centreon/pull/9372
> fix(secu): sanitize host dashboard

- www/include/Administration/parameters/ldap/form.php
avoid injection in LDAP form
**Fixes** # (MON-6623)
> fix(secu): avoid injection in LDAP form

- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
> enh(doc): Centreon Web 19.10.19 RN

- www/install/insertBaseConf.sql
> chore(install):update version to 20.04.10

- www/install/insertBaseConf.sql
> chore(install):update version to 19.10.20

- doc/en/release_notes/centreon-2.8/centreon-2.8.36.rst
- doc/en/release_notes/centreon-2.8/index.rst
- doc/fr/release_notes/centreon-2.8/centreon-2.8.36.rst
- doc/fr/release_notes/centreon-2.8/index.rst
- www/install/insertBaseConf.sql
- www/install/sql/centreon/Update-DB-2.8.35_to_2.8.36.sql
Update version to 2.8.36
@lpinsivy Kindly check placeholder release notes
> chore(install): update to version 2.8.36

- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
> enh(doc): add Centreon 19.10.20 RN

- www/install/insertBaseConf.sql
- www/install/php/Update-19.10.21.php
> chore(install): update to version 19.10.21

- www/include/core/login/template/login.ihtml
Update copyright date
**Fixes** # (MON-6781)
> enh(chore): update copyrigth on login page

- www/install/insertBaseConf.sql
- www/install/php/Update-20.10.5.php
> chore(install):update version to 20.10.5

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.11.php
> chore(install):update version to 20.04.11

- doc/en/release_notes/centreon-2.8/centreon-2.8.37.rst
- doc/en/release_notes/centreon-2.8/index.rst
- doc/fr/release_notes/centreon-2.8/centreon-2.8.37.rst
- doc/fr/release_notes/centreon-2.8/index.rst
- www/install/insertBaseConf.sql
- www/install/sql/centreon/Update-DB-2.8.36_to_2.8.37.sql
> chore(install):update version to 2.8.37

- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
> enh(doc): Add Web 19.10.21 RN

- Jenkinsfile
- sonar-project.properties
- www/main.get.php
Transition from sonarQube community to dev edition 
**Fixes** # (MON-5609)
****Requires** https://github.com/centreon/centreon-build/pull/445**
> enh(chore): integrate sonarQube dev edition

- Jenkinsfile
- sonar-project.properties
change target instance key and adapt configuration
**Fixes** # (MON-5609)
> fix(chore): 19.10.x job

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.12.php
> chore(install): update version to 20.04.12

- composer.json
- composer.lock
- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
- symfony.lock
- www/install/insertBaseConf.sql
- www/install/php/Update-19.10.22.php
> chore(install): update to version 19.10.22

- doc/API/centreon-api-v2.1.yaml
Fix openApi online documentation
> fix(doc): openApi correction

- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
Centreon Web 19.10.22 release note
> enh(doc): Add Web 19.10.22 RN

- www/class/centreonConfigCentreonBroker.php
- www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
- www/include/configuration/configCentreonBroker/formCentreonBroker.php
fix broker form. Please check the comment above
> fix(chore): fix broker form

- src/CentreonRemote/Domain/Resources/RemoteConfig/CfgCentreonBroker.php
- www/class/centreonConfigCentreonBroker.php
- www/include/configuration/configCentreonBroker/DB-Func.php
- www/include/configuration/configCentreonBroker/formCentreonBroker.ihtml
- www/include/configuration/configCentreonBroker/formCentreonBroker.php
revert wrongly backported commits
> revert(chore): broker logs

- unattended.sh
* add firewall rules for broker bbdo and gorgone zmq
* use central ip in the URL to the UI provided at the end of the execution
* don't provide link to further doc if there is nothing more to do
> enhance unattended

- unattended.sh
Refers to https://github.com/centreon/centreon/pull/9619
There are conflits with this other PR and there shouldn't.
So I create a new PR from a new branch that I newly created from master.
> enh(unattended): new version of unattended for 21.04 release

- src/Centreon/Infrastructure/HostConfiguration/HostConfigurationRepositoryRDB.php
- src/Centreon/Infrastructure/ServiceConfiguration/ServiceConfigurationRepositoryRDB.php
To support Mysql < 8 and MariaDB < 12.2, we change recursive requests.
It should change nothing.
> MON-6867: rewrite recursive request (20.10.x)

- www/include/views/graphs/graph-periods.php
Same as https://github.com/centreon/centreon/pull/9735 for 2.8.x
See Jira issue for explanations
> sec(graph-periods): secure post entries

- www/include/views/graphs/graph-split.php
Same as https://github.com/centreon/centreon/pull/9738 for 2.8.X
See JIRA issue
> sec(graph-split): secure data from request

- webpack.config.js
This fixes a blank page appearing on Firefox ESR 52
> fix(webpack): Keep only relevant moment locales in the webpack bundle

- www/install/php/Update-20.10.7
Update version to 20.10.7 in files.
> chore(install): update to version 20.10.7

- www/install/insertBaseConf.sql
- www/install/php/Update-19.10.23.php
Update version to 19.10.23 in files.
> chore(install): update version to 19.10.23

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.13.php
Update version to 20.04.13 in files
> chore(install): update to version 20.04.13

- www/include/views/graphs/graph-split.php
Correct query called on split graph
> fix(graph): correct graph split query

- .github/CODEOWNERS
translation files should be handled by fe and be
> enh(codeowners): translation files should be handled by fe and be

- www/include/configuration/configObject/host/listHost.php
> fix(host) fix XSS in the alias field of host

- doc/en/release_notes/centreon-19.10.rst
- doc/fr/release_notes/centreon-19.10.rst
> enh(release): Add Centreon Web 19.10.23 RN

- www/include/views/componentTemplates/DB-Func.php
- www/include/views/componentTemplates/componentTemplates.php
- www/include/views/componentTemplates/formComponentTemplate.php
Same as #9762 but for 2.8.x
See Jira issue
> sec(componentTemplate): secure the page

- www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
Same as https://github.com/centreon/centreon/pull/9781 for 2.8.x
See Jira ticket
> sec(export): secure hostgroup log export

- .github/ISSUE_TEMPLATE/bug_report.md
Correct php log path
**Relates to**  https://github.com/centreon/centreon/pull/9725
> enh(chore): update issue template

- Jenkinsfile
fix jenkins parallel os steps on stable builds
Check CI
> fix(ci): fix jenkins parallel os steps on stable builds

- www/include/views/graphs/generateGraphs/generateImage.php
Same as https://github.com/centreon/centreon/pull/9787/files for 2.8.x
See Jira issue
> sec(generateImage): secure entries

- www/class/centreon-knowledge/procedures_Proxy.class.php
- www/include/configuration/configKnowledge/proxy/proxy.php
This PR intends to sanitize KB request parameters
**Fixes** # MON-7079
> fix(security): sanitize kb request parameters

- .github/CODEOWNERS
do not assign reviewers on translation files
> enh(chore): do not assign reviewers on translation files

- www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
FIX SQL ERROR request 
Check curl command provided in MON-7081
> fix(csv_HostGroupLogs): fix sql search on session

- www/include/reporting/dashboard/csvExport/csv_HostGroupLogs.php
Other fix from validation
Jira issue
> fix(csv_HostGroupLogs): fix variable naming

- www/install/insertBaseConf.sql
- www/install/php/Update-20.10.8.php
Update version to 20.10.8 in files
> chore(install): update to version 20.10.8

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.14.php
Update version to 20.04.14 in files.
> chore(install): update to version 20.04.14

- doc/en/release_notes/centreon-2.8/centreon-2.8.38.rst
- doc/en/release_notes/centreon-2.8/index.rst
- doc/fr/release_notes/centreon-2.8/centreon-2.8.38.rst
- doc/fr/release_notes/centreon-2.8/index.rst
> enh(doc): add web 2.8.38 RN

- www/install/insertBaseConf.sql
- www/install/sql/centreon/Update-DB-2.8.37_to_2.8.38.sql
Update version to 2.8.38 in files.
> chore(install): update version to 2.8.38

- unattended.sh
Since centos8 has become centos stream, the release name has changed into centos-stream-release.
- [x ] Patch fixing an issue (non-breaking change)
- [x ] 21.04.x
- [x ] 21.10.x (master)
> feat(unattended): add case centos-stream-release

- unattended.sh
Using ${1} and ${2} refered to the first and second argument passed to the function.
As second argument had a list, it was expanded and only the first item was displayed.
- [x ] 21.04.x
- [x ] 21.10.x (master)
> enh(unattended): enhance logger to display full message

- www/install/php/Update-20.10.8.php
- www/install/sql/centreon/Update-DB-20.10.8.sql
same than #9869 but for 20.10.x branch
> fix(update): insert module meta relation if exist

- src/CentreonRemote/Application/Webservice/CentreonTaskService.php
The addImportTaskWithParent must be present for 20.04.x to import data into database
> fix(remote): re-add missing function

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.15.php
Update version to 20.04.15 in files.
> chore(install): update version to 20.04.15

- www/install/insertBaseConf.sql
- www/install/php/Update-20.10.9.php
Update version to 20.10.9 in files
> chore(install): update to version 20.10.9

- setupTest.js
- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.16.php
Update version to 20.04.16 in files.
> chore(install): update version to 20.04.16

- SECURITY_ACK.md
Add two reporter's names to the security acknowledgement page
> enh(ACK): add reporters

- Jenkinsfile
Retrieve quality gate status with sonar api and listening to the coming webhook in order to avoid ten minutes timeout.
> fix(ci): quality gate timeout management

- Jenkinsfile
> enh(chore): remove CI's timeout workaround

- unattended.sh
In Centos 8.2, the powertools repo is named PowerTools.
The script checked if a centos-release-* was returned, and used powertools for any centos release which lead to a
non functionnal installation (missing a part of php packages)
A case was added for centos 8.2.x versions to handle this difference versus centos 8.3 and centos-stream
- [x ] 21.04.x
- [x ] 21.10.x (master)
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so …
> enh(install): add case for centos 8.2 release for PowerTools

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> fix(typo): fix FR typo

- README.md
> enh(readme): add missing title closing

- SECURITY_ACK.md
Add of a contributor : Gaurang Mahetal
> doc(secu): add vulnerability reporter

- Jenkinsfile
remove sleep on 20.04.x branch
> enh(chore): remove sleep step on 20.04

- Jenkinsfile
remove sleep on 21.04.x branch
> enh(chore): remove sleep step on 21.04

- composer.json
- composer.lock
- config/json_validator/latest/Centreon/Downtime/Downtime.json
- config/json_validator/latest/Centreon/Downtime/Downtimes.json
- config/packages/dev/jms_serializer.yaml
- config/packages/jms_serializer.yaml
- config/packages/prod/Centreon.yaml
- config/packages/prod/jms_serializer.yaml
- config/packages/serializer/Centreon/Downtime.Downtime.yml
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Application/Controller/DowntimeController.php
- src/Centreon/Domain/Common/Assertion/Assertion.php
- src/Centreon/Domain/Common/Assertion/AssertionException.php
- src/Centreon/Domain/Downtime/Downtime.php
- src/Centreon/Domain/Downtime/DowntimeService.php
- src/Centreon/Domain/Monitoring/Serializer/ResourceExclusionStrategy.php
- src/Centreon/Infrastructure/Serializer/ObjectConstructor.php
- symfony.lock
- www/include/monitoring/downtime/AddDowntime.php
- www/include/monitoring/downtime/template/AddDowntime.ihtml
Allows you to create downtimes up to 2038
> fix(downtimes) Prevent the user from creating downtimes with start date, end date and duration after 2037 (#9985)

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.17.php
> chore(install): update version to 20.04.17

- www/install/insertBaseConf.sql
- www/install/php/Update-20.10.10.php
> chore(install): update to version 20.10.10

- bin/migrate_php74.sh
- bootstrap.php
- src/Centreon/Domain/Monitoring/Resource.php
- www/class/centreonAuth.MySQL.class.php
- www/include/common/common-Func.php
- www/install/php/Update-18.10.1.php
- www/install/php/Update-18.10.2.php
- www/install/php/Update-18.10.3.php
- www/install/php/Update-18.10.4.php
- www/install/php/Update-18.10.5.php
- www/install/php/Update-19.04.2.php
- www/install/php/Update-19.10.0-beta.2.php
- www/install/php/Update-20.04.0-rc.1.php
- www/install/php/Update-20.04.0-rc.2.php
- www/install/php/Update-20.04.0-rc.3.php
- www/install/php/Update-20.04.0.php
- www/install/php/Update-20.04.3.php
- www/install/php/Update-20.04.5.php
- www/install/php/Update-20.04.6.php
- www/install/php/Update-20.10.0-beta.1.php
- www/install/step_upgrade/functions.php
- www/main.get.php
add compatibility with php 7.4 + add migration script
**Fixes** MON-7342
> chore(php): add compatibility with php 7.4 + add migration script

- Jenkinsfile
set reference job in each recordIssues
> chore(ci): set reference job in each recordIssues

- SECURITY_ACK.md
Add a reporter to security acknowledgement
> enh(secu): add reporter name

- bin/migrate_php73.sh
add script to upgrade php 7.2 to 7.3
thanks @adr-mo 
**Fixes** MON-7341
> chore(php): add script to upgrade php 7.2 to 7.3

- Jenkinsfile
This allows to generate a docker image on centos8 for QA branches
> fix(CI): Allow to build a docker image with centos8 tag on QA branches

- bin/migrate_php74.sh
fail on error when upgrading php
**Fixes** MON-7342
> fix(php): fail on error when upgrading php

- Jenkinsfile
- behat.yml
Remove feature files that provoke random acceptance tests failures while we found a way to make them reliable.
Relates to [that error](https://jenkins.int.centreon.com/blue/organizations/jenkins/centreon-web/detail/master/3117/pipeline/671/)
> fix(test): adapt AT feature files listing

- composer.json
- composer.lock
- config/Modules/Centreon.yaml
- config/json_validator/latest/Centreon/Downtime/Downtime.json
- config/json_validator/latest/Centreon/Downtime/Downtimes.json
- config/packages/dev/jms_serializer.yaml
- config/packages/jms_serializer.yaml
- config/packages/prod/jms_serializer.yaml
- config/packages/serializer/Centreon/Downtime.Downtime.yml
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- src/Centreon/Application/Controller/DowntimeController.php
- src/Centreon/Domain/Common/Assertion/Assertion.php
- src/Centreon/Domain/Common/Assertion/AssertionException.php
- src/Centreon/Domain/Downtime/Downtime.php
- src/Centreon/Domain/Downtime/DowntimeService.php
- src/Centreon/Domain/Monitoring/Serializer/ResourceExclusionStrategy.php
- src/Centreon/Infrastructure/Serializer/Exception/SerializerException.php
- src/Centreon/Infrastructure/Serializer/ObjectConstructor.php
- symfony.lock
- www/class/centreonExternalCommand.class.php
- www/include/monitoring/downtime/AddDowntime.php
- www/include/monitoring/downtime/template/AddDowntime.ihtml
- www/include/monitoring/external_cmd/popup/massive_downtime.php
- www/include/monitoring/external_cmd/popup/templates/massive_downtime.ihtml
Prevent the user from creating downtimes with start date, end date and duration after 2037.
Controls added on :
- UI interfaces
- API
- CLAPI
> fix(downtimes) Prevent the user from creating downtimes with start date, end date and duration after 2037

- www/install/insertBaseConf.sql
- www/install/php/Update-20.04.18.php
> chore(install): update to version 20.04.18

- www/install/insertBaseConf.sql
> chore(install): update to version 20.10.11

- doc/API/centreon-api-v21.10.yaml
retrieve authentication api doc
**Fixes** MON-6752
> fix(doc): retrieve authentication api doc

- .github/CODEOWNERS
- SECURITY_ACK.md
Update security acknowledgement page
> enh(secu): update security ack

- Jenkinsfile
In order to speed up the Web pipeline, we introduced more //lisation and we deliver rpm on yum repository instead of srvi repo.
> enh(ci): more //lised pipeline workflow

- Jenkinsfile
Fixes the condition for delivery in order to have the right rpm installed in the next step, docker creation.
> deliver package before docker creation for develop branches

- .github/workflows/dependabot_jira.yml
Change action event trigger to automate ticket creation
> enh(chore) change action event trigger to create ticket

- .github/dependabot.yml
- .github/workflows/dependabot_jira.yml
Limit to 10 updates
Ignore patch and non essential updates
> enh(dependabot): remove patch update

- .github/dependabot.yml
Ignore all dependencies updates.
Should be overriden on security updates
> fix(chore): ignore all non security related updates

- unattended.sh
Canged simple redirect to append redirect when setting timezone in ini php file.
> fix(unattended): fix redirect of initial timezone to php ini file

- Jenkinsfile
update qa branch of serie 21.10
> chore(ci): update qa branch of serie 21.10

- sonar-project.properties
Remove parsing errors and other warnings in the logs by excluding sql upgrade scripts
> enh(chore): clear sonarQube analysis logs

- sonar-project.properties
Exclude missing tests folder, when pipeline is related only to backend files
> fix(chore): avoid flapping QG results

- Jenkinsfile
Unstash dependencies required to analyse TS
> fix(chore): unstash required dependencies

- Jenkinsfile
fix api doc version in jenkinsfile
> fix(ci): fix api doc version in jenkinsfile

- libinstall/functions
optimize apache configuration
**Fixes** MON-11799
> chore(apache): optimize apache configuration

- README.md
Update supported versions in readme
> enh(readme): update supported versions

- .github/workflows/dependabot_jira.yml
Fix dependabot random pipeline failure
> fix(chore): dependabot pipeline failure

- Jenkinsfile
fix checkout of centreon-build
Check CI
> fix(ci): fix checkout of centreon-build

- Jenkinsfile
> fix(chore): skip SQ QG on canary jobs

- libinstall/functions
This PR intends to Add Set Cookie to apache conf
**Fixes** # MON-12056
> enh(conf): Add Set Cookie to apache conf

- Jenkinsfile
> add-unstash-el8

- doc/API/NotificationPolicy.yaml
- doc/API/centreon-api-v22.04.yaml
add api doc for notification policy endpoints
**Fixes** MON-10908
> doc(api): add api doc for notification policy endpoints

- Jenkinsfile
> fix(build): Add missing parallel function call for docker stage

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
update translation of “hard/soft”  (should'nt be translated into French)
> fix : MON-12903-filter-translation

- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
remove duplicated translations
**Fixes** MON-13015
> fix(translation): remove duplicated translations

- Jenkinsfile
retry checkout of centreon-build (3 times)
> fix(ci): retry checkout of centreon-build

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> fix(translations): Fix translations

- ci/debian/centreon-common.postrm
- ci/debian/centreon-trap.postinst
- ci/debian/centreon-trap.postrm
- ci/debian/centreon-web.postinst
> fix issues with post scripts debian

- lang/es_ES.UTF-8/LC_MESSAGES/messages.po
- lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
- lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
remove duplicate translation
Refs: MON-13160
> fix(translation): remove duplicate translation

- unattended.sh
Updated version to 22.04
Updated password generation to be compliant with the new security policy.
> enh(unattended): update version and password generation for 22.04

- Jenkinsfile
- ci/scripts/centreon-deb-package.sh
> Normalize VERSION variable to Debian format

- ci/debian/centreon-common.postinst
- ci/debian/centreon-poller-centreon-engine.postinst
- ci/debian/centreon-web-apache.postinst
- ci/debian/centreon-web.postinst
> Fix permissions for Debian packages

- ci/debian/centreon-poller-centreon-engine.postinst
> add missing permission group in postinst Debian package

- ci/debian/centreon-web-apache.postinst
> Add apache to gorgone group missing

- .github/CODEOWNERS
Fix codeowner team affectation errors and enhance team security scope
> chore(git): correct codeowners file

- ci/debian/control
- ci/debian/extra/centreon-web/centreon-macroreplacement.txt
- ci/debian/rules
> improves macro handling

- ci/debian/centreon-poller-centreon-engine.postinst
- ci/debian/centreon-web-apache.postinst
- ci/debian/centreon-web.postinst
> Add new permissions postinst debian

- SECURITY_ACK.md
update security acknowledgement page
> chore(doc): update security acknowledgement

- ci/debian/centreon-web-apache.postinst
- ci/debian/centreon-web.install
- ci/scripts/centreon-deb-package.sh
> Add missing locale and api doc Debian build

- Jenkinsfile
update the debian repo version in order to deliver package into 22.10 apt repo
> fix(ci): update debian repo version

- ci/debian/centreon-poller-centreon-engine.postinst
- ci/debian/control
> (debian) remove chmod from non exist file

- ci/debian/centreon-web.postinst
- ci/debian/control
> (debian) Fix issues centreon install

- ci/debian/centreon-trap.postinst
- ci/debian/control
> (debian) snmptrap permissions issues

- ci/debian/extra/centreon-web/crontab/centreon
> (debian) fix username for apache

- .github/CODEOWNERS
> Update centreon-documentation and centreon-devops codeowners
